### ISSUE TITLE
Issues with opening the templates

### ISSUE THREAD

**Issue by JimScott0** [saesrpg/donation-vehicle-shaders#10]
I can't open the templates anymore, it says:
 Photoshot cannot read this file. This is not a valid bitmap file, or this format is not supported.

I looked up this problem on google and saw a video about this problem. It said that I had to open it with paint but I can't open it with paint either.

**Comment by Dufabo** [comment]
Try to use photoshop 2018 or 2019 it should help.

**Comment by tutgreco** [comment]
the PSD template works fine on Adobe photoshop 2017. it should work fine on earlier and later versions too
