### ISSUE TITLE
Steven's Custom Wrap

### ISSUE THREAD

**Issue by steven517** [saesrpg/donation-vehicle-shaders#100]
**Vehicle ID**
598

**Wrap access**
st3v3n517

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/17758/donation-therealsteven-amount-5-00-gbp
https://saesrpg.uk/topic/16528/donation-therealsteven-amount-10-00-gbp
(I dont need a donation changed, I have no donation vehicle at the moment, will have it added once this wrap is live)

**Wrap image**
https://i.imgur.com/UVcEwqU.png

**Comment by steven517** [comment]
https://i.imgur.com/VvK8WpE.jpg

**Comment by tutgreco** [comment]
598: https://imgur.com/a/zcRIVtv

**Comment by steven517** [comment]
https://i.imgur.com/msc8yrB.jpg

**Comment by tutgreco** [comment]
598: https://imgur.com/a/P46DToC

**Comment by steven517** [comment]
https://i.imgur.com/iBRNgDQ.jpg

**Comment by steven517** [comment]
if this last one looks okay, this is good to go

**Comment by tutgreco** [comment]
598: https://imgur.com/a/sCcp19z
I'll just need the donation thread linked in original post for verification

**Comment by steven517** [comment]
Done @tutgreco

**Comment by tutgreco** [comment]
Wrap added as `st3v3n517_1`
