### ISSUE TITLE
Kowalskis Wrap Request

### ISSUE THREAD

**Issue by Kowalski1245** [saesrpg/donation-vehicle-shaders#101]
**Vehicle ID**
560

**Wrap access**
killerboy5678 (me), velona77 (velona)

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/20023/donation-kowalski-amount-20-00-gbp

**Wrap image
![AA_sultan](https://user-images.githubusercontent.com/67747920/86370734-5f5d3080-bc80-11ea-8807-748b112bb03c.png)

**Comment by tutgreco** [comment]
The text on the side is going to be facing the wrong way on the other side (which will be on the right side in this case). There is no way to go about this. Would you still like this tested or will you make further adjustments first?

**Comment by Kowalski1245** [comment]
Edited and adjusted here is the new wrap image:
![AA_sultan](https://user-images.githubusercontent.com/67747920/86499302-c7983900-bd8a-11ea-8805-243a96176d38.png)

**Comment by tutgreco** [comment]
560: https://imgur.com/a/0iMCnaR

**Comment by Kowalski1245** [comment]
Adjusted the text again so it's right and not mirrored

**Comment by tutgreco** [comment]
It's looking good to me. Adding this

**Comment by tutgreco** [comment]
Wrap added as `killerboy5678_1`
