### ISSUE TITLE
Stone's Custom Wrap Update

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/donation-vehicle-shaders#102]
This one should replace mrslowguy_1 I believe.

**Vehicle ID**
598: Police LV

**Wrap access**
mrslowguy (stone) and anyone else who has my permission.

**Needs testing**
If it seems good, go ahead and add it. We trust you

**Thread for reward change**
https://saesrpg.uk/topic/16159/donation-mrslowguy-amount-50-00gbp - 16th of March
https://saesrpg.uk/topic/16358/donation-mrslowguy-amount-30-00-gbp - 20th of March
https://saesrpg.uk/topic/17874/donation-safp-stoner-amount-100-00-gbp - 21st of April

**Wrap image**
https://cdn.discordapp.com/attachments/700180497023631390/726945045374304336/SAFP_dodge.png

**NEW REQUEST**

**Vehicle ID**
490 FBI Rancher (Chevy Tahoe)

**Wrap Access**
mrslowguy (stone) and anyone else who has my permission.

**Needs Testing**

If it seems good, go ahead and add it. We trust you

**Wrap Image**

https://cdn.discordapp.com/attachments/700180497023631390/726238417674829892/SAFPrancher.png

**Comment by tutgreco** [comment]
Both are looking good to me. Are there more coming or do you want the rest removed?

**Comment by MrSlowGuy** [comment]
You can remove everything else except the turismo wraps. I will be requesting 2 different wraps once I recieve them. 1 for crown vic and 1 for police LV. Burrito wrap can be deleted

**Comment by MrSlowGuy** [comment]
Sorry! Please replace the Turismo wrap with this one. 

Vehicle ID
451 Turismo (Lamborghini)

Wrap access
mrslowguy (stone) and anyone else who has my permission.

Needs testing
If it seems good, go ahead and add it. We trust you

Thread for reward change
https://saesrpg.uk/topic/16159/donation-mrslowguy-amount-50-00gbp - 16th of March
https://saesrpg.uk/topic/16358/donation-mrslowguy-amount-30-00-gbp - 20th of March
https://saesrpg.uk/topic/17874/donation-safp-stoner-amount-100-00-gbp - 21st of April

Wrap image
https://cdn.discordapp.com/attachments/700180497023631390/720617564870279218/SAFP_turismo.png

**Comment by tutgreco** [comment]
It's looking good to me, adding this together with the rest :+1:

**Comment by tutgreco** [comment]
598 added as replacement for `SAFPCharger`
490 added as replacement for `mrslowguy_3`
451 added as replacement for `SAFPTurismo`
The remaining unwanted wraps were removed on request
