### ISSUE TITLE
Steven's Custom SGT Wrap

### ISSUE THREAD

**Issue by steven517** [saesrpg/donation-vehicle-shaders#103]
**Vehicle ID**
506

**Wrap access**

**Needs testing**
Yes

**Thread for reward change**
Just need to see how this looks ingame, and will donate the required amount if I like it

**Wrap image**
https://i.imgur.com/TzKrPN6.jpg

**Comment by tutgreco** [comment]
506: https://imgur.com/a/SeXDcRS

**Comment by steven517** [comment]
All good, thanks tut, you may close this
