### ISSUE TITLE
FoxZilla's Wrap #1

### ISSUE THREAD

**Issue by Lahanaa** [saesrpg/donation-vehicle-shaders#104]
**Vehicle ID**
506 (SGT)

**Wrap access**
Just me i am doing it for test shader (my username is mertt)

**Needs testing**
yes

**Thread for reward change**
I wont use it i am designer i want to test it

**Wrap image
https://imgur.com/a/nKqF3wU

**Comment by tutgreco** [comment]
506: https://imgur.com/a/KbsWAAS

**Comment by Lahanaa** [comment]
Thanks tut i have took the image
