### ISSUE TITLE
FoxZilla's Custom wrap #2

### ISSUE THREAD

**Issue by Lahanaa** [saesrpg/donation-vehicle-shaders#105]
**Vehicle ID**
451

**Wrap access**
For Testing just me mertt

**Needs testing**
yes

**Thread for reward change**
nope just designing
**Wrap image
https://cdn.discordapp.com/attachments/729194426013843487/729197860058562581/template.png

**Comment by tutgreco** [comment]
451: https://imgur.com/a/wddpSG2
