### ISSUE TITLE
Cheess' custom donation wrap

### ISSUE THREAD

**Issue by Cheessoufle** [saesrpg/donation-vehicle-shaders#106]
**Vehicle ID** 400

**Wrap access** Everyone

**Needs testing** Yes

**Thread for reward change** https://saesrpg.uk/topic/20129/donation-cheess-amount-10-00-gbp

**Wrap image  https://cdn.discordapp.com/attachments/728213451679465512/730349573654183976/1141234141235412.png

**Comment by Cheessoufle** [comment]
I got PSD file if you wanto to

**Comment by tutgreco** [comment]
400: https://imgur.com/a/hsMH0n4
I won't need the PSD

**Comment by Cheessoufle** [comment]
Hm, the AA FTW at the back aint really working. I would like to have that changed. If you cant change it, I could

**Comment by tutgreco** [comment]
I'm not doing it sorry

**Comment by Cheessoufle** [comment]
Okey, np. I will change it and tell you when it's done.

**Comment by Cheessoufle** [comment]
I got it fixed now Tut. Could you test it again? @tutgreco

**Comment by tutgreco** [comment]
400: https://imgur.com/a/YDrnef5
If the low detail appearence of the people bothers you, you could increase resolution to 1024x1024, but this will quadruple the file size. Another workaround would be adding sharpening filters to the image so that the pixels will be less blurry and have more contrast in itself.

**Comment by Cheessoufle** [comment]
It's fine like this, thanks

**Comment by Cheessoufle** [comment]
When will it get added?

**Comment by tutgreco** [comment]
There's no ETA. We're adding the 'completed' label to it once it's available. :+1:

**Comment by tutgreco** [comment]
Wrap added as `cheessoufle_1` without username restriction
