### ISSUE TITLE
ANARCHY's wrap request

### ISSUE THREAD

**Issue by anarchy35** [saesrpg/donation-vehicle-shaders#108]
**Vehicle ID** 402

**Wrap access** sadi31

**Needs testing** Yes

**Thread for reward change** https://saesrpg.uk/topic/20125/donation-anarchy-30-00-gbp

**Wrap image** https://i.imgur.com/Nvdm2zY.png

**Comment by tutgreco** [comment]
402: https://imgur.com/a/surUog8
FYI the text on spoiler uses same place as the trunk.

**Comment by anarchy35** [comment]
can you test this? : https://i.imgur.com/tON4pBZ.jpg

**Comment by tutgreco** [comment]
402: https://imgur.com/a/FUJV20i

**Comment by anarchy35** [comment]
it's look good i am okey with it

**Comment by tutgreco** [comment]
Wrap added as `sadi31_1`
