### ISSUE TITLE
FoxZilla's custom wrap #3 (Need 2 testing)

### ISSUE THREAD

**Issue by Lahanaa** [saesrpg/donation-vehicle-shaders#109]
#1 
**Vehicle ID**
598

**Wrap access**
mertt

**Needs testing**
yes

**Thread for reward change**
after testing i may make it.

**Wrap image
https://imgur.com/a/Nx175m9

#2 
**Vehicle ID**
598

**Wrap access**
mertt

**Needs testing**
yes

**Thread for reward change**
after testing i may make it.

**Wrap image
https://imgur.com/a/F5pDNYU

**Comment by tutgreco** [comment]
You need to remove the Turkish flag and the logo on the side, as well as any words that are not English.

**Comment by Lahanaa** [comment]
There is no way to solve the problem without remove?

**Comment by tutgreco** [comment]
It's against the donation wrap rules for emergency vehicles to have the afforementioned contents in them

**Comment by Lahanaa** [comment]
Okay i'm going to close this topic i will make it to diffrent vehicle. Thank you tut <3
