### ISSUE TITLE
Wraps request 

### ISSUE THREAD

**Issue by Dufabo** [saesrpg/donation-vehicle-shaders#11]
Wrap #1 
Vehicle ID: 598
Wrap access : IF possible group "desert" if not possible username : dufabo1900
Image link : https://i.imgur.com/tHxCdRT.png

Wrap #2 
Vehicle ID: 598
Wrap access : dufabo1900
Image link : https://i.imgur.com/7zcCYsE.png

**Comment by tutgreco** [comment]
Wrap 1 = dufabomil
Wrap 2 = dufabocop
they are on their way

**Comment by tutgreco** [comment]
the wrap is live now.

**Comment by tutgreco** [comment]
the police version of your wraps has been ruled disallowed and removed, you're welcome to request a different wrap.  @Dufabo
