### ISSUE TITLE
Daniel's custom warp

### ISSUE THREAD

**Issue by 3Bo0** [saesrpg/donation-vehicle-shaders#110]
**Vehicle ID**
490 

**Wrap access**
3bo010 ( in-game name is: Daniel ) + xxmrtrollstylexx ( in-game name is: Niklaus ) 

**Needs testing**
Yes, after I agree, you can upload it

**Thread for reward change**
https://saesrpg.uk/topic/19608/donation-daniel-%D0%B2%D0%B8%D1%81%D0%B5%D0%BB%D0%B8%D1%86%D0%B0-3970-amount-20-00-gbp 

**Wrap image**
![9WyXGxF](https://user-images.githubusercontent.com/67001169/86963185-c8efaa00-c16c-11ea-9428-1b43e780a5cb.png)

https://i.imgur.com/9WyXGxF.png

**Comment by 3Bo0** [comment]
**Add bumper & police siren light on the warp**

**Comment by tutgreco** [comment]
490: https://imgur.com/a/IOqtuY1 
With lightbar: https://i.imgur.com/rV7taVp.png

**Comment by 3Bo0** [comment]
Aight now you can upload it

**Comment by tutgreco** [comment]
Please specify that for the admin sorting it in-game, as that's considered an upgrade for your donation vehicle. :+1:

**Comment by tutgreco** [comment]
Wrap added as `3bo010_1`
