### ISSUE TITLE
FoxZilla's Custom Wrap #4

### ISSUE THREAD

**Issue by Lahanaa** [saesrpg/donation-vehicle-shaders#111]
**Vehicle ID**
506

**Wrap access**
mertt

**Needs testing**
yes

**Thread for reward change**
i want to test first.

**Wrap image**
Uploaded to here
![kendimicinsgt](https://user-images.githubusercontent.com/67840082/87126581-1c5d1780-c295-11ea-8f6b-43b3a7aec0d8.png)

**Comment by tutgreco** [comment]
506: https://imgur.com/a/nQxlJqS

**Comment by tutgreco** [comment]
Are you still looking to get the wrap added? @Lahanaa

**Comment by Lahanaa** [comment]
Thanks for remiend i wont use it
