### ISSUE TITLE
pinkyyys wrap

### ISSUE THREAD

**Issue by PinkyyyTinkyyy** [saesrpg/donation-vehicle-shaders#113]
**Vehicle ID**
451 Turismo

**Wrap access**
Just me ( t1nk3rt0ts ) 

**Needs testing**
Yes please :D 

**Thread for reward change**
https://saesrpg.uk/topic/18235/donation-pinkyyytinkyyy-amount-40-00-gbp?_=1594788309698

**Wrap image
https://imgur.com/gallery/rYKLqNg

**Comment by tutgreco** [comment]
For the final version please ensure to keep image resolutions of 512x512 or 1024x1024.
To qualify for 1024x1024, the image must be well detailed and not just upscaled from the current resolution. That's because its file size is 4 times 512x512.
451: https://imgur.com/a/ODUAbpl

**Comment by tutgreco** [comment]
Are you still looking to get the wrap added? @PinkyyyTinkyyy
