### ISSUE TITLE
LV Police template fix/update

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#114]
Vehicle ID
598 Police LV (Slicktop version) Under: denis10_2

Wrap access
denis10 

Needs testing
Yes

Image color profile
RGB

https://images-ext-1.discordapp.net/external/58z9CCqMurMvmdU2EUvbOAnT-TQe--8VgWszyX5JVpA/https/i.imgur.com/vnxI1HI.png?width=528&height=528

---------------------------------------------------------------------

Vehicle ID
598 Police LV (Lightbars version) Under: denis10_3

Wrap access
denis10 

Needs testing
Yes

Image color profile
RGB

https://images-ext-2.discordapp.net/external/7Yp6WlCMqnweZwR-fNyE6fhiVmX8AnSNo30PJmfn6gc/https/i.imgur.com/K1r7VRj.png?width=528&height=528

**Comment by tutgreco** [comment]
What's wrong with them?

**Comment by TheRealElement** [comment]
Nothing wrong, that's a fix (With the new template), the current one in-game is a bit buggy.
