### ISSUE TITLE
Sanek's Custom Wrap

### ISSUE THREAD

**Issue by SanekFox** [saesrpg/donation-vehicle-shaders#115]
**Vehicle ID**
< 416 >

**Wrap access**
< cahek23 >

**Needs testing**
<  yes >

**Thread for reward change**
<  https://saesrpg.uk/topic/20453/donation-sanek-amount-20-00-gbp?_=1595157670775  >

**Wrap image
<  https://imgur.com/oCSSIIr  >

**Comment by tutgreco** [comment]
416: https://imgur.com/a/0yydeD4

**Comment by SanekFox** [comment]
Update: https://imgur.com/NEpuncy

**Comment by tutgreco** [comment]
416: https://imgur.com/a/UrX3ksB

**Comment by SanekFox** [comment]
Final https://imgur.com/a/X8t2sBT

**Comment by tutgreco** [comment]
You may have noticed that the 3 stripes can't be wrapped. I'll see if this can be made possible but I can't promise as it would require every other wrap to be updated alongside. Anyway I'm adding this :+1:

**Comment by SanekFox** [comment]
<3

**Comment by IEDaryl** [comment]
You've made a spelling mistake. It's spelled 'Response' not 'Responce'.

**Comment by SanekFox** [comment]
Final v2 https://imgur.com/a/viBhDUm
Ty for your attention Daryl

**Comment by tutgreco** [comment]
Wrap added as `cahek23_3`
