### ISSUE TITLE
taavilaudur's custom wrap

### ISSUE THREAD

**Issue by TaaviLaudur1312** [saesrpg/donation-vehicle-shaders#116]

**Comment by TaaviLaudur1312** [comment]
Vehicle ID
< 560 >

Wrap access
< Hell Soldier members >

Needs testing
< yes >

Thread for reward change
Will be made soon

**Wrap image
https://imgur.com/lFVeOOp

**Comment by tutgreco** [comment]
I think including anything related to nazism is taking it too far. Can you please adjust this and we'll have it tested shortly.
The wrap can be applied to a vehicle as long as 1 of the people locked to it is added to the `wrap access`. Can you please specify which usernames needs adding :+1:

**Comment by TaaviLaudur1312** [comment]
Updated

**Comment by tutgreco** [comment]
560: https://imgur.com/a/Zqvwwva

**Comment by TaaviLaudur1312** [comment]
Yeah that what its supposed to look like :)

**Comment by tutgreco** [comment]
Wrap added as `snakeer_1`
