### ISSUE TITLE
Car test

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#117]
Hello i asked Tut to test my car and he told me to make github request here
**Needs testing**
Yes please

**Wrap image
https://imgur.com/koFo3oz

**Comment by tutgreco** [comment]
Please link your donation thread for this reward

**Comment by Liyones** [comment]
> Please link your donation thread for this reward

nah i don't have i just would like to test it

**Comment by tutgreco** [comment]
If we were to test wraps for people who haven't donated, we would be wasting our time testing things that aren't going to see the light in the server.

**Comment by Liyones** [comment]
@tutgreco Q - Dance will add it

**Comment by tutgreco** [comment]
Only donators should make github issues for wraps. This also applies if their designer wants it tested before having it added. In this case it's the QDance member who wants the wraps that should make the request.
Additionally groups are not eligible for wraps
