### ISSUE TITLE
Sanfara's Custom Wrap

### ISSUE THREAD

**Issue by Sanfara44** [saesrpg/donation-vehicle-shaders#119]
**Vehicle ID**
598

**Wrap access**
At the moment, no one

**Needs testing**
Yes, Honestly I made this topic just to test it, since this wrap is the first one I make.

**Thread for reward change**
Didn't request the wrap yet.

**Wrap image
https://i.imgur.com/VehMdNk.png

**Comment by tutgreco** [comment]
We'll need a valid request for a wrap for this to be processed, closing.
