### ISSUE TITLE
Custom wrap for Police Ford Crown Vic

### ISSUE THREAD

**Issue by SanekFox** [saesrpg/donation-vehicle-shaders#12]
Vehicle ID: 596
Wrap access locked to username: SanekFox
https://imgur.com/a/wGpTnbn

**Comment by tutgreco** [comment]
Wrap is on its way to the server, no ETA yet.
Its name is 'SheriffSanek'

**Comment by tutgreco** [comment]
the wrap is live now.

**Comment by tutgreco** [comment]
@SanekFox 
596 template was updated, get the latest here:
https://saesrpg.uk/topic/8309/about-donation-wraps

It underwent many changes, making your current wrap unusable. I'll leave the thread open for a month. If you prefer to not submit an updated version, we'll have to remove it.

**Comment by SanekFox** [comment]
https://imgur.com/a/IIF2B02 new one

**Comment by tutgreco** [comment]
596: https://imgur.com/a/t5Ocuz2

**Comment by SanekFox** [comment]
https://imgur.com/a/WJlJ5Zq

**Comment by tutgreco** [comment]
596: https://imgur.com/a/xJmOvch

**Comment by SanekFox** [comment]
Nice!))

**Comment by tutgreco** [comment]
on the right side, are you able to horizontally flip the sheriff's star? It reads backwards @SanekFox

**Comment by SanekFox** [comment]
https://imgur.com/a/79T6ir3
