### ISSUE TITLE
ProNuBs SANA wrap for burrito.

### ISSUE THREAD

**Issue by ProNuBs** [saesrpg/donation-vehicle-shaders#120]
**Vehicle ID**

482

**Wrap access**

iampronubs; jojofromjory; jonas13362; bulgur; heyheuhei; teelor

**Needs testing**

Yes

**Thread for reward change**

Will be donating if the test turns out to look nice enough

**Wrap image

https://i.imgur.com/j5aZPTd.png

**Comment by ProNuBs** [comment]
**Thread for reward change**

https://saesrpg.uk/topic/20796/pronubs-reward-change-31st-july-2020

**Comment by tutgreco** [comment]
482: https://imgur.com/a/BlstnUO
