### ISSUE TITLE
Sollozzo's Custom Wrap

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#121]
_40 GPB : 2 Vehicles + 2 Custom Wraps_
https://saesrpg.uk/topic/20803/donation-sollozzo-amount-40-00-gbp

**First Vehicle :** 

**Vehicle ID**
 598 - Police LV

**Wrap access**
sollozzo

**Needs testing**
No, Thanks

**Thread for reward change**
https://saesrpg.uk/topic/20803/donation-sollozzo-amount-40-00-gbp

**Wrap image**
https://i.imgur.com/gEisba1.png

---

**Second Vehicle :** 

**Vehicle ID**
 490 - FBI Rancher

**Wrap access**
sollozzo

**Needs testing**
No, Thanks

**Thread for reward change**
https://saesrpg.uk/topic/20803/donation-sollozzo-amount-40-00-gbp

**Wrap image**
https://i.imgur.com/jsqcw5f.png

Thank you.

**Comment by tutgreco** [comment]
The wraps were added as `sollozzo_5` and `sollozzo_6`
