### ISSUE TITLE
bardo45 - Custom wrap patch

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#122]
Patch for the Hertog Jan van 2.0

**!!! Please overwrite this on bardo45_2  !!!**

**Vehicle ID**
482 Burrito (custom)

**Wrap access**
bardo45 (me)

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/20278/bart-s-reward-change?_=1596280949461

**Wrap image**
https://i.imgur.com/LivETpK.png

Thank you!

**Comment by tutgreco** [comment]
As a small note, we've added wrap compatibility for news van and added a version for civilians, so if you now have an option to get the wrap for an equivalent of chevrolet g20 if you like. Anyway thanks for submitting the patch
