### ISSUE TITLE
SANA News van wrap

### ISSUE THREAD

**Issue by ProNuBs** [saesrpg/donation-vehicle-shaders#123]
**Vehicle ID**

582 (News Van)

**Wrap access**

iampronubs; jojofromjory; jonas13362; bulgur; heyheuhei; teelor

**Needs testing**

Yes

**Thread for reward change**

https://saesrpg.uk/topic/20796/pronubs-reward-change-31st-july-2020

**Wrap image

https://i.imgur.com/Et61P5Gh.jpg

**Comment by tutgreco** [comment]
582: https://imgur.com/a/1eNCteI

**Comment by ProNuBs** [comment]
We've reworked it a bit. V2 : https://i.imgur.com/s47M3V5.png

**Comment by tutgreco** [comment]
The changes doesn't justify a test since the hood graphics should be easily imagined from the first test. Would you like this added right away, and if so, can you please send as either 512x512 or 1024x1024.

**Comment by ProNuBs** [comment]
This one should be the right size : https://i.imgur.com/GP80DJ1h.jpg

**Comment by tutgreco** [comment]
Wrap added as replacement for the wrap `nub`
