### ISSUE TITLE
Halo`s donation 

### ISSUE THREAD

**Issue by halomiro** [saesrpg/donation-vehicle-shaders#124]
**Vehicle ID**
 490

**Wrap access**
 buch

**Needs testing**
 Yes sir

**Thread for reward change**
 https://saesrpg.uk/topic/20824/donation-halo-amount-20-gbp/2?_=1596686303991

**Wrap image
 https://imgur.com/gallery/FDntvbo

**Comment by tut98** [comment]
490: https://imgur.com/a/6MsU1iR
Parts of the texture is really low detailed. Would it be possible for you to enhance them? Otherwise can you please consider adding it as 512x512 image resolution.

**Comment by halomiro** [comment]
https://imgur.com/a/bbpTcyc

Done sir

**Comment by halomiro** [comment]
https://imgur.com/a/fqo9mll

Done sir

**Comment by tut98** [comment]
Would you like this tested or uploaded now? @halomiro

**Comment by halomiro** [comment]
Yes please, test my custom

**Comment by tut98** [comment]
490: https://imgur.com/a/AAG5Jkv

**Comment by halomiro** [comment]
Perfect tuti 👯

**Comment by tut98** [comment]
done
