### ISSUE TITLE
Q-Dance SAES custom wrap newsvan radio dj

### ISSUE THREAD

**Issue by Cheessoufle** [saesrpg/donation-vehicle-shaders#126]
**Vehicle ID** 582

**Wrap access** [AA]Cheess (cheessoufle)

**Needs testing** Yes

**Thread for reward change** https://saesrpg.uk/topic/21471/donation-cheess-amount-100-00-gbp

**Wrap image** https://cdn.discordapp.com/attachments/728213451679465512/749197092425170994/DJ.png

**Comment by tut98** [comment]
For this and #127 we'll need a forum thread to process the reward. Please send a notice when that's done and add that to your issue 👍

**Comment by Cheessoufle** [comment]
https://saesrpg.uk/topic/21471/donation-cheess-amount-100-00-gbp

**Comment by tut98** [comment]
582: https://imgur.com/a/LOqHoNP

**Comment by Cheessoufle** [comment]
I will edit it a bit

**Comment by Cheessoufle** [comment]
Got a new wrap image https://cdn.discordapp.com/attachments/728213451679465512/749197092425170994/DJ.png

**Comment by tut98** [comment]
582: https://imgur.com/a/ms3tQml

**Comment by Cheessoufle** [comment]
Look great! Can be added ingame.

**Comment by tut98** [comment]
Wrap added as `cheessoufle_2`
