### ISSUE TITLE
Q-Dance SAES custom wrap Burrito member

### ISSUE THREAD

**Issue by Cheessoufle** [saesrpg/donation-vehicle-shaders#127]
**Vehicle ID** 482 

**Wrap access** [AA]Cheess (cheessoufle)

**Needs testing** Yes

**Thread for reward change** https://saesrpg.uk/topic/21471/donation-cheess-amount-100-00-gbp

**Wrap image** https://cdn.discordapp.com/attachments/728213451679465512/749197087639339028/memeber.png

**Comment by Cheessoufle** [comment]
https://saesrpg.uk/topic/21471/donation-cheess-amount-100-00-gbp

**Comment by tut98** [comment]
482: https://imgur.com/a/xJWH26c

**Comment by Cheessoufle** [comment]
Will edit it a bit

**Comment by Cheessoufle** [comment]
Got a new wrap image. Added it to the main post either. https://cdn.discordapp.com/attachments/728213451679465512/749197087639339028/memeber.png

**Comment by tut98** [comment]
482: https://imgur.com/a/CcqMkUE

**Comment by Cheessoufle** [comment]
Look great! Can be added ingame.

**Comment by tut98** [comment]
Wrap added as `cheessoufle_4`
