### ISSUE TITLE
Q-Dance SAES custom wrap Burrito builder

### ISSUE THREAD

**Issue by Cheessoufle** [saesrpg/donation-vehicle-shaders#128]
**Vehicle ID** 482

**Wrap access** [AA]Cheess (cheessoufle)

**Needs testing** Yes

**Thread for reward change** Not yet 

**Wrap image**  https://cdn.discordapp.com/attachments/728213451679465512/749197089031979018/builder.png

**Comment by Cheessoufle** [comment]
I got 2 **different** versions of the Burrito I would like to have added. I will add my donation thread soon.

**Comment by Cheessoufle** [comment]
https://saesrpg.uk/topic/21471/donation-cheess-amount-100-00-gbp

**Comment by tut98** [comment]
This wrap has nearly the same detailing, so the preview on the Members van will suffice
_Originally posted by @tut98 in https://github.com/saesrpg/donation-vehicle-shaders/issues/127#issuecomment-683210415_

**Comment by Cheessoufle** [comment]
Got a new wrap image. Edited at the main post either. https://cdn.discordapp.com/attachments/728213451679465512/749197089031979018/builder.png

**Comment by Cheessoufle** [comment]
And you could you test it again for #126 , #127 and #128 please?

**Comment by tut98** [comment]
482: https://imgur.com/a/n9fY9bk

**Comment by Cheessoufle** [comment]
Look great! Can be added ingame.

**Comment by tut98** [comment]
Wrap added as `cheessoufle_3`
