### ISSUE TITLE
Police LV wrap

### ISSUE THREAD

**Issue by MToreno** [saesrpg/donation-vehicle-shaders#129]
**Vehicle ID** 598

**Wrap access** SWAT members

**Needs testing** Yes

**Thread for reward change**  https://saesrpg.uk/topic/21485/toreno-s-reward-change

**Wrap image**
![Final](https://user-images.githubusercontent.com/46752607/91635807-c76b9100-e9fb-11ea-81e0-e469b5e09911.png)

**Comment by tut98** [comment]
I'm sorry, the Netherlands flag needs removing 👍 
See _[Note for emergency vehicle wraps](https://saesrpg.uk/topic/8309/about-donation-wraps)_

**Comment by MToreno** [comment]
Well that sucks, replaced it with the American flag now

![finals](https://user-images.githubusercontent.com/46752607/91636225-49a98480-e9ff-11ea-887e-8942b3564c4d.png)

**Comment by tut98** [comment]
598: https://imgur.com/a/gkePwRk

**Comment by MToreno** [comment]
![finals2](https://user-images.githubusercontent.com/46752607/91663109-193d1580-eae7-11ea-82f5-157276915718.png)

**Comment by tut98** [comment]
598: https://imgur.com/a/BucnGDt

Please make sure that the final image resolution is either 512x512 or 1024x1024

**Comment by MToreno** [comment]
![finals4](https://user-images.githubusercontent.com/46752607/91713008-34606180-eb89-11ea-8c12-9d1473fe31d0.png)

**Comment by MToreno** [comment]
Final version, resized to 512x512

Usernames: bendrin12, xxzizouxx, mertt, lightning, xicesmashx, denis10, milicajac, bas260, CyberGhost

**Comment by tut98** [comment]
Wrap added as ` monstercookie12_1`
