### ISSUE TITLE
Wrap request turismo

### ISSUE THREAD

**Issue by JimScott0** [saesrpg/donation-vehicle-shaders#13]
Wrap #1
Vehicle ID: 451
Wrap access : oximan42
Image link : https://imgur.com/yeTlggB

Wrap #2 Police turismo
Vehicle ID: 451
Wrap access : oximan42
Image link : https://imgur.com/VZh3O36

**Comment by tutgreco** [comment]
1 = OPD1
2 = OPD2
on their way

**Comment by tutgreco** [comment]
the wraps are live now.
