### ISSUE TITLE
Zizou _1 warp

### ISSUE THREAD

**Issue by ryadmahsoudi** [saesrpg/donation-vehicle-shaders#130]
**Vehicle ID** 598

**Wrap access**  SWAT members

**Needs testing** yes

**Thread for reward change** https://saesrpg.uk/topic/21543/zizou-s-reward-change

**Wrap image
https://cdn.discordapp.com/attachments/727249953990377542/750339516254126120/ZIZOUV2.png

**Comment by tut98** [comment]
598: https://imgur.com/a/WhKXnBZ

**Comment by ryadmahsoudi** [comment]
Looks perfect, Can be added in-game.

**Comment by tut98** [comment]
Please name 4 SWAT members here that you want to get access to the wrap @ryadmahsoudi

**Comment by ryadmahsoudi** [comment]
denis10 monstercoockie12 bendrin12 lightning12

**Comment by tut98** [comment]
Wrap added as `xxzizouxx_1`
