### ISSUE TITLE
Prada's Custom Wraps

### ISSUE THREAD

**Issue by Prada420** [saesrpg/donation-vehicle-shaders#132]
**Vehicle ID**
400

**Wrap access**

**Needs testing**
yes

**Thread for reward change**
1-https://saesrpg.uk/topic/21630/donation-prada-amount-10-00-gbp 2-https://saesrpg.uk/topic/21631/donation-prada-amount-10-00-gbp

**Wrap image
https://imgur.com/a/2QHxcsU

**Comment by tut98** [comment]
Please be mindful of the image quality when using 1024x1024 resolution. If it can't be sharpened up, please lower the resolution to 512x512.

**Comment by Prada420** [comment]
https://imgur.com/a/nzHLOFj

**Comment by tut98** [comment]
The quality did not change a bit. 1067x1067 is not allowed, it has to be either 512x512 or 1024x1024.

Adding to this, please make sure that the white fringe/edge is gone from the edges of the vehicle, else it will be seen in-game. When exporting the image, please use PNG with lossless compression to ensure it doesn't lose quality unnecessarily. 👍 

If you're uncertain how to resolve the white fringe, what you can do is hide the layer that creates the whiteness, and I assume it's the base guide layer that ships with the photoshop file. It's only useful when creating the design, as it allows you to use clipping masks.

**Comment by Prada420** [comment]
fixed it https://imgur.com/a/eD6C4g8

**Comment by tut98** [comment]
400: https://imgur.com/a/uZ0iJFn

**Comment by Prada420** [comment]
changed resolution needs to be tested  512x512 https://imgur.com/a/RhWR1RV

**Comment by tut98** [comment]
The 1024x1024 version looks better, but it's got a lot of color artifacts - would you be able to resolve them? 

Compare the former https://imgur.com/a/KEUeIDV with the latest https://imgur.com/a/LBwrS2y

**Comment by Prada420** [comment]
try with this one https://imgur.com/a/CxTtUPA

**Comment by tut98** [comment]
400: https://imgur.com/a/ntJLXno
Please be reminded that the resolution must be 512x512 or 1024x1024 (that one is 1080x1080)

**Comment by Prada420** [comment]
last change test plis https://imgur.com/a/qCGdGMV

**Comment by tut98** [comment]
400: https://imgur.com/a/25vtUrI

**Comment by Prada420** [comment]
ok the last one that's the one I want for the game

**Comment by tut98** [comment]
Wrap added as `iqprada_1`
