### ISSUE TITLE
Ntruder's custom wrap

### ISSUE THREAD

**Issue by Ntruder** [saesrpg/donation-vehicle-shaders#133]
**Vehicle ID**
482- Burrito

**Wrap access**
muric123

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/21625/donation-ntruder-amount-20-00-gbp?_=1599231223974

**Wrap image
 https://imgur.com/9LaeGog

**Comment by tut98** [comment]
482: https://imgur.com/a/2Psz7FD

**Comment by Ntruder** [comment]
https://imgur.com/a/mUF01Ih

**Comment by tut98** [comment]
482: https://imgur.com/a/Bk9i0jh
Please send final image as 512x512 or 1024x1024. If you go with the higher resolution, make sure that the pixel quality allows.

**Comment by Ntruder** [comment]
I suppose, this should fill the bill now. Let me know if there is still something incorrect.
https://imgur.com/L8gtmaf

**Comment by tut98** [comment]
Wrap added as `muric123_1`
