### ISSUE TITLE
Bas's Custom Wrap

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#134]
**Vehicle ID**
490

**Wrap access**
bas260, timmoto, jamesmpf, tut

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/21637/donation-bas260-amount-30-00-gbp

**Wrap image**

**Comment by bas260** [comment]
![template](https://user-images.githubusercontent.com/46720463/92272986-d6b27900-eeea-11ea-92c3-439310ea7b62.png)

**Comment by tut98** [comment]
490: https://imgur.com/a/dw0z9mh
Please send the next ones with white (opaque) background

**Comment by tim260** [comment]
![safd_tahoe_commission](https://user-images.githubusercontent.com/28573423/92333954-74c35200-f057-11ea-8360-ba23cec4871a.png)

**Comment by tut98** [comment]
490: https://imgur.com/a/ggIkuma

**Comment by bas260** [comment]
![NFxDZsq](https://user-images.githubusercontent.com/46720463/92407812-f8ef0580-f13b-11ea-9c2a-8bdb896f31eb.png)

**Comment by bas260** [comment]
![NFxDZsq](https://user-images.githubusercontent.com/46720463/92407968-70249980-f13c-11ea-8eed-12b7ec9ca332.png)

**Comment by tut98** [comment]
490: https://imgur.com/a/vKEvLVc

**Comment by bas260** [comment]
Alright accept it.

**Comment by tut98** [comment]
Wrap added as `bas260_8`
