### ISSUE TITLE
Bas's Custom Wrap [2]

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#135]
**Vehicle ID**
596

**Wrap access**
bas260, timmoto & jamesmpf

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/21683/donation-bas260-amount-20-00-gbp

**Wrap image
![safd_crownvic_wrap](https://user-images.githubusercontent.com/46720463/92333730-12cf1080-f088-11ea-9ed9-6549e9b309b3.png)

**Comment by tut98** [comment]
Wrap added as `bas260_7`
