### ISSUE TITLE
Douglass's Custom Wrap

### ISSUE THREAD

**Issue by manuel4693** [saesrpg/donation-vehicle-shaders#136]
**Vehicle ID**
560 (sultan)

**Wrap access**
subkage,FelixOvalles12

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/21690/douglass-s-reward-change

**Wrap image**
https://i.imgur.com/uuvze4U.png

**Comment by tut98** [comment]
560: https://imgur.com/a/EnxCSWR

**Comment by manuel4693** [comment]
> 560: https://imgur.com/a/EnxCSWR

Perfect

**Comment by manuel4693** [comment]
@tut98 when added to game?

**Comment by tut98** [comment]
No idea.

**Comment by tut98** [comment]
Wrap added as `subkage_1`
