### ISSUE TITLE
Velo's Custom Wrap

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#137]
**Vehicle ID**
604

**Wrap access**
velona77

**Needs testing**
Yes

**Thread for reward change**
There's not one yet as I have never seen a Damaged Glendale wrap ingame. I want to see how it reflects before making the decision.

**Wrap image
![template_glenshit](https://user-images.githubusercontent.com/46403782/92419474-6881e680-f176-11ea-81d3-225cd36ff197.png)

**Comment by tut98** [comment]
It should look fine, eventually give it a look with generic wraps in SF cardealership, second floor. You can scroll through wraps/cars using arrowkeys.

Unfortunately I'll need a thread to process the donation. I hope the above helps 🙂

**Comment by Velona77** [comment]
There it is - https://saesrpg.uk/topic/21716/velona-s-reward-change

**Comment by tut98** [comment]
604: https://imgur.com/a/wInJPVB

**Comment by Velona77** [comment]
This one should be OK, doesn't need an extra test
![template_glenshit](https://user-images.githubusercontent.com/46403782/92420791-f8775e80-f17d-11ea-824e-72c68db2d3e8.png)

**Comment by tut98** [comment]
Wrap added as `velona77_3`
