### ISSUE TITLE
Rondaw's Custom Wrap

### ISSUE THREAD

**Issue by Rondaw** [saesrpg/donation-vehicle-shaders#138]
**Vehicle ID**
604 (Glendale)

**Wrap access**
league1

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/21502/donation-rondaw-amount-30-00-gbp/3?_=1599562767076

**Wrap image**
https://imgur.com/a/RTmlOyq

**Comment by tut98** [comment]
Is it possible for you to send as either 256x256 or 512x512? If it gets upscaled to 512x512, please make sure that the image quality justifies it. 256x256 is relative low and will look quite blurry on vehicles.

**Comment by Rondaw** [comment]
> 
> 
> Is it possible for you to send as either 256x256 or 512x512? If it gets upscaled to 512x512, please make sure that the image quality justifies it. 256x256 is relative low and will look quite blurry on vehicles.

https://i.imgur.com/wMtLGJUh.jpg i hope this one is fine.

**Comment by tut98** [comment]
604: https://imgur.com/a/3aGUQBk

**Comment by tut98** [comment]
Is there any interest in having this wrap added?

**Comment by tut98** [comment]
I'll go ahead and close this, you're welcome to reopen it at any time.
