### ISSUE TITLE
tim260's Custom Wrap

### ISSUE THREAD

**Issue by tim260** [saesrpg/donation-vehicle-shaders#139]
**Vehicle ID**
596 Police LS

**Wrap access**
timmoto

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/21784/tim260-s-reward-change
**This wrap is only to be added to vehicle 1 & 2, I will create another custom wrap request for the third vehicle**

**Wrap image
![spvm-crown-vic](https://user-images.githubusercontent.com/28573423/92997044-32c66000-f4de-11ea-81c3-933546d5cfc9.png)

**Comment by tut98** [comment]
Wrap added as `timmoto_1`
