### ISSUE TITLE
Wraps request

### ISSUE THREAD

**Issue by RicardaPrimis** [saesrpg/donation-vehicle-shaders#14]
#Wrap 1
Vehicle ID: 451
Wrap access locked to usernames (leave blank if public): GirlyPrimis

#Wrap2
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): GirlyPrimis

#Wrap 3
Vehicle ID: 596
Wrap access locked to usernames (leave blank if public): GirlyPrimis

![BuffaloCIA](https://user-images.githubusercontent.com/53186122/61646046-7c376880-aca8-11e9-9eac-8ff9fb78189c.png)
![CrownVicCIA](https://user-images.githubusercontent.com/53186122/61646047-7c376880-aca8-11e9-844e-d2bbfb7d9dbb.png)
![turisimoCIA](https://user-images.githubusercontent.com/53186122/61646048-7c376880-aca8-11e9-911b-7a5babf68021.png)

**Comment by tutgreco** [comment]
wraps are on their way

**Comment by tutgreco** [comment]
the wraps are live now.
