### ISSUE TITLE
Tim260's Custom Wrap [2]

### ISSUE THREAD

**Issue by tim260** [saesrpg/donation-vehicle-shaders#140]
**Vehicle ID**
596 Police LS

**Wrap access**
_Anyone_

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/21784/tim260-s-reward-change
**This is only for vehicle 3. For the first 2 I have requested a different wrap**

**Wrap image
![generic-crown-vic](https://user-images.githubusercontent.com/28573423/92998844-660eec00-f4ea-11ea-9104-9b7b871b2208.png)

**Comment by tut98** [comment]
Wrap added as `timmoto_2`
