### ISSUE TITLE
Tim260's Custom Wrap [3]

### ISSUE THREAD

**Issue by tim260** [saesrpg/donation-vehicle-shaders#141]
**Vehicle ID**
490 FBI Rancher

**Wrap access**
_Anyone_

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/21784/tim260-s-reward-change

**Wrap image
![state-police-tahoe](https://user-images.githubusercontent.com/28573423/92997129-e9c2db80-f4de-11ea-8a10-55f22f8b7e7f.png)

**Comment by tut98** [comment]
Wrap added as `timmoto_3`
