### ISSUE TITLE
Bas's Custom Wrap Update 

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#142]
I'd like to have the shader that's currently on my 2 FBI rancher in SAI base replaced with the one below. 
The IDs of the FBI ranchers in-game are 17062 and 17064. I don't know what number the wrap that's on it right now has.

**Vehicle ID**
490

**Wrap access**
bas260, denis10

**Needs testing**
no

**Thread for reward change**
None

**Wrap image
![FEDERAL_PROTECTIVE_SERVICE](https://user-images.githubusercontent.com/46720463/93463101-9211df00-f8e7-11ea-8650-fb94f259551b.png)

**Comment by tut98** [comment]
Please show a screenshot of the wrap that it's meant to replace

**Comment by bas260** [comment]
![sai_icv](https://user-images.githubusercontent.com/46720463/93507390-e6d04c80-f91d-11ea-8cef-f13abade3244.png)
It's replacing this one

**Comment by bas260** [comment]
Close this without any change @Tut.
