### ISSUE TITLE
Real Custom Wrap

### ISSUE THREAD

**Issue by Turealpro11** [saesrpg/donation-vehicle-shaders#143]
**Vehicle ID**
 Turismo>Lamborghini

**Wrap access**
 

://i.imgur.com/**Needs testing**
 Yes

**Thread for reward change**

**Wrap image
 https://i.imgur.com/dnyCYJq.jpg

**Comment by tut98** [comment]
451: https://imgur.com/a/c6TlqpN

**Comment by tut98** [comment]
Is there any interest in having this wrap added?

**Comment by tut98** [comment]
@Turealpro11 I'm leaving a notice here, please see above

**Comment by Turealpro11** [comment]
If there is interest but there are some things missing to modify, my
pc damaged so I have not finished it but I will finish it soon

**Comment by tut98** [comment]
Ok, hardware issues can take a while to fix. Please reopen if you need to. Closing this as it's inactive for days.
