### ISSUE TITLE
Sollozzo's Custom Wrap Request + Fixes

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#145]
Hello, I would like to request 3 custom wraps for my last donation of 60 GBP : https://saesrpg.uk/topic/21933/donation-sollozzo-amount-60-00-gbp : 

(+) and a fix for `sollozzo_3` , and `sollozzo_4`

_3 custom wraps for 3 vehicles :_ 

---

**Vehicle ID**
451 - Police Turismo

**Wrap access**
sollozzo, 40salih
`sollozzo_7`

**Needs testing**
Yes, please. 

**Thread for reward change**
https://saesrpg.uk/topic/21933/donation-sollozzo-amount-60-00-gbp

**Wrap image**
https://i.imgur.com/g8ENW61.png
<sup>MIT - Police Turismo</sup>

---

**Vehicle ID**
596 Police LS (Crown Vic)

**Wrap access**
sollozzo, 40salih
`sollozzo_8`

**Needs testing**
No, thanks. 

**Thread for reward change**
https://saesrpg.uk/topic/21933/donation-sollozzo-amount-60-00-gbp

**Wrap image**
https://i.imgur.com/NOKPdLK.png
<sup>MIT - Crown Victoria</sup>

---

**Vehicle ID**
598 Police LV (GTA5)

**Wrap access**
sollozzo, 40salih
`sollozzo_9`

**Needs testing**
No, thanks. 

**Thread for reward change**
https://saesrpg.uk/topic/21933/donation-sollozzo-amount-60-00-gbp

**Wrap image**
https://i.imgur.com/cZUA54i.png
<sup>MIT - Police LV Clean</sup>

---

To be fixed : 
---

Fix for `sollozzo_3` : 
**Model :** 598 - Police LV
**Image :** https://i.imgur.com/I0F7gXC.png <sup>(MIT - Police LV Emergency)</sup>
**Original post :** https://github.com/saesrpg/donation-vehicle-shaders/issues/89
Detail : Missing details since the migration to the new template + modification of the emergency stripes  + (red,white,red) claw

Fix for `sollozzo_4` : 
**Model :** 416 - Ambulance 
**Image :** https://i.imgur.com/9miMAYo.png <sup>(MIT - Police Truck)</sup>
**Original post :** https://github.com/saesrpg/donation-vehicle-shaders/issues/89
Detail : Modification of the emergency stripes + (red,white,red) claw

**Comment by tut98** [comment]
451: https://imgur.com/a/CFvEbXJ

**Comment by tut98** [comment]
Everything is live with the exception of 451

**Comment by SOLLOZZO-SAES** [comment]
Thank you very much, Im processing the 451

**Comment by SOLLOZZO-SAES** [comment]
Hi Tut, could you please try this one : 
451 - Police Turismo
https://i.imgur.com/RZKM25H.png

Sorry for the tests, the template isn't comfortable, but this one should be ok.
Thank you.

**Comment by tut98** [comment]
I can look at it by eye, and still tell that the door graphics are in lower height than the sides. You'll need to move the door-wraps up a bit. Try 2-3 pixels

**Comment by tut98** [comment]
@SOLLOZZO-SAES I'm leaving a notice here, please let us know if you choose to proceed with the last wrap or not

**Comment by SOLLOZZO-SAES** [comment]
> @SOLLOZZO-SAES I'm leaving a notice here, please let us know if you choose to proceed with the last wrap or not

Let me 24h to give you an update.

**Comment by tut98** [comment]
Closing this as it's been inactive for days. The rest of your wraps are live 2 weeks ago.
