### ISSUE TITLE
Garcia's Custom Wrap

### ISSUE THREAD

**Issue by Garcia125** [saesrpg/donation-vehicle-shaders#146]
**Vehicle ID**
400 Landstalker

**Wrap access**
benlaidabdou

**Needs testing**
Yes it does need testing

**Thread for reward change**
https://saesrpg.uk/topic/22055/garcia-s-reward-change

**Wrap image**
![alt text](https://i.imgur.com/82SvY1k.png)

**Comment by tut98** [comment]
The text would be very blurry on 512x512 resolution, so if you want it to read more clear I suggest upping it to 1024x1024.

**Comment by Garcia125** [comment]
@tut98 https://imgur.com/a/7kJ7ks5 i guess its fine now

**Comment by tut98** [comment]
It would be an idea to fix the scale of the hood's image, as simply upscaling it won't look good. Same goes for the red flag.

**Comment by Garcia125** [comment]
> 
> 
> It would be an idea to fix the scale of the hood's image, as simply upscaling it won't look good. Same goes for the red flag.

may i ask for images how it look ingame, cuz it is fine for me to look a bit with low quality

**Comment by tut98** [comment]
400: https://imgur.com/a/9ZGqcej

**Comment by Garcia125** [comment]
@tut98 yes i want that.

**Comment by tut98** [comment]
Wrap added as `benlaidabdou_1`
