### ISSUE TITLE
Stark's Custom Wrap

### ISSUE THREAD

**Issue by OG-Stark** [saesrpg/donation-vehicle-shaders#148]
**Vehicle ID**
400

**Wrap access**
n/a

**Needs testing**
yes

**Thread for reward change**
coming soon

**Wrap image
![template copy](https://user-images.githubusercontent.com/56271043/94354812-fc93ef00-004c-11eb-9f33-23be3ea8d507.png)

**Comment by tut98** [comment]
400: https://imgur.com/a/9Q7CO1h

**Comment by OG-Stark** [comment]
That's the best resolution that it can have ?

**Comment by tut98** [comment]
No, you can increase it to 1024x1024 if the overall image quality allows.

**Comment by OG-Stark** [comment]
You mean increase the template label to 1024x1024 or the picture of the wrap ?

**Comment by tut98** [comment]
Yes, you can increase the canvas to 1024x1024.

Increasing the image size to 1024x1024 will not improve the quality. If the source image is less than 1024x1024, then you'll be upscaling the pixels without gaining any quality improvement, so that won't be accepted.

**Comment by OG-Stark** [comment]
Lets try this one:

![G-Wagon2 0](https://user-images.githubusercontent.com/56271043/94494783-02f5a880-01be-11eb-8b30-b3cf45a38e9a.png)

**Comment by tut98** [comment]
It would be an idea to fix the white spots on the edges. Put a black background on it to clearly see the issue.

Please keep the black background on it, as we cannot accept images that has transparent backgrounds.

**Comment by OG-Stark** [comment]
Working on it

**Comment by OG-Stark** [comment]
![G-Wagon2 0](https://user-images.githubusercontent.com/56271043/94499492-dac07680-01ca-11eb-99a2-192d99937806.png)

**Comment by tut98** [comment]
400: https://imgur.com/a/J8FFOFq

**Comment by OG-Stark** [comment]
Beautiful, I love it

**Comment by OG-Stark** [comment]
https://saesrpg.uk/topic/22122/donation-stark-amount-20-00-gbp 

Can upload it Tut

**Comment by tut98** [comment]
Wrap added as `jt16_2`
