### ISSUE TITLE
Rocoso Custom Wrap

### ISSUE THREAD

**Issue by Rocoso15** [saesrpg/donation-vehicle-shaders#149]
**Vehicle ID**
490
**Wrap access**
Rocoso/Understaked015

**Needs testing**
Yes please

**Thread for reward change**
-https://saesrpg.uk/topic/21921/donation-rocoso-amount-50-00-gbp
-https://saesrpg.uk/topic/22103/rocoso-s-reward-change

**Wrap image**
![my truck](https://i.imgur.com/yh7QJHS.png)

**Comment by tut98** [comment]
490: https://imgur.com/a/GPfzelO
The submitted image is of incorrect size, please submit as either 512x512 or 1024x1024.

**Comment by Rocoso15** [comment]
![my truck](https://i.imgur.com/yh7QJHS.png)
Done sir

**Comment by tut98** [comment]
Wrap added as `rocoso_1`
