### ISSUE TITLE
ProNuBs wrap request

### ISSUE THREAD

**Issue by ProNuBs** [saesrpg/donation-vehicle-shaders#15]
Requesting a Custom wrap for all 3 of my ambulances (LS jefferson, LS All saints and LV)

Vehicle ID: 416
Access: iampronubs
https://i.imgur.com/tC1n4Gi.png

**Comment by ProNuBs** [comment]
In case the text on the side collides with the side door in the model :

https://i.imgur.com/Hqluf7W.png

**Comment by tutgreco** [comment]
It will not, but the text became more readable by scaling it up so I'll use the second one. It will be live on one of our upcoming server updates.

**Comment by ProNuBs** [comment]
https://i.imgur.com/NJdF0Co.png

Updated version as requested

**Comment by tutgreco** [comment]
> In case the text on the side collides with the side door in the model :
> 
> https://i.imgur.com/Hqluf7W.png

This is live now, please find a clan member to sort it for you.



> https://i.imgur.com/NJdF0Co.png
> 
> Updated version as requested (Fix)

I will add this in this week most likely

**Comment by ProNuBs** [comment]
what should be the final fix:

https://i.imgur.com/sGK9Ak5.png

**Comment by tutgreco** [comment]
the wrap is live now, closing this
