### ISSUE TITLE
Ntruder's Custom Wrap

### ISSUE THREAD

**Issue by Ntruder** [saesrpg/donation-vehicle-shaders#150]
**Vehicle ID**
405 Sentinel

**Wrap access**
muric123

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/21876/donation-ntruder-amount-20-00-gbp?_=1601325263199

**Wrap image**
https://imgur.com/a/EPR8yIa

**Comment by tut98** [comment]
560: https://imgur.com/a/TBqs0m9
The submitted image is of incorrect size, please submit as either 512x512 or 1024x1024.

**Comment by saesrpg** [comment]
test

**Comment by Ntruder** [comment]
Quick question, How can i adjust the sides in exactly the same way? 
This is how it should be [https://i.imgur.com/2hEq3xC.png](url)
but this is exactly opposite of it [https://i.imgur.com/FwJCAhY.png](url)

**Comment by tut98** [comment]
You can't. It reads opposite on one side, correct on the other.
If you don't want this defect, please don't put text on it, or choose another vehicle.

**Comment by Ntruder** [comment]
Edited the topic as i chosed another type of vehicle, you may find the details of the wrap out there.

**Comment by tut98** [comment]
405: https://imgur.com/a/WGIvpk5

**Comment by Ntruder** [comment]
one more testing please. https://imgur.com/a/XOWGiTs

**Comment by tut98** [comment]
405: https://imgur.com/a/XuoPKuJ

**Comment by Ntruder** [comment]
Take some photos of the both bumpers only, the rest parts are amazing.
https://imgur.com/a/VASRAom

**Comment by tut98** [comment]
405: https://imgur.com/a/I5M1aYy

**Comment by Ntruder** [comment]
It is all good, may go to live now.

**Comment by tut98** [comment]
Wrap added as `muric123_2`
