### ISSUE TITLE
Fenter90's wrap testing issue

### ISSUE THREAD

**Issue by Deebrio** [saesrpg/donation-vehicle-shaders#151]
**Vehicle ID**
482

**Wrap access**
(im not a donator, just testing my wrap)

**Needs testing**
yes

**Thread for reward change**
(im not a donator, just testing my wrap)

**Wrap image**
https://cdn.discordapp.com/attachments/619497058113552420/760503577574637578/template2_Buritto.png

**Comment by tut98** [comment]
482: https://imgur.com/a/YNUXXAi

**Comment by Deebrio** [comment]
back writings need to be edited, anyway thanks for helping :heart:

**Comment by tut98** [comment]
Ok, I can keep the issue up for a few days if you're planning on donating for it.

**Comment by Deebrio** [comment]
No you need, you can close it. i was just preparing it for the next Christmas donation discounts :p
