### ISSUE TITLE
Custom Spanish Wrap

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#152]
**Vehicle ID**
490

**Wrap access**
lapd0070, valgitin, understaked015, CristianEscobar

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/22145/donation-spanish-amount-10-00-gbp

**Wrap image**

**Comment by LAPDSpanishVEN** [comment]
![SAM 2](https://user-images.githubusercontent.com/72228343/94858428-67f10e80-0409-11eb-888a-b8a5c72285e4.jpg)

**Comment by tut98** [comment]
490: https://imgur.com/a/ZhHNHWj

**Comment by LAPDSpanishVEN** [comment]
![template SAM2 0](https://user-images.githubusercontent.com/72228343/94881506-0eee9e00-043c-11eb-8cbe-99fda9bbeed0.jpg)

**Comment by tut98** [comment]
490: https://imgur.com/a/wEHrFCC

**Comment by LAPDSpanishVEN** [comment]
![template SAM final](https://user-images.githubusercontent.com/72228343/94890066-9b0cbf80-0454-11eb-9f6f-a7621eab7c78.jpg)
final test, and sorry for the inconvenience

**Comment by tut98** [comment]
490: https://imgur.com/a/uRFcHvT

**Comment by LAPDSpanishVEN** [comment]
I think it looks good, I accept it

**Comment by tut98** [comment]
Wrap added as `lapd0070`
