### ISSUE TITLE
Wrap Real 

### ISSUE THREAD

**Issue by Turealpro11** [saesrpg/donation-vehicle-shaders#154]
**Vehicle ID**
 Turismo

**Wrap access**

**Needs testing**
 Si

**Thread for reward change**

**Wrap image**
 https://media.discordapp.net/attachments/748109850512195625/764515025674174474/templatelambo22.jpg?width=406&height=406

**Comment by tut98** [comment]
Please submit as 512x512 or 1024x1024.

**Comment by Turealpro11** [comment]
Ok Wait

**Comment by Turealpro11** [comment]
https://i.imgur.com/pTQAsyR.jpg

**Comment by Turealpro11** [comment]
there it is

**Comment by tut98** [comment]
I'm sorry, it's 406x406. It needs to be 512x512 or 1024x1024 image size

**Comment by Turealpro11** [comment]
Wait pls

**Comment by Turealpro11** [comment]
https://imgur.com/a/jI9GpfS

**Comment by tut98** [comment]
451: https://imgur.com/a/XbMJeKZ

**Comment by Turealpro11** [comment]
https://i.imgur.com/43a6ba5.jpg

**Comment by Turealpro11** [comment]
That gucci wrap can be fixed since I don't like how much it is being pliss haci let's not take so much struggle I just want that gucci made my name somewhere and some logos that suit that wrap if you can pretend it was for you please please

**Comment by Turealpro11** [comment]
Brotho if you can fix that wrap already and I do my best but it is not as I want if you can make a gucci wrap with some logos that match the wrap

**Comment by tut98** [comment]
I need .psd, not .jpg to fix it

**Comment by Turealpro11** [comment]
http://www.mediafire.com/file/7b3nj1elovdebe2/templatelambo22.psd/file

**Comment by tut98** [comment]
In response to your PM, I've not agreed to add extra graphics to your design, only to fix it which would assumably be the stripes not lining up.

As such I'm closing this, please create another issue when you have the files ready.
