### ISSUE TITLE
Niklaus's 2nd Custom Wrap

### ISSUE THREAD

**Issue by Niklaus-187** [saesrpg/donation-vehicle-shaders#156]
**Vehicle ID**
400
**Wrap access**
xxmrtrollstylexx and iqprada
**Needs testing**
Yes please
**Thread for reward change**
https://saesrpg.uk/topic/22524/donation-niklaus-amount-15-00-gbp
**Wrap image**

https://i.imgur.com/O25VdoG.png

**Comment by tut98** [comment]
The patterns with simple text doesn't require testing. If you're happy with this version I'll go ahead and add it.

**Comment by Niklaus-187** [comment]
@tut98 Alright, go ahead and add it, please.

**Comment by tut98** [comment]
Wrap added as `xxmrtrollstylexx_2`
