### ISSUE TITLE
Element's custom warps.

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#158]
1) **Vehicle ID** 
400 Landstalker (G wagon)

**Wrap access**
denis10

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/22547/donation-element-amount-50-00-gbp?_=1603308268641

**Wrap image**
https://i.imgur.com/jArCru1.png

-----------------------------------------------------------------------------------------------------------------------------------

2) **Vehicle ID** 
604 Glendale shit (Pontiac)

**Wrap access**
denis10

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/22547/donation-element-amount-50-00-gbp?_=1603308268641

**Wrap image**
https://i.imgur.com/aFwLxGM.png

-----------------------------------------------------------------------------------------------------------------------------------

3) **Vehicle ID** 
582 News van (custom)

**Wrap access**
denis10

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/22547/donation-element-amount-50-00-gbp?_=1603308268641

**Wrap image**
https://i.imgur.com/cCEt4ci.png

**Comment by tut98** [comment]
I'm sorry, anything that's associated with police and emergency services must be native to the US.

**Comment by TheRealElement** [comment]
The warps are not going to be used on police/emergency vehicles.

**Comment by tut98** [comment]
Vehicle 1: https://imgur.com/a/BrwDsuV
Vehicle 2: https://imgur.com/a/dBGfwhM
Vehicle 3: https://imgur.com/a/X6GeFAl
Vehicle 4: https://imgur.com/a/2WpPhzq

**Comment by TheRealElement** [comment]
The request has been updated with new & updated warps.

**Comment by tut98** [comment]
400: https://imgur.com/a/gniTvqe
582: https://imgur.com/a/JwMEyiQ
604: https://imgur.com/a/jdGFqKr

**Comment by TheRealElement** [comment]
Here's a fix: 

400: https://i.imgur.com/GqllIRE.png
582: https://i.imgur.com/uRjadPK.png
604:https://i.imgur.com/zAHqNqp.png

Needs testing, please.

**Comment by tut98** [comment]
400: https://imgur.com/a/NtXmnUR
582: https://imgur.com/a/mPAMvVa
604: https://imgur.com/a/Kj0fZe6

**Comment by TheRealElement** [comment]
Perfect, I would love to see them in-game, please.

**Comment by tut98** [comment]
ID 400 added as `denis10_7`
ID 582 added as `denis10_8`
ID 604 added as `denis10_9`

Brightness of ID 604 is an issue on our end, and will be patched later today or the weekend. Please set vehicle color to grey if it's an issue for the time being
