### ISSUE TITLE
Henry's wrap change

### ISSUE THREAD

**Issue by SAESHenry** [saesrpg/donation-vehicle-shaders#159]
**Vehicle ID**
604

**Wrap access**
mierburns

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/16564/donation-henry-amount-20-00-gbp (changing current mierburns_1)

**Wrap image**

https://i.imgur.com/PzDj4Td.jpg

**Comment by tut98** [comment]
604: https://imgur.com/a/UVbXST0

**Comment by SAESHenry** [comment]
I've changed front color, I will go with this one, doesn't need testing.

https://i.imgur.com/grKKwOw.jpg

**Comment by tut98** [comment]
Wrap added as `mierburns_2`
