### ISSUE TITLE
Ardron's LV Police Car Wrap

### ISSUE THREAD

**Issue by Ardron92** [saesrpg/donation-vehicle-shaders#16]
Hello!
Requesting a wrap for my police LV car!
Link: https://imgur.com/a/d86f2rB
Vehicle ID: 598
Usernames: king1992

Thanks!

**Comment by DemienD** [comment]
You've rotated the image, that might form a problem :p 
And everything that's white won't be recolored, so did you mean the car to be white? If so change the grey background as well :)

- Dyam

**Comment by tutgreco** [comment]
Besides the rotation being incorrect, there are a few issues present in the wrap:
The left side 'Ardron+2 flags' needs to be moved to the left (aka down towards the ground) as  they're too close to the car roof. This is only the case for the left side.
The roof texture (unit and wings) needs to be flipped 180 degrees.

**Comment by Ardron92** [comment]
Updated as requested
https://imgur.com/a/xOd9VvS

**Comment by tutgreco** [comment]
will be live in one of the coming server updates

**Comment by tutgreco** [comment]
the wrap is live now, closing this
