### ISSUE TITLE
Negan's custom wrap 

### ISSUE THREAD

**Issue by Negan-juuc1498** [saesrpg/donation-vehicle-shaders#160]
**Vehicle ID**
506 Super GT (Shelby GR1)

**Wrap access**
juuc1498, sollozzo, 40salih

**Needs testing**
Yes, please.

**Thread for reward change**
https://saesrpg.uk/topic/22600/donation-negan1498-amount-15-00-gbp

**Wrap image**
https://i.imgur.com/MvrnrZy.jpg

**Comment by tut98** [comment]
What does the text on the sides read?

**Comment by Negan-juuc1498** [comment]
Means "Turk" in Cyrillic script

**Comment by tut98** [comment]
506: https://imgur.com/a/3hllD6H

**Comment by Negan-juuc1498** [comment]
Thanks, can be pushed

**Comment by tut98** [comment]
It has been pushed

I'll close once it's been approved

**Comment by tut98** [comment]
Wrap added as `juuc1498_1`

Please note it's cut down to 512x512 as we've changed the allowed limits.
