### ISSUE TITLE
Real 

### ISSUE THREAD

**Issue by Turealpro11** [saesrpg/donation-vehicle-shaders#161]
**Vehicle ID**
 turismo

**Wrap access**
 turealpro11

**Needs testing**
It needs to be tested and if you can align the lines

**Thread for reward change**

**Wrap image**
<!-- Preferably upload and attach the file here, or use an image hosting website and link it h 
http://www.mediafire.com/file/pfwcl2y3l851olu/templatelambo22.psd/file

**Comment by tut98** [comment]
Ok, I'll see what can be done

**Comment by tut98** [comment]
The lines line up OK.

Not perfect but they're fine to me.

If you're happy with the current version I'll go ahead and add it.

**Comment by Turealpro11** [comment]
can you show me?

**Comment by tut98** [comment]
Check #154 comments

**Comment by Turealpro11** [comment]
If you want, you can add it and put it on my car or how it works I must make a reward change

**Comment by tut98** [comment]
Ok it'll be on server soon.

Once issue is closed you can make a reward change.

**Comment by Turealpro11** [comment]
Ok

**Comment by tut98** [comment]
Wrap added as `turealpro11_1`
