### ISSUE TITLE
Mackey's custom wrap

### ISSUE THREAD

**Issue by mackey21** [saesrpg/donation-vehicle-shaders#162]
**Vehicle ID**
400 Landstalker (G wagon)

**Wrap access**
zizi31

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/22457/donation-mackey-amount-15-00-gbp

**Wrap image**
https://imgur.com/a/XCMTXLp

**Comment by tut98** [comment]
What's written on the sides?

**Comment by mackey21** [comment]
funny Turkish words

**Comment by tut98** [comment]
What does it translate to

**Comment by mackey21** [comment]
First door : I couldn't quit neither smoking nor you, one destroyed my heart, the other my lunghs...
Second door: I could not translate exactly , but they dont really make sense because they're song lyrics from turkish songs, you can ask any turkish admin to verify

**Comment by mackey21** [comment]
I made some changes, left door is the same, right door i burned my youth for that smile instead of a cigarette and at the back door do not bet on the bundesliga

**Comment by tut98** [comment]
The wrap should not need testing if you have followed the photoshop template guides.

Would you like this added or make adjustments first?

**Comment by mackey21** [comment]
I want it to be set first

**Comment by tut98** [comment]
It looks fine to my eye.

**Comment by mackey21** [comment]
Well then you can add

**Comment by tut98** [comment]
Wrap added as `zizi31_1`
