### ISSUE TITLE
FoxZilla's Custom Wrap

### ISSUE THREAD

**Issue by Lahanaa** [saesrpg/donation-vehicle-shaders#163]
**Vehicle ID**
604

**Wrap access**
mertt

**Needs testing**
yes

**Thread for reward change**
N/A

**Wrap image**
https://imgur.com/a/UHlLF9J (its 1024x1024 can you make it 512x512 I tried but texts cant read)
https://i.imgur.com/p7MwgnP.jpg (its 512x512 but texts cant read)

**Comment by tut98** [comment]
What does the text say?

**Comment by Lahanaa** [comment]
at the front bumper "Hoşçakal diyen geri gelmiyor mecnun."
at the left front side "Her şeyi ve herkesi karşımıza almadan, ne sen leyla olabilirsin nede ben mecnun."
at the left back side "Kelimeler... Kelimeler albayım, bazı anlamlara gelmiyor."
at the top side (roof) " "Eksik Bir şey mi var hayatta?" " and " Leyla ile Mecnun "
at the right back side "Insanız sonuçta. bize en çok zarar verenden ayrı kalamıyoruz."
at the front of the right back side " Gitti işte. - sanki buram çok acıyo gibi ha. - Buram sanki, buram çok acıyor gibi oldu şimdi. - Bu acı geçiyor mu?"
at the middle right side " Ben De Özledim " and "Çok yanlızım n'olur dağılmayın lan!"
at the right front side "Hop giremezsin."

**Comment by tut98** [comment]
The wrap should not need testing if you have followed the photoshop template guides.

Would you like this added or make adjustments first?

**Comment by Lahanaa** [comment]
actually I checked but I cloudnt test the car can you help me?

**Comment by tut98** [comment]
It does not have anything that needs lining up or synchronising with other sides. Why does it need testing? The template is fairly accurate representation of how it's going to look in game.

**Comment by tut98** [comment]
Request seems inactive, closing. Feel free to reopen as you like
