### ISSUE TITLE
HaKy's custom wrap

### ISSUE THREAD

**Issue by Haky22** [saesrpg/donation-vehicle-shaders#164]
1)

**Vehicle ID**
482 Burrito (custom)

**Wrap access**
hakypehbiu

**Needs testing**
yes

**Thread for reward change**
[https://saesrpg.uk/topic/22706/donation-haky-amount-45-00-gbp](url)

**Wrap image**
[https://imgur.com/a/vn2QfjE](url)

2)

**Vehicle ID**
482 Burrito (custom)

**Wrap access**
hakypehbiu

**Needs testing**
yes

**Thread for reward change**
[https://saesrpg.uk/topic/22706/donation-haky-amount-45-00-gbp](url)

**Wrap image**
[https://imgur.com/a/Yr6PIEe](url)

3)

**Vehicle ID**
405 Sentinel (BMW M5)

**Wrap access**
hakypehbiu

**Needs testing**
yes

**Thread for reward change**
[https://saesrpg.uk/topic/22706/donation-haky-amount-45-00-gbp](url)

**Wrap image**
[https://imgur.com/a/rGjbkyr](url)

**Comment by tut98** [comment]
Granted you followed the guides in the photoshop template none of them will need a testing.

Would you like them added now or make more adjustments first?

**Comment by Haky22** [comment]
Yes , add them pls

**Comment by tut98** [comment]
> Yes , add them pls
> 
> Edit: only 1 question , bmw m5 its black and white yes ?
> Bcz I make it blwhite and and white and at img its looks like grey , can I only see bmw and if its really black and white add them

It's grey and white. If you want it black please do so.

**Comment by Haky22** [comment]
New wrap BMW M5 405

[https://imgur.com/a/1zKxUTy](url)

Done

**Comment by tut98** [comment]
Wraps added as `hakypehbiu_1` through 3
