### ISSUE TITLE
Sollozzo's Custom Wrap + Fixes

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#165]
Hello, I would like to request 2 new wraps + 2 fixes
**Thread for reward change**:
https://saesrpg.uk/topic/22711/donation-sollozzo-amount-30-00-gbp

---

**Vehicle ID**
598 Police LV (GTA5)

**Wrap access**
Sollozzo
`sollozzo_10`

**Needs testing**
No, thanks

**Wrap image**
https://i.imgur.com/Afl8dG6.png
<sup>MIT - Police Old Concept</sup>

---

**Vehicle ID**
598 Police LV (GTA5)

**Wrap access**
Sollozzo
`sollozzo_11`

**Needs testing**
No, thanks

**Wrap image**
https://i.imgur.com/kxiIqXy.png
Latin text = Intelligenti Pro Patria = Intelligence for the Homeland (MIT Motto)
<sup>MIT - Special Guard</sup>

---

## To be fixed :  
**Vehicle ID**
451 - Police Turismo

**Wrap access**
sollozzo, 40salih
`sollozzo_7`

**Thread for reward change**
https://saesrpg.uk/topic/21933/donation-sollozzo-amount-60-00-gbp

**Wrap image**
https://i.imgur.com/N6utmMp.png
<sup>MIT - Police Turismo</sup>

---
**Vehicle ID**
596 Police LS (Crown Vic)

**Wrap access**
sollozzo, 40salih
`sollozzo_8`

**Thread for reward change**
https://saesrpg.uk/topic/21933/donation-sollozzo-amount-60-00-gbp

**Wrap image**
https://i.imgur.com/KA1sCsL.png
<sup>MIT - Crown Victoria</sup>

---
No need tests.
I would also like to know if the Sultan Police was possible to modify with the Sultan template ? and of course the possibility of modifying more vehicle will be appreciated.

Thank you.

**Comment by tut98** [comment]
To answer your last question, it isn't yet possible, but we might consider it at a later point
