### ISSUE TITLE
Rocoso Custom Wrap

### ISSUE THREAD

**Issue by Rocoso15** [saesrpg/donation-vehicle-shaders#166]
**Vehicle ID**
490  / FBI Rancher
**Wrap access**
Understaked015 / Rocoso
**Needs testing**
Yes please
**Thread for reward change**
https://saesrpg.uk/topic/22800/rocoso-s-reward-change
**Wrap image**
https://i.imgur.com/iwRP40M.png

**Comment by tut98** [comment]
I have tested and it lines up correctly, I'll go ahead and add this now

**Comment by Rocoso15** [comment]
Thanks sir

**Comment by Rocoso15** [comment]
Sir this wrap alredy put ingame?

**Comment by tut98** [comment]
Currently not on live.

**Comment by Rocoso15** [comment]
copy

**Comment by tut98** [comment]
Wrap added as `understaked015_2`

I'm sorry for having you waiting weeks.
