### ISSUE TITLE
Rocoso Wrap 2

### ISSUE THREAD

**Issue by Rocoso15** [saesrpg/donation-vehicle-shaders#167]
**Vehicle ID**
490  / FBI Rancher
**Wrap access**
Understaked015 / Rocoso
**Needs testing**
Yes please
**Thread for reward change**
https://saesrpg.uk/topic/22800/rocoso-s-reward-change
**Wrap image**
https://i.imgur.com/aGn8mqR.png

**Comment by tut98** [comment]
It should not need testing. If you're happy with the current design I'll go ahead and add it.

**Comment by Rocoso15** [comment]
Yes please add it

**Comment by Rocoso15** [comment]
Sir this wrap alredy put ingame?

**Comment by tut98** [comment]
Wrap added as `understaked015_3`
