### ISSUE TITLE
Rocoso Wrap 3

### ISSUE THREAD

**Issue by Rocoso15** [saesrpg/donation-vehicle-shaders#168]
**Vehicle ID**
598 / Police LV
**Wrap access**
Understaked015 / Rocoso
**Needs testing**
Yes please
**Thread for reward change**
https://saesrpg.uk/topic/22800/rocoso-s-reward-change
**Wrap image**
https://i.imgur.com/Z2t7hur.png

**Comment by tut98** [comment]
It should not need testing. If you're happy with the current design I'll go ahead and add it.

**Comment by Rocoso15** [comment]
Yes add it please

**Comment by Rocoso15** [comment]
Sir this wrap alredy put ingame?

**Comment by tut98** [comment]
Wrap added as `understaked015_4`
