### ISSUE TITLE
Prada's Custom Wrap

### ISSUE THREAD

**Issue by Prada420** [saesrpg/donation-vehicle-shaders#169]
**Vehicle ID** 604
glendale

**Wrap access** iqprada
 JUST ME!!!!! iqprada

**Needs testing**
YES

**Thread for reward change**

**Wrap image**
 https://imgur.com/a/ttuW8F1

**Comment by tut98** [comment]
604: https://imgur.com/a/fmVlkjB

**Comment by Prada420** [comment]
i will fix the line of the back

**Comment by Prada420** [comment]
can u try this one https://imgur.com/a/TGiOAip

**Comment by tut98** [comment]
Yes, next week.
> **Wrap access**
> 
> JUST ME!!!!!
Please specify the username as the template asks.

**Comment by tut98** [comment]
I'm afraid I haven't been able due to temporary network issues.

I hope you've been able to follow the last review that I sent here. If you'd like I can go ahead and add your wrap at my earliest convenience.

**Comment by Prada420** [comment]
need be fixep up can u help me with this. the lines of the back they are not well placed.

**Comment by tut98** [comment]
If you move the trunk's lines towards the center of the car, approximately by the amount of space you can see [here](https://i.imgur.com/3ixaufB.png), you should be fine.

**Comment by Prada420** [comment]
https://imgur.com/a/xSLLEKp but u tried this psd <<<<< before? i send to u couples days ago?

**Comment by tut98** [comment]
No, I have not. I've sent 1 review and I think that's enough.

**Comment by Prada420** [comment]
but you can send the photos to see how it looks

**Comment by tut98** [comment]
No, sorry - https://github.com/saesrpg/donation-vehicle-shaders/issues/169#issuecomment-729288731

**Comment by Prada420** [comment]
so wtf what can i do?

**Comment by Prada420** [comment]
i dont like the car with this lines like this

**Comment by tut98** [comment]
Please take note of the advice I sent above - https://github.com/saesrpg/donation-vehicle-shaders/issues/169#issuecomment-729782910

**Comment by Prada420** [comment]
im fixed the problem already i think but need be test it

**Comment by Prada420** [comment]
but i send u the imagene already bro

**Comment by Prada420** [comment]
just need be test it!

**Comment by tut98** [comment]
> I'm afraid I haven't been able due to temporary network issues.
> 
> I hope you've been able to follow the last review that I sent here. If you'd like I can go ahead and add your wrap at my earliest convenience.



> If you move the trunk's lines towards the center of the car, approximately by the amount of space you can see [here](https://i.imgur.com/3ixaufB.png), you should be fine.

**Comment by Prada420** [comment]
so i can wait i think so

**Comment by Prada420** [comment]
so the problem is u still got problems with your network?

**Comment by tut98** [comment]
Guess who had to lend out their internet adapter. 😩 
Should be back around weekend. Appreciate your patience!

**Comment by Prada420** [comment]
np man

**Comment by tut98** [comment]
604: https://imgur.com/a/rNY14ke

**Comment by Prada420** [comment]
try this one i add some things and fix others  https://imgur.com/a/kRKjgu1

**Comment by tut98** [comment]
It looks OK. Would you like this added or make additional adjustments?

**Comment by Prada420** [comment]
can see some picture plss?

**Comment by tut98** [comment]
No.

**Comment by Prada420** [comment]
why not ? u still got problem with ur internet?

**Comment by Prada420** [comment]
I need to see if I like how it is now!

**Comment by tut98** [comment]
You've received 2 previews. It's not a question of internet at this point, you just have to be realistic about your requests

As a rule of thumb the image are almost identical to how it looks in game.

I've already confirmed that the lines match up in game.

Would you like to make additional adjustments, or have the wrap added as is

**Comment by Prada420** [comment]
aight I wanted to see it with my eyes but if you tell me that the lines match you can add it to the game I hope it's true thanks you!

**Comment by tut98** [comment]
OK - please add username and vehicle ID to your first post.

**Comment by Prada420** [comment]
done

**Comment by tut98** [comment]
Wrap is on its way as `iqprada_2` as of Nov 25 01.43 AM CET
