### ISSUE TITLE
Wrap change

### ISSUE THREAD

**Issue by RicardaPrimis** [saesrpg/donation-vehicle-shaders#17]
Name: BuffaloCIA
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): GirlyPrimis
![BuffaloCIA](https://user-images.githubusercontent.com/53186122/63230359-db3abf80-c20b-11e9-9fd3-3bb087525c60.png)

**Comment by tutgreco** [comment]
are those smudges intended, else please adjust it

**Comment by RicardaPrimis** [comment]
Those white smudges were on the older (black) template too. I didn't change it since it had the name "shading". If you could check if they look bad ingame that would be great

**Comment by tutgreco** [comment]
Nah it looks fine. Btw, the comment I made on https://github.com/saesrpg/donation-vehicle-shaders/issues/18#issuecomment-522473104 applies here too, please look into it

**Comment by RicardaPrimis** [comment]
![BuffaloCIA (2)](https://user-images.githubusercontent.com/53186122/63278778-31f5d700-c2a8-11e9-9517-531bdc4023e4.png)

**Comment by tutgreco** [comment]
i have fixed it, will be live in one of the next server updates

**Comment by tutgreco** [comment]
the wrap is live now, closing this
