### ISSUE TITLE
ZoRo's Custom Wrap

### ISSUE THREAD

**Issue by ZoRo12425** [saesrpg/donation-vehicle-shaders#170]
**Vehicle ID** 
598 / Police LV

**Wrap access**
ZoRo124 (Just Me)

**Needs testing**
Yes Please

**Thread for reward change**
https://saesrpg.uk/topic/22987/zoro-s-reward-change

**Wrap image**
https://i.imgur.com/SNGUVSB.png

**Comment by tut98** [comment]
That's not ID 598. I believe it's ID 402 but please look that up.

**Comment by ZoRo12425** [comment]
Isn't it the Police-LV?

**Comment by tut98** [comment]
Buffalo is 402 and the image you've sent is for 402

**Comment by ZoRo12425** [comment]
Fixed Sir, sry for the mistake

**Comment by tut98** [comment]
402: https://imgur.com/a/U4jgwms

**Comment by ZoRo12425** [comment]
There is a mistake from the designer, It will be fixed soon, Thanks for testing.

**Comment by ZoRo12425** [comment]
Fixed to 598 Police LV, Thx for waiting.

**Comment by tut98** [comment]
Ideally you would submit as 512x512.

A 256x256 will not be readable.

**Comment by ZoRo12425** [comment]
I hope It will get accepted this time, Fixed.

**Comment by tut98** [comment]
The image link needs updating

**Comment by ZoRo12425** [comment]
emm, Like that ?? https://i.imgur.com/Vxe2Z8G.png

**Comment by tut98** [comment]
That's 300x300.

Must be either 256x256 or 512x512, but I would not recommend 256x256 for wraps that has typography on them

**Comment by ZoRo12425** [comment]
done it's 512*512 now: https://i.imgur.com/XmCMcZ3.png

**Comment by tut98** [comment]
598: https://imgur.com/a/TbH2gMl

Please stay within boundaries of the photoshop file that we provide

**Comment by ZoRo12425** [comment]
that's it, sir, https://i.imgur.com/SNGUVSB.png

**Comment by tut98** [comment]
You've received enough reviews, would you like this added or do you need to make additional adjustments first

**Comment by ZoRo12425** [comment]
Add it sir

**Comment by tut98** [comment]
Wrap is on its way as `ZoRo124_1`
