### ISSUE TITLE
Velo's Custom Wrap Request

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#171]
**Vehicle ID** 405

**Wrap access** velona77

**Needs testing** Yes

**Thread for reward change** https://saesrpg.uk/topic/23077/donation-velona-amount-15-00-gbp

**Wrap image**
![sentinel](https://user-images.githubusercontent.com/46403782/100178454-f0110300-2ee4-11eb-936e-b5f54192dca1.png)

**Comment by tut98** [comment]
405: https://imgur.com/a/AkV2TBL

**Comment by Velona77** [comment]
@tut98 Could you test this one as well? If you see the texts on the sides and the photos on the front and back do fit well, you can upload directly
![sentinel](https://user-images.githubusercontent.com/46403782/100354627-7ae72000-3001-11eb-8f8b-79c628ae3adb.png)

**Comment by tut98** [comment]
Wrap is on its way as `velona77_4`
