### ISSUE TITLE
Negan's custom wrap + fixes

### ISSUE THREAD

**Issue by Negan-juuc1498** [saesrpg/donation-vehicle-shaders#174]
**Vehicle ID**
Super GT

**Wrap access**
juuc1498

**Needs testing**
No, thanks

**Thread for reward change**
https://saesrpg.uk/topic/23115/donation-negan1498-amount-30-00-gbp

**Wrap image**
https://i.imgur.com/KAugKT8.png

**Details**
Galatasaray Logo

---
Fix for` juuc1498_1` : 
---
**Needs testing**
No, thanks

**Wrap image**
https://i.imgur.com/cxtW5yr.png

**Fix details**
 * "Turk" cyrillic script black colored
 * Removal of cCc
 * Full white body

**Comment by tut98** [comment]
The ID cannot contain letters, please look up the wiki page for getting Super GT's ID

**Comment by Negan-juuc1498** [comment]
**Model number** :
` 506`
Super GT 
(Shelby GR1)

**Comment by tut98** [comment]
New wrap is on its way as `juuc1498_3` together with the `juuc1498_1` improvement
