### ISSUE TITLE
Velo's Custom Wrap Request #2

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#175]
**Vehicle ID**
506

**Wrap access**
velona77

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/23140/donation-velona-amount-15-00-gbp

**Wrap image**
![CANER 88](https://user-images.githubusercontent.com/46403782/100555560-5a42f280-32ad-11eb-8a6e-cb8be116c98b.png)

**Comment by tut98** [comment]
506: https://imgur.com/a/ARWQE6Y

**Comment by Velona77** [comment]
@tut98 can you test this one too if possible?
![CANER 88](https://user-images.githubusercontent.com/46403782/100582365-31951a00-32fa-11eb-9840-7da5b2daf6ed.png)

**Comment by tut98** [comment]
506: https://imgur.com/a/P11P2Na

**Comment by Velona77** [comment]
The first one seems better, I approve of it (in the main post)

**Comment by tut98** [comment]
OK then. Wrap is on its way as `velona77_5`
