### ISSUE TITLE
BOPE Car

### ISSUE THREAD

**Issue by samuel3021** [saesrpg/donation-vehicle-shaders#176]
**Vehicle ID**

FBI Rancher | 490

**Wrap access**
 
Samuel3021

**Needs testing**

Yes

**Thread for reward change**

**Wrap image**

https://imgur.com/a/zFNtnZ3

**Comment by tut98** [comment]
For wrap access you need to specify at least one username if it is private

For wrap image dimensions you must choose 512x512 or 256x256. 1024x1024 is no longer supported.

**Comment by tut98** [comment]
I do not recommend dimensions of 256x pixels for wraps that use typography. They can not be read.

**Comment by tut98** [comment]
I reckon you've stopped working on it as you've noticed there are other issues than the canvas size.

I'll go ahead and close this as it's been inactive for 8 days.
