### ISSUE TITLE
mrtogna_1

### ISSUE THREAD

**Issue by mrtogna21** [saesrpg/donation-vehicle-shaders#177]
**Vehicle ID**
 482, burrito 

**Wrap access**
 Leave blank if anyone can use the wrap, otherwise state the usernames 

**Needs testing**
 yes 

**Thread for reward change**
 https://saesrpg.uk/topic/23287/donation-mr-togna21-amount-30-00-gbp?_=1607346990654

**Wrap image**
 here it is
![mrtogna_1](https://user-images.githubusercontent.com/75625009/101362252-29ac1b80-38a0-11eb-8ccc-5500663ec3db.png)

**Comment by tut98** [comment]
The wrap does not need testing, would you like to make additional adjustments or have it added?

**Comment by mrtogna21** [comment]
I added a bit of rust. This is the final version, if it is okay you can add it. Thanks!
![mrtogna_1](https://user-images.githubusercontent.com/75625009/101391735-0b0c4b80-38c5-11eb-90e5-49db793a64d6.png)

**Comment by tut98** [comment]
Wrap is on its way as `mrtogna21_1`
