### ISSUE TITLE
Westbrook's wrap request

### ISSUE THREAD

**Issue by Westbrook31** [saesrpg/donation-vehicle-shaders#178]
**Vehicle ID**
604

**Wrap access**
buglemc, molasis

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/23359/donation-westbrook-amount-30-00-gbp

**Wrap image**
![template_glenshit](https://user-images.githubusercontent.com/75691371/101906847-b0c40100-3bca-11eb-848c-4e838fd5df57.png)

**Comment by tut98** [comment]
It shouldn't need testing. Would you like this added or make additional adjustments

**Comment by Westbrook31** [comment]
If you believe texts and images are going to look okey, then sure.

**Comment by tut98** [comment]
Wrap is on its way as `buglemc_1`
