### ISSUE TITLE
Crown vic wrap dyam98_2

### ISSUE THREAD

**Issue by DemienD** [saesrpg/donation-vehicle-shaders#179]
**Vehicle ID**
596

**Wrap access**
dyam98

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/23542/donation-dyam-amount-40-00-gbp

**Wrap image**
![2 (1)](https://user-images.githubusercontent.com/15146566/102715962-e9559000-42d8-11eb-8fa6-6a330f37e828.png)

**Comment by tut98** [comment]
For this and your other request, please specify the usernames and send images as 512x512

**Comment by DemienD** [comment]
@tut98 Image resized and compressed. User access edited.

**Comment by tut98** [comment]
Wrap is on its way as `dyam98_2`
