### ISSUE TITLE
Ricarda Wrap Request

### ISSUE THREAD

**Issue by RicardaPrimis** [saesrpg/donation-vehicle-shaders#18]
#Wrap1
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): GirlyPrimis

Don't know how well the Yellow + Black with the Background will work, would be great if you could test it beforehand
![BuffaloUndercover](https://user-images.githubusercontent.com/53186122/63249954-d527fb80-c26a-11e9-983d-986720b8b7c7.png)

**Comment by tutgreco** [comment]
Can you please move the right side UC1+flag up a little bit to avoid distortion

**Comment by RicardaPrimis** [comment]
![UndercoverBuff](https://user-images.githubusercontent.com/53186122/63278791-3ae6a880-c2a8-11e9-83b1-45b61433671e.png)

**Comment by FilexGH** [comment]
lel fake taxi

**Comment by RicardaPrimis** [comment]
![UndercoverBuff](https://user-images.githubusercontent.com/53186122/63299805-f0305500-c2d6-11e9-8493-3975b4ad4aba.png)

**Comment by tutgreco** [comment]
i have fixed it, will be live in one of the upcoming server updates named ``ricCab``

**Comment by tutgreco** [comment]
the wrap is live now, closing this

**Comment by tutgreco** [comment]
wrap is ruled disallowed as it uses non police material, you're welcome to request another wrap instead. @RicardaPrimis
