### ISSUE TITLE
FBI Rancher wrap dyam98_3

### ISSUE THREAD

**Issue by DemienD** [saesrpg/donation-vehicle-shaders#180]
**Vehicle ID**
490

**Wrap access**
dyam98

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/23542/donation-dyam-amount-40-00-gbp

**Wrap image**
![3 (1)](https://user-images.githubusercontent.com/15146566/102715974-068a5e80-42d9-11eb-8029-1c0d11523e28.png)

**Comment by DemienD** [comment]
@tut98 Image resized and compressed. User access edited.

**Comment by tut98** [comment]
Wrap is on its way as `dyam98_3`
