### ISSUE TITLE
Spanish Custom Wrap 2 

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#181]
**Vehicle ID:** 490 

**Wrap access:** lapd0070, ALIJR007, ferthistheking17

**Needs testing:** Yes

**Thread for reward change:**  https://saesrpg.uk/topic/23736/donation-lapd_spanish_ven-amount-10-00-gbp?_=1609352458241

**Wrap image:** https://i.imgur.com/Fr8KsiN.jpg

**Comment by tut98** [comment]
The wrap looks OK - should not warrant a preview.

Please submit as 512x512. Let us know once you're eligible for this wrap, so that we can upload it

**Comment by LAPDSpanishVEN** [comment]
Wrap updated in: https://i.imgur.com/yuFga3N.png

Additionally, a donation of 10 GBP is made Corresponding to the wrap, link added

**Comment by tut98** [comment]
Wrap is on its way as `lapd0070_2`
