### ISSUE TITLE
Aniki custom wrap for Super GT (thehiddenapple) #1

### ISSUE THREAD

**Issue by TheHiddenApple** [saesrpg/donation-vehicle-shaders#182]
Vehicle ID: 506

Wrap access: thehiddenapple, carl, jaycee2015

Needs testing: Yes

Thread for reward change: https://saesrpg.uk/topic/23750/donation-lonelywolf-amount-40-00-gbp

Wrap image: https://imgur.com/a/l03rRiL

**Comment by tut98** [comment]
https://imgur.com/a/QsRBMYE

**Comment by TheHiddenApple** [comment]
Looks amazing.

**Comment by tut98** [comment]
Wraps on its way as `thehiddenapple_1`
