### ISSUE TITLE
Lmaoborghini custom wrap for Turismo (thehiddenapple) #2

### ISSUE THREAD

**Issue by TheHiddenApple** [saesrpg/donation-vehicle-shaders#183]
Vehicle ID: 451

Wrap access: thehiddenapple

Needs testing: Yes

Thread for reward change: https://saesrpg.uk/topic/23750/donation-lonelywolf-amount-40-00-gbp

Wrap image: https://imgur.com/a/VVA616o

**Comment by tut98** [comment]
Doesn't need testing, looks fine to me

Please submit as 512x512 with opaque background

**Comment by TheHiddenApple** [comment]
Ok i hope this works background should be transparent https://imgur.com/a/DjIJhjW

**Comment by tut98** [comment]
sorry, background must have a fill color

**Comment by TheHiddenApple** [comment]
I don't know how long it will take to solve this problem because apparently i had wrong size templates for this so im gona try to sort it out as soon as possible.

**Comment by TheHiddenApple** [comment]
Remade it in 512x512 https://imgur.com/a/aVhqjYI

**Comment by tut98** [comment]
Wrap is on its way as `thehiddenapple_2`
