### ISSUE TITLE
LV Police wrap

### ISSUE THREAD

**Issue by MToreno** [saesrpg/donation-vehicle-shaders#184]
**Vehicle ID** 598

**Wrap access** SWAT Members

**Needs testing** No

**Thread for reward change** https://saesrpg.uk/topic/23848/donation-toreno-amount-40-00-gbp

**Wrap image**
![rsz_toreno35](https://user-images.githubusercontent.com/46752607/103489246-4ee66800-4e13-11eb-8434-34ff4f240b27.png)

**Comment by tut98** [comment]
Wrap is on its way as `monstercookie12_2`, saved to user `monstercookie12`
