### ISSUE TITLE
Custom Wrap M7mDGr7_1

### ISSUE THREAD

**Issue by M7mDGr7** [saesrpg/donation-vehicle-shaders#185]
**Vehicle ID**
604

**Wrap access**
m7mdgr7

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/23137/donation-m7mdgr7-amount-35-00-gbp

**Wrap image**
https://i.imgur.com/6e2Rd7f.jpg

**Comment by tut98** [comment]
It doesn't have anything that needs lining up or precise details. Wrap looks Ok to me.

Please submit as 512x512.

Please keep usernames lower case.

**Comment by M7mDGr7** [comment]
Done,
Here's the new one: https://i.imgur.com/wdToFMK.jpg

**Comment by tut98** [comment]
Wrap's on its way as `m7mdgr7_1`
