### ISSUE TITLE
Vercetti86 Custom Wrap

### ISSUE THREAD

**Issue by vercetti7** [saesrpg/donation-vehicle-shaders#186]
**Vehicle ID**
451 / Turismo

**Wrap access**
vercetti86

**Needs testing**
yes

**Thread for reward change**
Testing so not yet.

**Wrap image**
https://imgur.com/a/l719woh

**Comment by tut98** [comment]
Wrap looks Ok. Please get rid of the helper lines.

If you're happy with the design we'll add it as is

**Comment by vercetti7** [comment]
![vercetti](https://user-images.githubusercontent.com/77248342/104138386-6b067e00-53ac-11eb-90fe-b9d629f29041.png)

There you go, please add this.

Link to donation: https://saesrpg.uk/topic/24129/donation-vercetti-amount-25-00-gbp

**Comment by tut98** [comment]
Ok, thanks. Please remember to keep them 512x512 not 563x563

Wrap's on its way as `vercetti86_1`
