### ISSUE TITLE
Velo's Wrap Change Request

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#187]
**Vehicle ID**
549

**Wrap access**
velona77

**Needs testing**
Yes

**Thread for reward change**
I will ask for a reward change (Sentinel <> Tampa) if the wrap gets approved.

**Wrap image**
![tampa](https://user-images.githubusercontent.com/46403782/104178794-f79c5500-541b-11eb-9eab-7f7da3bb9e06.png)

**Comment by Velona77** [comment]
I'd like this to be changed with `velona77_4` ,
which you can find here https://github.com/saesrpg/donation-vehicle-shaders/issues/171

**Comment by tut98** [comment]
Sorry I've taken my time - here's a preview
https://imgur.com/a/GK60HxM

**Comment by Velona77** [comment]
This one can be pushed live, thanks in advance.
I'll have my reward change request ready meanwhile.
![tampa](https://user-images.githubusercontent.com/46403782/104445289-0153c300-55aa-11eb-99e3-a7e7b9cfebdd.png)

**Comment by Velona77** [comment]
@tut98 here is the reward change request
https://saesrpg.uk/topic/24272/velo-s-reward-change
