### ISSUE TITLE
Halo's Wrap  Request

### ISSUE THREAD

**Issue by HaloReagan** [saesrpg/donation-vehicle-shaders#188]
**Vehicle ID**

598 

**Wrap access**

**Needs testing**
 Yes ! Please

**Thread for reward change**

https://saesrpg.uk/topic/24166/donation-halo-amount-20-00-gbp?_=1610432278015

**Wrap image**

https://i.imgur.com/4Dp4vkV.png

**Comment by tut98** [comment]
Hi please submit as 512x512 and see if you can resolve the blurry text, to make it readable in lower resolutions

**Comment by HaloReagan** [comment]
Hi.

Fixed and if you need something tell me please

https://i.imgur.com/mnXsnIl.png

**Comment by tut98** [comment]
Looks good. Wrap's on its way as `buch_2`
