### ISSUE TITLE
Wrap car

### ISSUE THREAD

**Issue by samuel3021** [saesrpg/donation-vehicle-shaders#189]
Vehicle ID

490

Wrap access

Needs testing

Yes ! Please
Thread for reward change

https://saesrpg.uk/topic/24069/donation-samuel3021-amount-20-00-gbp?_=1610493256183
https://saesrpg.uk/topic/24100/donation-samuel3021-amount-10-00-gbp?_=1610493256186

Wrap image

https://imgur.com/a/Af8cAlf

**Comment by tut98** [comment]
I'm sorry, emergency vehicle graphics needs to be native to San Andreas / USA. Please pick civilian vehicles if you want to create BOPE wraps.

As a side note, keep images at 512x512 instead of 1024x1024

**Comment by tut98** [comment]
On a second thought that would not work.

Please read the rules for wraps. https://saesrpg.uk/topic/8309/about-donation-wraps
