### ISSUE TITLE
Linkan

### ISSUE THREAD

**Issue by L1nkan** [saesrpg/donation-vehicle-shaders#19]
Check my donate topic for more info thanks

Vehicle ID: 560
Wrap access locked to usernames (leave blank if public):linus111560,swe

[Linkan.zip](https://github.com/saesrpg/donation-vehicle-shaders/files/3517570/Linkan.zip)

**Comment by tutgreco** [comment]
Please post your file as image format not photoshop document

**Comment by L1nkan** [comment]
![Linkan](https://user-images.githubusercontent.com/54290753/63462612-97d69000-c45b-11e9-9010-0f5e12972211.png)

**Comment by tutgreco** [comment]
Wrap `elkCar` will be added in one of the upcoming server updates

**Comment by L1nkan** [comment]
Hi. its now live and added to my sultan. But all the text is rototed and shit so when time is possible please change it to this one! As you can see on this screen both "Sweman and Linkan is fucked up(rotated)" and the flag is also fucked same goes with Elk Mobile. 
![mta-screen_2019-08-29_17-34-17](https://user-images.githubusercontent.com/54290753/63954349-40e84080-ca83-11e9-8126-acda93178343.png)

 
Please check if the Ikea Logo wont be rotated ingame as i placed it so it should be rotated to its exact posistion ingame.

![Linkan](https://user-images.githubusercontent.com/54290753/63954309-32018e00-ca83-11e9-91e0-c31a72d88fea.png)

So i guess the new update should fix the most problems with it also i removed nicknames and added ikea haha!
