### ISSUE TITLE
Spanish Custom Wrap 3

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#190]
**Vehicle ID:** 416

**Wrap access:** lapd0070, johnnyenglish

**Needs testing:** Yes

**Thread for reward change:** There is no corresponding donation with the wrap, I hope to make you before the end of the month

**Wrap image:** https://imgur.com/a/nwfXutv

**Comment by tut98** [comment]
Looks good, would you like this added?

Please let us know once you're eligible for this donation reward (by having donation credits available)

**Comment by LAPDSpanishVEN** [comment]
Donation link updated at: https://saesrpg.uk/topic/24333/donation-lapd_spanish_ven-amount-9-00-gbp?_=1611029750965

**Comment by tut98** [comment]
Wraps on its way as `lapd0070_3`
