### ISSUE TITLE
Nishki's Custom wraps

### ISSUE THREAD

**Issue by Nishki** [saesrpg/donation-vehicle-shaders#191]
**Vehicle ID**
Vehicle ID: 406, 494
**Wrap access**
bluelive122

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/24165/nishki-s-reward-change

**Wrap image**

https://cdn.discordapp.com/attachments/720386650047512606/799677792391266365/template_glenshit-Recovered-Recovered.png
https://cdn.discordapp.com/attachments/720386650047512606/799277525741338694/image0.png

**Comment by tut98** [comment]
Green is on its way as `bluelive122_1`
Yellow is on its way as `bluelive122_2`
