### ISSUE TITLE
Element's custom wrap

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#192]
**Vehicle ID**
598 Police LV (GTA5)

**Wrap access**
denis10, specialist12, bendrin12

**Needs testing**
Yes, please.

**Thread for reward change**
https://saesrpg.uk/topic/24126/donation-dudi-amount-10-00-gbp

**Wrap image**

https://imgur.com/NRcKoVW

**Comment by tut98** [comment]
Please submit as 512x512

**Comment by TheRealElement** [comment]
Updated the link with a fixed size of the wrap.

**Comment by tut98** [comment]
https://imgur.com/a/92lv0kf

**Comment by TheRealElement** [comment]
Here's a fix (hopefully), needs testing, please.

https://i.imgur.com/AhC6xlr.png

Thanks in advance!

**Comment by tut98** [comment]
If you follow the guide layers in the photoshop file, and reference the screenshots above, it should not need testing. I've compared the 2 images and it looks like you did follow the vehicle sides guides.

**Comment by TheRealElement** [comment]
Yeah, but you never know what pops up when it comes to wraps, however, if you think from your perspective that the wrap is fine I guess that we can proceed to the next stage.

**Comment by tut98** [comment]
Wrap's on its way as `denis10_10`
