### ISSUE TITLE
Halo´s Custom Wrap

### ISSUE THREAD

**Issue by Rocoso15** [saesrpg/donation-vehicle-shaders#193]
**Vehicle ID**
451
**Wrap access**
buch

**Needs testing**
Yes please
**Thread for reward change**
https://saesrpg.uk/topic/24286/donation-halo-amount-20-00-gbp

**Wrap image**
![Halo](https://user-images.githubusercontent.com/67118949/105636407-4d1e2c00-5e36-11eb-92cf-aa528e90567c.png)

**Comment by tut98** [comment]
> [Note] I upload the halo wrap from my account as he asked me to do it, he is having problems with his github account so I do it for him

Ok, that's fine. Please follow **Wrap image**'s comment and do not use the helper lines in final export

**Comment by Rocoso15** [comment]
https://i.imgur.com/EQfdHjw.png

Fixed

**Comment by tut98** [comment]
Please see the Wrap Image comment :)
> Attach the file here, do not use 3rd party image hosts. File extension must be .PNG using 512x512 or 256x256 dimensions

**Comment by Rocoso15** [comment]
https://media.discordapp.net/attachments/794363820922896411/801558164050673694/image0.png?width=468&height=468
:)

**Comment by Rocoso15** [comment]
@tut98 I think it would be all right now, I'm sorry  :c

**Comment by tut98** [comment]
It's only 468x468, needs to be 512x512 or 256x256.
Please use the image file attach feature next up - we do not want 3rd party hosted images!

Wrap looks like you'd expect

**Comment by Rocoso15** [comment]
@tut98  Done sir

**Comment by tut98** [comment]
Wrap's on its way as `buch_3`
