### ISSUE TITLE
Curny's Custom Wrap

### ISSUE THREAD

**Issue by Curny1212** [saesrpg/donation-vehicle-shaders#194]
**Vehicle ID**
402

**Wrap access**
freezz , elegant09
**Needs testing**
Yes.

**Thread for reward change**
https://saesrpg.uk/topic/24399/donation-curny-amount-10-00-gbp

**Wrap image**
https://i.imgur.com/mb2faEc.jpg

**Comment by tut98** [comment]
Wrap looks good to me. Shouldn't need testing.

**Comment by Curny1212** [comment]
Great! shall we proceed?

**Comment by tut98** [comment]
Wrap's on its way as `freezz_1`
