### ISSUE TITLE
Elegant's Custom Wrap

### ISSUE THREAD

**Issue by Elegant09** [saesrpg/donation-vehicle-shaders#195]
**Vehicle ID**
402 - Buffalo

**Wrap access**
elegant09, freezz

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/24387/donation-elegant-amount-40-00-gbp

**Wrap image**
https://i.imgur.com/mPh4Rcf.png

**Comment by tut98** [comment]
Wrap looks fine to me, shouldn't need testing.

**Comment by Elegant09** [comment]
Okay perfect, we can proceed to the next stage I assume?

**Comment by tut98** [comment]
Wrap's on its way as `elegant09_1`
