### ISSUE TITLE
Rocoso's Custom Wrap

### ISSUE THREAD

**Issue by Rocoso15** [saesrpg/donation-vehicle-shaders#196]
**Vehicle ID**
598

**Wrap access**
Understaked015 / SAFP Members
**Needs testing**
Yes Please

**Thread for reward change**
https://saesrpg.uk/topic/24470/donation-rocoso-amount-15-00-gbp

**Wrap image**
![Wrap Rocoso](https://user-images.githubusercontent.com/67118949/105720871-ef4f1a00-5ef1-11eb-9e17-10e464b8c954.png)

**Comment by tut98** [comment]
Wrap is looking Ok - the rear bumper text should be readable if you shrink its length by 10 - 15%. The guide layer will prove helpful. 

Don't see any need for testing this. Please edit your thread with a 512x512 image and we'll add it, unless you'd like to make further adjustments.

**Comment by Rocoso15** [comment]
@tut98  All done :)

**Comment by tut98** [comment]
Wraps on its way as `understaked015_5`
