### ISSUE TITLE
Pular's Custom Wrap

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/donation-vehicle-shaders#197]
**Vehicle ID**
482

**Wrap access**
 (kmkm567)

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/24056/pular-s-reward-change

**Wrap image**

![template_Buritto](https://user-images.githubusercontent.com/49839598/105704643-2a684200-5f20-11eb-8a24-73e87be24037.png)

**Comment by tut98** [comment]
Please attach file here, do not use 3rd party sites as advised in the template comment

**Comment by laggiaze** [comment]
**Wrap image**
![template_Buritto](https://user-images.githubusercontent.com/49839598/105704643-2a684200-5f20-11eb-8a24-73e87be24037.png)

**Comment by tut98** [comment]
Wrap's on its way as `kmkm567_1`
