### ISSUE TITLE
Killerask Custom Wrap

### ISSUE THREAD

**Issue by Killerask** [saesrpg/donation-vehicle-shaders#198]
Vehicle ID
482

Wrap access
killerask getskillz

Needs testing
 No

Thread for reward change
https://saesrpg.uk/topic/24526/killerask-reward-change

Translations
N/A

Wrap image https://i.imgur.com/mjtz3EQ.png

**Comment by tut98** [comment]
Wrap's on its way as `killerask_1` - please remember to use github host for images as asked in template
