### ISSUE TITLE
Nik0's custom wrap

### ISSUE THREAD

**Issue by f0ther** [saesrpg/donation-vehicle-shaders#199]
**Vehicle ID**: 451

**Wrap access**: fother

**Needs testing**: Yes

**Thread for reward change**: https://saesrpg.uk/topic/24555/donation-nik0-amount-5-00-gbp/2

**Translations**: "El pepe" is an artist in my country and "mamaguevo" is a normal dominican word which means "dicksucker" in english. 

**Wrap image**:
![512x512](https://user-images.githubusercontent.com/78181614/106319721-40d80b80-6248-11eb-9ad5-748d32529a29.png)

**Comment by tut98** [comment]
Please submit as 512x512. Don't see much need for a pics, looks like the graphics are within their boundaries

**Comment by f0ther** [comment]
**Wrap image:**
![512x512](https://user-images.githubusercontent.com/78181614/106319255-8c3dea00-6247-11eb-90af-8400618d79aa.png)

**Comment by tut98** [comment]
Wrap's on its way as `fother_1`
