### ISSUE TITLE
Vennelle's shader request

### ISSUE THREAD

**Issue by Vennelle** [saesrpg/donation-vehicle-shaders#20]
I would like to request a custom shader for my police LV car located at LVPD (the exact one will be apointed in game)

![ETF shader (1)](https://user-images.githubusercontent.com/53538689/63650244-cea4f280-c748-11e9-816c-4bc12b6f2ef3.png)

**Comment by tutgreco** [comment]
please use the correct format for requests found below
https://github.com/saesrpg/donation-vehicle-shaders/issues/1

**Comment by Vennelle** [comment]
For Custom wrap request :
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): mrredbull, AntiRug

**Comment by tutgreco** [comment]
Wrap `etfBomb` will be added in one of the next server updates
