### ISSUE TITLE
Nulgath custom wrap

### ISSUE THREAD

**Issue by saes-nulgath** [saesrpg/donation-vehicle-shaders#200]
**Vehicle ID**
604

**Wrap access**
throng0

**Needs testing**
yes please

**Thread for reward change**
https://saesrpg.uk/topic/24614/nulgath-sreward-change

**Translations**
Red logo is tunisia flag.

**Wrap image**
![template_glenshit (2)](https://user-images.githubusercontent.com/78265940/106369263-2c7f3600-6350-11eb-96ce-73e03b4ab516.png)

**Comment by tut98** [comment]
Please upload straight to github, do not use 3rd party sites
Please add translations for the red logo
For your friend to get unbanned please use the appropriate ban appeal section, not needed to go on a wrap

**Comment by saes-nulgath** [comment]
@tut98 done

**Comment by tut98** [comment]
Thanks. Shrink the hood's graphics a little, avoid keeping them close to their boundaries and it will be good to go

**Comment by saes-nulgath** [comment]
i think it's done now @tut98 
![template_glenshit](https://user-images.githubusercontent.com/78265940/106383532-f0d38300-63c6-11eb-8f5f-eb4ef260a665.png)

**Comment by tut98** [comment]
Hood = bonnet, not roof

**Comment by saes-nulgath** [comment]
@tut98 i think it's done now :) 
![template_glenshit](https://user-images.githubusercontent.com/78265940/106448250-cf37d180-6482-11eb-84fb-1ec6f1cfc1f4.png)

**Comment by tut98** [comment]
Wrap's on its way as `throng0_1`
