### ISSUE TITLE
Steven's Custom Wrap

### ISSUE THREAD

**Issue by steven517** [saesrpg/donation-vehicle-shaders#201]
**Vehicle ID**
597

**Wrap access**
anyone

**Needs testing**
yes

**Thread for reward change**
just need this tested for now

**Translations**
n/a

**Wrap image**

![fbisultan](https://user-images.githubusercontent.com/67033453/106376846-1b392800-6356-11eb-970e-66710ea96627.png)

**Comment by tut98** [comment]
Things tend to stretch a little with Sultan so beware of that
https://imgur.com/a/duRCRax

**Comment by steven517** [comment]
try this one 
![fbisultanv2](https://user-images.githubusercontent.com/67033453/106685745-45712c80-6586-11eb-90a3-9c9b9eb92062.png)

**Comment by tut98** [comment]
I've taken the template down for maintenance to resolve the stretching. Should be back up in around 4 hours.

**Comment by steven517** [comment]
Sure, no problem take your time

Are you going to make a new template or do I still use this one?

**Comment by tut98** [comment]
Every bit is the same, just slightly different scale. I'll keep you updated on when the new one is out

**Comment by tut98** [comment]
updated at https://saesrpg.uk/topic/8309/about-donation-wraps doesn't need tests

**Comment by steven517** [comment]
![FBIpolicesultan](https://user-images.githubusercontent.com/67033453/106987497-d5e87200-672a-11eb-8df7-e6a32895bf52.png)

**Comment by tut98** [comment]
Wrap's on its way as `st3v3n517_2`
Added guide layer to psd, can download from above link
