### ISSUE TITLE
Bart's custom wrap replace

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#202]
**Vehicle ID**
598

**Wrap access**
-

**Needs testing**
Yes.

**Thread for reward change**
I'd like to change this wrap with the current bardo45_2
https://saesrpg.uk/topic/24625/bart-s-reward-change

**Translations**
It's English.

**Wrap image**
![KMARLV](https://user-images.githubusercontent.com/61796491/106620413-d4c01500-6571-11eb-87a9-b9e3e1681638.png)

Please re-write this one (replace it) with bardo45_2. (Should be the Burrito one)

**Comment by tut98** [comment]
Please use the correct template and upload image to github

**Comment by bardo45** [comment]
Updated.

**Comment by tut98** [comment]
You can get the up to date template from here: https://saesrpg.uk/topic/8309/about-donation-wraps
Please save as 512x512 which is the new limit

**Comment by bardo45** [comment]
I followed the link on that topic which send me to the github page which says, press new issue, which is what I did?

**Comment by tut98** [comment]
Sorry I'm talking about image template, the one you've got is obsolete

**Comment by bardo45** [comment]
Aha gotcha, it's updated @tut98

**Comment by tut98** [comment]
It does not need testing, but please consider removing the white fringe at the top of the image

**Comment by tut98** [comment]
Sorry, Dutch police shouldn't patrol SA
https://upload.wikimedia.org/wikipedia/commons/6/65/Dutch_police_car_02.JPG
