### ISSUE TITLE
Stay's Custom Wrap.

### ISSUE THREAD

**Issue by stayA9** [saesrpg/donation-vehicle-shaders#203]
Vehicle ID: 560

Wrap access: stayalive7

Needs testing: No

Thread for reward change: https://saesrpg.uk/topic/24647/stay-s-reward-change

Translations: "El Jefe" means the boss, Jans off standing for Hands off, Maduro is a public figure.

Wrap image:
![template](https://user-images.githubusercontent.com/46969491/106461487-38abe600-646b-11eb-9b76-36816a0035b0.png)

**Comment by tut98** [comment]
Wrap's on its way as `stayalive7_1`
