### ISSUE TITLE
Bart's new custom wrap

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#204]
**Vehicle ID**
598

**Wrap access**
-

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/24625/bart-s-reward-change
Already archived so can't edit it but 2nd Dodge LV must be bardo45_3 

**Translations**
Reddingsbrigade => Rescue Brigade

**Wrap image**

![PoliceREDDINGLV](https://user-images.githubusercontent.com/61796491/106623542-04245100-6575-11eb-9e05-3cafd0e66e29.png)

Please save it as bardo45_3

**Comment by tut98** [comment]
Emergency wraps must be English. Either way I think orange police cars is a little off.
