### ISSUE TITLE
steddie custom wrap

### ISSUE THREAD

**Issue by Steddieeddie** [saesrpg/donation-vehicle-shaders#205]
**Vehicle ID**
598

**Wrap access**
bardo45

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/24626/steddie-reward-change

**Translations**

**Wrap image**
![PolicePOLITIELV](https://user-images.githubusercontent.com/78441036/106646393-fb8c4480-658d-11eb-8588-4c41516728b6.png)

**Comment by tut98** [comment]
Sorry, Dutch police shouldn't patrol SA
https://upload.wikimedia.org/wikipedia/commons/6/65/Dutch_police_car_02.JPG
