### ISSUE TITLE
Bart's custom wrap replace (bardo45_2)

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#206]
**Vehicle ID**
598

**Wrap access**
-

**Needs testing**
No

**Thread for reward change**
I'd like to change this wrap with the current bardo45_2
https://saesrpg.uk/topic/24625/bart-s-reward-change

**Translations**
it's in perfect English.

**Wrap image**
![PoliceKMARLV](https://user-images.githubusercontent.com/61796491/107025664-07545280-67aa-11eb-9880-07d07604b67f.png)

**Comment by bardo45** [comment]
@tut98  It's updated
Also, got permissions from @SAESKain to use this.

**Comment by tut98** [comment]
Thanks, I'll upload soon as I hear confirmation

**Comment by bardo45** [comment]
@tut98  Thanks, I uploaded a new PNG to fix the white lining from the upper part.

**Comment by tut98** [comment]
Wrap's on its way
