### ISSUE TITLE
RiseAgain's Custom Wrap

### ISSUE THREAD

**Issue by r1seaga1n** [saesrpg/donation-vehicle-shaders#207]
**Vehicle ID**
560

**Wrap access**
riseagain

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/24704/donation-riseagain-amount-30-00-gbp

**Wrap image**
![sultan_baked](https://user-images.githubusercontent.com/78505180/106813683-00c6bd80-667a-11eb-9fe1-d27c1d3d6edb.png)

**Comment by tut98** [comment]
Wrap's on its way as `riseagain_1`
