### ISSUE TITLE
steddie custom wrap

### ISSUE THREAD

**Issue by Steddieeddie** [saesrpg/donation-vehicle-shaders#208]
**Vehicle ID**
598

**Wrap access**
steddieeddie & bardo45

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/24626/steddie-reward-change

**Translations**
Kain gave us permission to use this

**Wrap image**

![PolicePOLITIELV](https://user-images.githubusercontent.com/78441036/107024601-88124f00-67a8-11eb-8a51-7d63cd8cab7b.png)

**Comment by tut98** [comment]
Wrap looks good to me. If you don't want to make additional adjustments, I can have it uploaded soon

**Comment by Steddieeddie** [comment]
Alright, good to go!

**Comment by tut98** [comment]
Wrap's on its way as `steddieeddie_1`
