### ISSUE TITLE
Duff's Fenerbahce Wrap

### ISSUE THREAD

**Issue by Duffy1907** [saesrpg/donation-vehicle-shaders#209]
Vehicle ID
604- Damaged Glendale

Wrap Access 
fener1907

Needs Testing 
No

Donation Link : https://saesrpg.uk/topic/24700/donation-duff-amount-10-00-gbp

Wrap Link

https://i.imgur.com/AQSPUVfh.jpg

**Comment by tut98** [comment]
Please add translations, upload as 512x512 straight to github

**Comment by Duffy1907** [comment]
![Kus_arabas1](https://user-images.githubusercontent.com/46969530/107154356-98325600-6983-11eb-8eaf-3bae467dabe1.jpg)

**Comment by tut98** [comment]
Wrap's on its way as `fener1907_1`

**Comment by Latinoo** [comment]
.
