### ISSUE TITLE
ZeKing wrap request

### ISSUE THREAD

**Issue by zekingsaes** [saesrpg/donation-vehicle-shaders#21]
Hello sir,
Here my request, thank you for your time.
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): zeking,tut
Name for wrap (e.g tutPD): zekingPD
https://media.discordapp.net/attachments/530024137109012500/615298005662302240/template2.png?width=668&height=668

Hello sir, here the new version of my Wrap :

https://cdn.discordapp.com/attachments/530024137109012500/615895517645242369/template4.png with bug fixed

**Comment by tutgreco** [comment]
Wrap will be added in one of the upcoming server updates
