### ISSUE TITLE
Dizzy's Custom Wrap

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/donation-vehicle-shaders#211]
**Vehicle ID**
519

**Wrap access**
leeys

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/24890/donation-dizzy-amount-10-00-gbp/3?_=1613088194918

**Wrap image**
![Shamalbody256](https://user-images.githubusercontent.com/49839598/107715065-8502eb80-6cdf-11eb-84d2-bf1b4cc77f81.jpg)

**Comment by tut98** [comment]
Wrap's on its way as `leeys_1`

Please submit further wraps as 512x512, 500x500 are not accepted image dimensions
