### ISSUE TITLE
Element's wrap

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#213]
**Vehicle ID**
490 FBI Rancher (Chevy Tahoe)

**Wrap access**
denis10

**Needs testing**
Yes, please.

**Thread for reward change**
https://saesrpg.uk/topic/25023/donation-element-amount-60-00-gbp

**Wrap image**
https://imgur.com/a/aIhiTnM

**Comment by tut98** [comment]
Looks fine

**Comment by TheRealElement** [comment]
Sounds good, well I guess we can move on to the next stage.

**Comment by tut98** [comment]
Wrap's on its way as `denis10_11`
