### ISSUE TITLE
Albanian skin

### ISSUE THREAD

**Issue by CaPu09** [saesrpg/donation-vehicle-shaders#214]
**Vehicle ID**

Damaged Glendale
**Wrap access**
 pocoloco anxhelo00
**Needs testing**

maybe
**Thread for reward change**

https://saesrpg.uk/topic/24990/donation-thedarkcapu-amount-5-00-gbp?_=1613590729692
https://saesrpg.uk/topic/25055/donation-thedarkcapu-amount-5-00-gbp?_=1613590729695
**Translations**

**Wrap image**

![CapuSkin](https://user-images.githubusercontent.com/79224365/108258584-7a71a780-7160-11eb-8a6a-bebc13fa8bad.png)

**Comment by tut98** [comment]
Please submit as 512x512. Who/what does the figures and logos represent?

**Comment by CaPu09** [comment]
it is Albanian flag and the date Albanian become a state
what about 512x512

**Comment by CaPu09** [comment]
did it got accepted

**Comment by tut98** [comment]
It's pending upload.

**Comment by tut98** [comment]
Wrap's on its way as `pocoloco_1` - if `pocoloco` is not the owner's name, please correct me!

**Comment by CaPu09** [comment]
username pocoloco name [MMC]CaPu
