### ISSUE TITLE
Getskillz costum wrap

### ISSUE THREAD

**Issue by Getskillz** [saesrpg/donation-vehicle-shaders#216]
**Vehicle ID**

482
**Wrap access**

Getskillz
**Needs testing**
yes
**Thread for reward change**
tomorrow will  donate GBP
**Translations**

N/A
**Wrap image**
 
![rsz_template_buritto](https://user-images.githubusercontent.com/79378867/108606985-e735ad80-73bd-11eb-9d52-d0eab95f4397.jpg)

**Comment by tut98** [comment]
It won't need tests

**Comment by tut98** [comment]
Wrap's on its way as `getskillz_1`
