### ISSUE TITLE
Daniel's custom wrap 

### ISSUE THREAD

**Issue by 3Bo0** [saesrpg/donation-vehicle-shaders#217]
**Vehicle ID**
598

**Wrap access**
3bo010 and xxmrtrollstylexx and xtmx
**Needs testing**
Yes and please test all sides
**Thread for reward change**
https://saesrpg.uk/topic/19608/donation-daniel-%D0%B2%D0%B8%D1%81%D0%B5%D0%BB%D0%B8%D1%86%D0%B0-3970-amount-20-00-gbp In fact: I had an old wrap on a donation car but because I was inactive for a long time the system removed it.
**Translations**

**Wrap image**
https://i.imgur.com/OS8XilT.png
![MIT1877](https://user-images.githubusercontent.com/67001169/108700791-2f68e300-7518-11eb-92da-e8c8e04a19b7.png)

**Comment by tut98** [comment]
This does not need testing. However, removing shadow layer would be a good idea as it will create artifacts.

Please upload as 512x512

**Comment by 3Bo0** [comment]
I hope you can test it so I can know if is in there anything wrong with the design, also what do you mean by shadow layer?
![MIT187](https://user-images.githubusercontent.com/67001169/108826906-00b14200-75d6-11eb-9612-570977877c09.png)

**Comment by tut98** [comment]
It will look fine if you followed the guides in the photoshop file.

Shadows will create artifacts - I recommend only using them as reference.

**Comment by 3Bo0** [comment]
Can you tell me where are the Shadow Layers exactly? because I didn't use any shadow effects on this design?

**Comment by tut98** [comment]
They are visible on the bumpers, door handles and the the space between your front doors and front axles.

It's a helper layer that comes with the photoshop file.

**Comment by 3Bo0** [comment]
Done.
![MIT-187](https://user-images.githubusercontent.com/67001169/108912867-43a50100-763a-11eb-923f-0cdc3d73ab0b.png)

**Comment by 3Bo0** [comment]
So is it accepted?

**Comment by tut98** [comment]
Pending upload.

**Comment by tut98** [comment]
Wrap's on its way as `3bo010_2`

**Comment by 3Bo0** [comment]
When it will be uploaded?

**Comment by tut98** [comment]
Needs a resource restart. Probably soon.

**Comment by 3Bo0** [comment]
This is the final wrap **IF** you test it in-game and it was fine.

![تيري ميري](https://user-images.githubusercontent.com/67001169/111094134-9e4fbf80-854b-11eb-8ecb-523c55e504b2.png)
