### ISSUE TITLE
Fugitive's custom donation wrap

### ISSUE THREAD

**Issue by FugiTheGoat** [saesrpg/donation-vehicle-shaders#22]
Hi there

https://media.discordapp.net/attachments/287226271539396608/618808097473036289/template3.png?width=568&height=568

This is my custom donation wrap on the template for G-Wagon

**Comment by tutgreco** [comment]
Adding this one instead as your linked wrap apparently is smaller than it should be
https://media.discordapp.net/attachments/287226271539396608/618846696624881674/template3.png

**Comment by FugiTheGoat** [comment]
Vehicle ID: 400
Wrap access locked to usernames (leave blank if public): fugitive9811, arcticbear
Name for wrap (e.g tutPD): MitroGOD
