### ISSUE TITLE
Strong's custom wrap request

### ISSUE THREAD

**Issue by Strong614** [saesrpg/donation-vehicle-shaders#221]
**Vehicle ID**
400

**Wrap access**
mas3ouda

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/25372/donation-strong-amount-20-00-gbp

**Translations**
It's all in English

**Wrap image**
![Stong1](https://user-images.githubusercontent.com/71896134/109405249-b41b8d00-796e-11eb-89e7-ec822512c6ef.png)

**Comment by tut98** [comment]
Wrap's on its way as `mas3ouda_1`
