### ISSUE TITLE
Elek Custom wrap

### ISSUE THREAD

**Issue by Elektrik335** [saesrpg/donation-vehicle-shaders#222]
**Vehicle ID**
604

**Wrap access**
dominik1234

**Needs testing**
yes please

**Thread for reward change**
https://saesrpg.uk/topic/25378/donation-elet-amount-5-00-gbp
https://saesrpg.uk/topic/24977/donation-elet-amount-15-00-gbp

**Translations**
N/A

**Wrap image**
![elek (1)](https://user-images.githubusercontent.com/79796158/109422294-3cd01280-79db-11eb-9bef-e7d3afbc2245.png)

**Comment by tut98** [comment]
The wrap will look fine.

**Comment by Elektrik335** [comment]
We can move on the next stage then

**Comment by tut98** [comment]
Wrap's on its way as `dominik1234_1`
