### ISSUE TITLE
Maksim's custom wrap

### ISSUE THREAD

**Issue by Blazzers** [saesrpg/donation-vehicle-shaders#223]
Vehicle ID*
506 Super GT

Wrap access
cnegovik

Needs testing
Yes

Thread for reward change
https://saesrpg.uk/topic/25420/maksim-s-reward-change

Photo 
https://imgur.com/gallery/2GYcjMi

**Comment by tut98** [comment]
Please embed the image here by uploading to github, include translations

**Comment by Blazzers** [comment]
![image](https://user-images.githubusercontent.com/69090078/109569833-1e146d80-7afa-11eb-8588-8dde7069640e.png)

**Comment by tut98** [comment]
https://imgur.com/a/OPABRkl
Try to change the background color to white, and where the wrap is red and blue, paint the background red and blue too.

**Comment by Blazzers** [comment]
![image](https://user-images.githubusercontent.com/69090078/109798602-05a47000-7c2c-11eb-880e-92f8bfc9213d.png)

That's true?

**Comment by tut98** [comment]
Wrap's on its way as `cnegovik_1`

**Comment by Blazzers** [comment]
A test ?

**Comment by tut98** [comment]
Doesn't need any more tests, use the last one as reference.

Is the wrap not ready to go?

**Comment by Blazzers** [comment]
I don't   saw it in SF wrap checker

**Comment by tut98** [comment]
The wrap is not on the server yet - it's on its way. The thread will be closed once it's uploaded 🙂

**Comment by Blazzers** [comment]
how long will it take?😅
