### ISSUE TITLE
WenDo's Generic Wrap

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/donation-vehicle-shaders#224]
**wendos-bank**

Hey there, this is a Shamal wrap.

![shamal](https://user-images.githubusercontent.com/60403881/110165323-118e5e80-7df3-11eb-8708-04eaff00f680.png)

**Comment by tut98** [comment]
> **wendos-bank**
> 
> Hey there, this is a Shamal wrap.

This can be added as a generic wrap as it follows a pattern.

If  you want this as a custom please use the correct template.

**Comment by WenDo21** [comment]
Add it as generic habibi

**Comment by tut98** [comment]
Wrap's on its way as `dollars`
