### ISSUE TITLE
juanes12 Custom Wrap

### ISSUE THREAD

**Issue by Juanes12a** [saesrpg/donation-vehicle-shaders#225]
Vehicle ID:: 402 (Buffalo)

Wrap access:: Juanes12

Needs testing:: Yes

Thread for reward change:: https://saesrpg.uk/topic/25628/donation-juanes12-amount-20-00-gbp/1

Traslations: N/A

Wrap Image: ![buffalo](https://user-images.githubusercontent.com/56209707/110215612-84e2af80-7e89-11eb-9677-87ac1477735d.png)

**Comment by tut98** [comment]
The wrap does not look like it needs testing - should look fine.

**Comment by Juanes12a** [comment]
> The wrap does not look like it needs testing - should look fine.

Alright then can be added

**Comment by tut98** [comment]
For your information, this is a custom wrap, not a generic wrap.

Generic wraps are images that follow a pattern or aren't specific to just one vehicle, such as camoflage.
Custom wraps are images that follows a template.

**Comment by Juanes12a** [comment]
> For your information, this is a custom wrap, not a generic wrap.
> 
> Generic wraps are images that follow a pattern or aren't specific to just one vehicle, such as camoflage.
> Custom wraps are images that follows a template.

"Alright upload it anyway"

**Comment by tut98** [comment]
Wrap's on its way as `juanes12_1`
