### ISSUE TITLE
Orten Custom Wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#226]
Posting this on behalf of Orten:

**Vehicle ID**
604

**Wrap access**
moemen12

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/25631/orten-s-reward-change

**Translations**
N/A

**Wrap image**

![template_glenshit](https://user-images.githubusercontent.com/60038193/110238455-fda54280-7f41-11eb-945d-b4b72b8ffb4d.jpg)

**Comment by tut98** [comment]
Looks fine, if you don't need additional adjustments we can go with this.

**Comment by Liyones** [comment]
Yeah sure , as you wish ,  but i wanna see how it look ingame if you don't mind , and if you're busy or not free we can move on and add it.

**Comment by tut98** [comment]
There is a small number of vehicles OR types of wraps i.e graphics that needs to line up, that may need testing.

Your image represents how it will look ingame so there is no need for a test.
Pending upload-

**Comment by Liyones** [comment]
Alright all cool , we can add it! thx :)

**Comment by tut98** [comment]
Wrap's on its way as `moemen12_1`
