### ISSUE TITLE
Real Costum Wrap

### ISSUE THREAD

**Issue by Turealpro11** [saesrpg/donation-vehicle-shaders#227]
**Vehicle ID**

598
**Wrap access**

turealpro11
**Needs testing**

Yes
**Thread for reward change**

https://saesrpg.uk/topic/25664/rewar-change-real
**Translations**

in the left and right sides (National Police)
in the roof of the car (as i know it's the same english > esp)
**Wrap image**

![LVPOLICEreal](https://user-images.githubusercontent.com/71466439/110518499-748e3700-810c-11eb-86ab-35d8805f5cea.png)

**Comment by tut98** [comment]
Keep text English. No need for a test.

**Comment by Turealpro11** [comment]
Edited @tut98

**Comment by tut98** [comment]
> I want to see how it looks to see if you need to fix something, I don't know why I want you to try it, try it please

Ok.

**Comment by tut98** [comment]
https://imgur.com/a/5jhxO3f

**Comment by Turealpro11** [comment]
Hi @tut98 i've edited the text and thanks for testing it, can u tell me if the text is good now ?

**Comment by tut98** [comment]
Use the images for reference

**Comment by Turealpro11** [comment]
> Use the images for reference

ik that, just in ur opinion is it good ?

**Comment by Turealpro11** [comment]
hello @tut98 i changed my mind and i'll change the car if u don't mind, ii'll send u the wrap asap, hope u don't mind

**Comment by tut98** [comment]
Please make a new issue
