### ISSUE TITLE
WenDo's Custom Wrap

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/donation-vehicle-shaders#228]
**Vehicle ID**
519

**Wrap access**
trymebitch

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/25706/wendo-s-reward-change

**Translations**
n/a

**Wrap image**
![shamal_roses](https://user-images.githubusercontent.com/60403881/110697808-20a74f00-81ed-11eb-83a3-8813101a7270.png)

**Comment by tut98** [comment]
Wrap's on its way as `trymebitch_1`
