### ISSUE TITLE
Real costum wrap

### ISSUE THREAD

**Issue by Turealpro11** [saesrpg/donation-vehicle-shaders#229]
**Vehicle ID**

451
**Wrap access**

turealpro11
**Needs testing**

yes if u don't mind
**Thread for reward change**

https://saesrpg.uk/topic/25664/rewar-change-real
**Translations**

N/A
**Wrap image**

![Lamborghini](https://user-images.githubusercontent.com/71466439/110711088-3cb3ec00-81ff-11eb-9ad6-089203b0c378.png)

**Comment by tut98** [comment]
The long white item below the roof in the image, is the step below the doors and will be white. If this is not intended, please color it red or green to match the overall design.
Other than that I see no reason for a preview from my side.

**Comment by Turealpro11** [comment]
> The long white item below the roof in the image, is the step below the doors and will be white. If this is not intended, please color it red or green to match the overall design.
> Other than that I see no reason for a preview from my side.

**Comment by Turealpro11** [comment]
> The long white item below the roof in the image, is the step below the doors and will be white. If this is not intended, please color it red or green to match the overall design.
> Other than that I see no reason for a preview from my side.

hello thanks for ur note, i'll fix it right now and send it for u,

**Comment by Turealpro11** [comment]
@tut98 i've closed this request mistakly is it possible to open it again or ?

**Comment by Turealpro11** [comment]
@tut98 Hi there i've fixed the wrap as u told me, thx again 
![Lamborghini](https://user-images.githubusercontent.com/71466439/110759287-ba9ee400-824d-11eb-82e2-0fdfda989c3a.png)

**Comment by tut98** [comment]
There are guide layers that will help you know where to draw what.

**Comment by Turealpro11** [comment]
> There are guide layers that will help you know where to draw what.

i know that , but i told u i wanna see how it looks i mean, sometimes when u get it ing some bugs will be in the car, i think u got me

**Comment by tut98** [comment]
I don't think it's necessary, looks good to me.

**Comment by Turealpro11** [comment]
> I don't think it's necessary, looks good to me.

alright thank u, u can go ahead i mean i think all done

**Comment by tut98** [comment]
Wrap's on its way as `turealpro11_2`

**Comment by Turealpro11** [comment]
How long will the Wrap be on the Server?
@tut98

**Comment by tut98** [comment]
Shouldn't take more than a couple of days.

**Comment by Turealpro11** [comment]
Okey
