### ISSUE TITLE
Turismo wrap reqest

### ISSUE THREAD

**Issue by Haky22** [saesrpg/donation-vehicle-shaders#23]
For Generic wrap requests :
Name for wrap (e.g camo2): sticker1

**Comment by tutgreco** [comment]
link to wrap is missing and the name is already in use, @Haky22

**Comment by Haky22** [comment]
For Generic wrap requests :
Name for wrap (e.g camo2): sticker1 ( https://i.imgur.com/KGf5s4l.png )

And what do mean with name is already in use?

**Comment by tutgreco** [comment]
i referenced you to Github as on your donation thread you had requested a wrap that we don't have. if you'd like one of our current wraps placed on your vehicle you don't need to use Github. this is only for new wraps that we don't have on the server.

**Comment by Haky22** [comment]
Oh understand, so i need just put it in saes donation topic and thats all yes?

**Comment by tutgreco** [comment]
yeah, just mention that you'd like sticker1 instead of the custom shade you linked there.
