### ISSUE TITLE
MIT Shader Request

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#230]
**Vehicle ID**
598 Police LV

**Wrap name**
gang_mit

**Needs testing**
No, thanks.

**Wrap image**
![MIT_LV_GM](https://user-images.githubusercontent.com/62222691/111052744-0b852700-845e-11eb-9601-315375bd0317.png)

**Comment by SAESHenry** [comment]
Approved
