### ISSUE TITLE
Blue's wrap req

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/donation-vehicle-shaders#231]
**Vehicle ID**
482

**Wrap access**
blue35

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/25811/blue-s-reward-change

**Translations**
n/a

**Wrap image**
![turk (1)](https://user-images.githubusercontent.com/62670831/111077272-0c22c980-8501-11eb-93e0-18a30fd73b8f.png)

**Comment by tut98** [comment]
Looks good to me. Would you like this added?

**Comment by BlueSAES** [comment]
Yes of course!

**Comment by tut98** [comment]
Wrap's on its way as `blue35_1`
