### ISSUE TITLE
Daniel's Custom Wrap

### ISSUE THREAD

**Issue by 3Bo0** [saesrpg/donation-vehicle-shaders#232]
**Vehicle ID**
598
**Wrap access**
3bo010 & xtmx & xxmrtrollstylexx
**Needs testing**
Yes, need testing to ensure that everything is fine in the design.

**Thread for reward change**
https://saesrpg.uk/topic/19608/donation-daniel-%D0%B2%D0%B8%D1%81%D0%B5%D0%BB%D0%B8%D1%86%D0%B0-3970-amount-20-00-gbp
**Translations**

**Wrap image**

![NoBryanytut](https://user-images.githubusercontent.com/67001169/111117975-429c2b00-8579-11eb-9034-8f82bcf6e103.png)

**Comment by tut98** [comment]
A similar wrap is already on the server as `3bo010_2` @ #217 
You can use it for reference.

Is the wrap in this issue a replacement for #217 ?

**Comment by 3Bo0** [comment]
Yea it is the issue replacement  for #217

**Comment by tut98** [comment]
Nice. Check the old version for reference and let me know when the new version is good to go.

**Comment by 3Bo0** [comment]
Check #217 @tut98

**Comment by tut98** [comment]
Looks fine to me.
Old version is already ingame so use that as reference!

**Comment by 3Bo0** [comment]
For you? yeah it is fine but in-game it is not because I did something wrong in the design so when you have free time I hope you can test it.
![11](https://user-images.githubusercontent.com/67001169/111102559-710c0d00-855d-11eb-8d0e-3c4009fb22d0.png)

**Comment by 3Bo0** [comment]
> Looks fine to me.
> Old version is already ingame so use that as reference!

Also, you can delete/update the old version and put this instead.

**Comment by tut98** [comment]
It does not need testing. The old version is so similar to the new one you can use it for reference.

**Comment by 3Bo0** [comment]
Now you said it does not need testing because it is so similar and in #217 you said the same for no reason?
and because of "it looks fine to me" I am here.
Again I'm saying I want it to get tested, it is not about the similarity it is about the mistakes.

**Comment by tut98** [comment]
Take a look at what's been said.

**Comment by 3Bo0** [comment]
Rejected because I wanted it to get tested?
![Screenshot_1](https://user-images.githubusercontent.com/67001169/111255933-163fe780-8629-11eb-85aa-4cac01874e42.png)

**Comment by tut98** [comment]
Yes, because I have listed your options for getting this wrap added.

There is no gurantee for a preview, it is up to our discretion to judge whether or not one is needed.

For the 5th time, use the wrap you have ingame as reference and the guide layers in the photoshop file.
