### ISSUE TITLE
BMW M3 Custom Wrap

### ISSUE THREAD

**Issue by FormulaOG** [saesrpg/donation-vehicle-shaders#235]
**Vehicle ID**
494

**Wrap access**
formula

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/25913/donation-formula-amount-10-00-gbp

**Wrap image**
![m3](https://user-images.githubusercontent.com/80972009/111826726-6f28ad80-88bf-11eb-9531-7299c09cda3a.png)

**Comment by tut98** [comment]
Please upload image in your post as requested in the issue template.
Include your username, these do not have uppercase letters.

**Comment by FormulaOG** [comment]
> Please upload image in your post as requested in the issue template.
> Include your username, these do not have uppercase letters.

I fixed this issue sorry. Thanks.

**Comment by tut98** [comment]
Wrap's on its way as `formula_1`, please keep background opaque for future uploads
