### ISSUE TITLE
Custom Buffalo Wrap

### ISSUE THREAD

**Issue by FormulaOG** [saesrpg/donation-vehicle-shaders#236]
**Vehicle ID**
402

**Wrap access**
formula

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/25915/donation-formula-amount-10-00-gbp

**Wrap image**
![r34](https://user-images.githubusercontent.com/80972009/111826826-89628b80-88bf-11eb-8862-e467ee147930.png)

**Comment by tut98** [comment]
See feedback on #235

**Comment by FormulaOG** [comment]
> See feedback on #235

I fixed this issue sorry. Thanks.

**Comment by tut98** [comment]
Wrap's on its way as `formula_2`
