### ISSUE TITLE
Kanox Car wrap

### ISSUE THREAD

**Issue by Valgitin** [saesrpg/donation-vehicle-shaders#237]
**Vehicle ID**

598
**Wrap access**

valgitin
**Needs testing**

yes, if u think it needs 
**Thread for reward change**

https://saesrpg.uk/topic/25947/kanox-s-reward-change-by-my-warp?_=1616419934207
**Translations**

N/A
**Wrap image**

![LVPOLICENeutro](https://user-images.githubusercontent.com/80906242/111854280-a7130d80-891e-11eb-8988-402e9a43e388.png)

**Comment by tut98** [comment]
Looks good to me, but I think the white text is too thin and vague to be read.
Let me know if it needs working on or you want it added now.

**Comment by Valgitin** [comment]
> Looks good to me, but I think the white text is too thin and vague to be read.
> Let me know if it needs working on or you want it added now.

Fixed , thanks for the note, and here's the fixed one.
![LVPOLICENeutro](https://user-images.githubusercontent.com/80906242/111870304-3acaf500-8984-11eb-83ae-2830a5a8ca7a.png)

**Comment by tut98** [comment]
Wrap's on its way as `valgitin_1`
