### ISSUE TITLE
Petrow Custom Wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#239]
**NOTE: Posting this on behalf of Petrow because he doesn't know how to request.**

**Vehicle ID**
482

**Wrap access**
presko99

**Needs testing**
Yes please

**Thread for reward change**
https://saesrpg.uk/topic/25956/petrow-s-reward-change

**Translations**
N/A

**Wrap image**
![template_Buritto](https://user-images.githubusercontent.com/60038193/111907661-9ebdee00-8a56-11eb-81c3-6b72b6139872.jpg)

**Comment by tut98** [comment]
Won't need a preview.

**Comment by Liyones** [comment]
Alright can be added

**Comment by tut98** [comment]
Wrap's on its way as `presko99_1`
