### ISSUE TITLE
Updated shader to accomodate fixes.

### ISSUE THREAD

**Issue by DemienD** [saesrpg/donation-vehicle-shaders#24]
Hey,

I've updated ETF's shader ([original request](https://github.com/saesrpg/donation-vehicle-shaders/issues/20)) to fix some glitches and add some changes.

For Custom wrap request :

> Vehicle ID: 598
> Wrap access locked to usernames (leave blank if public): mrredbull, AntiRug
> Wrap name: `etfBomb`

Updated graphic:

![ETF shader](https://user-images.githubusercontent.com/15146566/64922389-02ff5200-d7cf-11e9-8409-f7a683b87eb8.png)

**Comment by Vennelle** [comment]
This was upon request from me and therefor is approved by me.

**Comment by tutgreco** [comment]
This was live since last week.
