### ISSUE TITLE
HLS Wrap

### ISSUE THREAD

**Issue by steven517** [saesrpg/donation-vehicle-shaders#240]
**Vehicle ID**
Police LV(with light bar) 598

**Wrap name**
gang_hls

**Needs testing**
yes, this just needs to be tested for now, HLS leaders will have to approve it before they request it themselves.

**Wrap image**
![HLSpolicelv](https://user-images.githubusercontent.com/67033453/111937230-e7909980-8a8c-11eb-906a-7e7b333aa24f.png)

**Comment by tut98** [comment]
Looks good to me

**Comment by steven517** [comment]
Can I get pictures of what it looks like in-game? I'm making these for other people which they are paying me to do, so I would like to show them how it actually looks in-game. And I need to ensure theres no text warping and that all the text is clear and legible on the vehicle
