### ISSUE TITLE
SAM wrap

### ISSUE THREAD

**Issue by steven517** [saesrpg/donation-vehicle-shaders#241]
**Vehicle ID**
490
**Wrap name**
gang_sam

**Needs testing**
Yes, just needs to be tested first so that SAM leaders can approve it.

**Wrap image**
![SAMfbirancher](https://user-images.githubusercontent.com/67033453/111937807-2f63f080-8a8e-11eb-8164-14d4f43a3ac5.png)

**Comment by tut98** [comment]
Had a look, looks fine to me

**Comment by steven517** [comment]
Can I get pictures of what it looks like in-game? I'm making these for other people which they are paying me to do, so I would like to show them how it actually looks in-game. And I need to ensure theres no text warping and that all the text is clear and legible on the vehicle

**Comment by tut98** [comment]
If you search `490` in this github repo, you might find some screenshots of similar wraps

**Comment by steven517** [comment]
Looking at other peoples wraps will not show me if I need to use a different font for better legibility or show me if the position of an image needs to be adjusted to ensure it wraps on the vehicle properly.

**Comment by tut98** [comment]
It will look fine, I know this being the creator of the photoshop file - it should also have helper layers to show where things should be painted. Unless something needs lining up, I don't see the need for a preview.
The only thing I would change is making the rear and front bumper black, like the sides

**Comment by steven517** [comment]
I'm not comfortable just trusting it looks good, I've done enough shaders to know things always can look different in-game, you can close both of my requests, I'll find a way to test these myself
