### ISSUE TITLE
KiroSa Custom Warp

### ISSUE THREAD

**Issue by KiroSa6ko** [saesrpg/donation-vehicle-shaders#242]
**Vehicle ID**
598

**Wrap access**
malikvx

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/25932/donation-kirosa-amount-10-00gbp?_=1616437644972
**Translations**
N/A
**Wrap image**
https://imgur.com/CtLJ0Sk

**Comment by KiroSa6ko** [comment]
![unknown](https://user-images.githubusercontent.com/78746386/112042867-51ba4480-8b48-11eb-8087-3d0120702bfd.png)

**Comment by tut98** [comment]
The issues are due to the image resolution being 473 x 452 rather than 512 x 512.
https://imgur.com/a/tKPHvCg

**Comment by KiroSa6ko** [comment]
i'll contact the guy who made it and i'll fix it

**Comment by KiroSa6ko** [comment]
![wrap](https://user-images.githubusercontent.com/78746386/112159818-d6a96a80-8be9-11eb-834e-7f1e2f0630a1.png)

**Comment by tut98** [comment]
Should look fine, I don't think it'll need testing.
Check the helper layer to make sure everything lines up the way you want it to.

**Comment by KiroSa6ko** [comment]
alright it can be added

**Comment by tut98** [comment]
Please make it 512x512

**Comment by KiroSa6ko** [comment]
![wut](https://user-images.githubusercontent.com/78746386/112331111-eb086880-8cb8-11eb-83cd-bdf7c32b07e9.PNG)
i thought you said its fine :( ok lemme tell the guy who made it to fix it

**Comment by KiroSa6ko** [comment]
he said he lost the psd file can you wait until he made another one !

**Comment by Liyones** [comment]
Hey @KiroSa6ko i think there is no need to new one i tried to resize it for you but the quality little bit bad so.
![Webp net-resizeimage](https://user-images.githubusercontent.com/60038193/112334583-d24d8200-8cbb-11eb-9453-8d8f9ebc0484.png)

**Comment by KiroSa6ko** [comment]
@tut98  does the one @Liyones  post is fine ?

**Comment by tut98** [comment]
Yep, if you use the up-to-date issue template, it will let you know to submit 512x512 files

**Comment by tut98** [comment]
Erm, the image template is centered on the canvas.
The file you sent is hugging the top of the canvas - this needs fixing.

**Comment by Valgitin** [comment]
yo @tut98 im the one who made that wrap, well we've made some changes . here u go
![Kirosawrap](https://user-images.githubusercontent.com/80906242/112346467-442ac900-8cc6-11eb-881f-70b6ddc1d508.png)

**Comment by KiroSa6ko** [comment]
@tut98  how is it the one that @Valgitin  post ?

**Comment by Raf0-0** [comment]
> @tut98 how is it the one that @Valgitin post ?

Hey @tut98 @KiroSa6ko im the one who made the wrap, so here u go and hope it's good for u tut.
![Kirosawrap](https://user-images.githubusercontent.com/78949505/112347401-1db95d80-8cc7-11eb-8c1a-c66e2de21685.png)

**Comment by tut98** [comment]
> > @tut98 how is it the one that @Valgitin post ?
> 
> Hey @tut98 @KiroSa6ko im the one who made the wrap, so here u go and hope it's good for u tut.
> ![Kirosawrap](https://user-images.githubusercontent.com/78949505/112347401-1db95d80-8cc7-11eb-8c1a-c66e2de21685.png)

Better detail, but front and rear text looks stretched. I would also consider rotating rear text 180 degrees.

**Comment by Raf0-0** [comment]
> > > @tut98 how is it the one that @Valgitin post ?
> > 
> > 
> > Hey @tut98 @KiroSa6ko im the one who made the wrap, so here u go and hope it's good for u tut.
> > ![Kirosawrap](https://user-images.githubusercontent.com/78949505/112347401-1db95d80-8cc7-11eb-8c1a-c66e2de21685.png)
> 
> Better detail, but front and rear text looks stretched. I would also consider rotating rear text 180 degrees.

ok so i'll change the text and turn it 180° as u told me , thank u

**Comment by Raf0-0** [comment]
@tut98 do u think it's cool now or i need to do the same for the logos ? 

![Kirosawrap](https://user-images.githubusercontent.com/78949505/112352502-1ac06c00-8ccb-11eb-81a7-543a4d30e385.png)

**Comment by tut98** [comment]
Its fine

**Comment by tut98** [comment]
Wrap's on its way as `malikvx_1` :slightly_smiling_face:
