### ISSUE TITLE
DROT's Custom Wrap

### ISSUE THREAD

**Issue by DROTDROT** [saesrpg/donation-vehicle-shaders#243]
**Vehicle ID**
423

**Wrap access**
milicajac

**Needs testing**
Yes

**Thread for reward change**
pls

**Translations**
No

**Wrap image**
![enforcer try 1 no helpers](https://user-images.githubusercontent.com/52143114/112068096-87bbf080-8b69-11eb-9729-89d0c5fa376d.png)

**Comment by tut98** [comment]
Wrap's added as `milicajac_1`
