### ISSUE TITLE
LoungeVC's Wrap

### ISSUE THREAD

**Issue by Niklaus-187** [saesrpg/donation-vehicle-shaders#244]
**Vehicle ID**
400

**Wrap name**
gang_LoungeVC

**Needs testing**
Yes, please.
**Wrap image**
![LoungeVC Wrap](https://user-images.githubusercontent.com/66783522/112184669-dbd1de00-8c18-11eb-813f-85b66560870b.png)

**Comment by tut98** [comment]
https://imgur.com/a/fFabMEd

**Comment by Niklaus-187** [comment]
![lands](https://user-images.githubusercontent.com/66783522/112515536-c7741980-8daf-11eb-9e78-db5f4ffabff4.jpg)

**Comment by Niklaus-187** [comment]
Please, test it again and check if the text is clear now.

**Comment by tut98** [comment]
It's placed correctly.

**Comment by Niklaus-187** [comment]
Alright, you can add it then.

**Comment by tut98** [comment]
Wrap's on its way but name is lowercase

**Comment by Niklaus-187** [comment]
@tut98 is it uploaded? the issue is closed and archived but admins couldn't find it in-game.
