### ISSUE TITLE
Elements's Custom Wrap

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#245]
**Vehicle ID**
598 Police LV (GTA5)

**Wrap access**
denis10

**Needs testing**
No.

**Thread for reward change**
https://saesrpg.uk/topic/25943/donation-element-amount-10-00gbp?_=1616521004544

**Wrap image**

![](https://i.imgur.com/JulhyFsh.jpg)

**Comment by tut98** [comment]
Please upload file to github so that it will embed

**Comment by TheRealElement** [comment]
Should be good now.

**Comment by tut98** [comment]
Wrap's on its way as `denis10_12`
