### ISSUE TITLE
Spanish new Custom Wraps

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#247]
Good morning, I want to add new wraps to the game, via reward exchange. There are 3 wraps, which must be specified in order

**Thread for reward change:** https://saesrpg.uk/topic/26012/spanish-reward-change

**- Wrap number 1**

**Vehicle ID:** [490] - FBI Rancher 

**Wrap access:** lapd0070, johnnyenglish

**Needs testing:** If possible yes, if you consider that it is not necessary, do not do it

**Wrap image:** https://i.imgur.com/iAhTl46.png

**- Wrap number 2**

**Vehicle ID:** [416] - Ambulance

**Wrap access:** lapd0070, johnnyenglish and San Andreas Medics members if they want it

**Needs testing:** If possible yes, if you consider that it is not necessary, do not do it

**Wrap image:** https://i.imgur.com/Bq5GYnM.png

**- Wrap number 3**

**Vehicle ID:** [596] - Police LS

**Wrap access:** lapd0070, bas260, king1992

**Needs testing:** If possible yes, if you consider that it is not necessary, do not do it

**Wrap image:** https://i.imgur.com/UfYMJ1D.png

**Comment by tut98** [comment]
490: Looks fine
416: May want to recolor the rear text as it can be hardly read, but besides that it looks fine
596: Front sides text will be distorted if you don't reduce the scale a little bit, other than that it looks fine

Please upload images as files straight to github

**Comment by LAPDSpanishVEN** [comment]
![FHPCV](https://user-images.githubusercontent.com/72228343/112534007-5ae62400-8d89-11eb-8f92-4686f8b4fc80.png)
![ambulancia](https://user-images.githubusercontent.com/72228343/112534010-5c175100-8d89-11eb-8de4-60602da186ef.png)
![SAM Camioneta 2](https://user-images.githubusercontent.com/72228343/112534032-620d3200-8d89-11eb-921a-7c87db521fa9.png)

**Comment by tut98** [comment]
490 on its way as lapd0070_4
416 on its way as lapd0070_5 (existing wrap lapd0070_3 looks very similar, want it removed?)
490 on its way as lapd0070_6

**Comment by LAPDSpanishVEN** [comment]
You can remove the lapd0070_1 and lapd0070_3 wrap

Thanks for the help
