### ISSUE TITLE
Homeland Security Custom Wrap

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#248]
**Vehicle ID**
598 Police LV (GTA5)

**Wrap name**
gang_hls

**Needs testing**
No.

**Wrap image**
![image](https://user-images.githubusercontent.com/46727042/112475252-44d06780-8d79-11eb-889d-493c1d464b15.png)

**Comment by tut98** [comment]
Wrap's on its way, please add solid background for future uploads!
