### ISSUE TITLE
kockata custom wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#249]
**NOTE: POSTING THIS ON BEHALF OF kockata BECAUSE HE DON'T KNOW HOW TO USE IT**
**Vehicle ID**
482

**Wrap access**
kockata

**Needs testing**
Yes please

**Thread for reward change**
https://saesrpg.uk/topic/26029/donation-kockata-amount-20-00-gbp

**Translations**
efbet is gambling site  , and the logo in is bulgarian logo

**Wrap image**
![template_Buritto](https://user-images.githubusercontent.com/60038193/112555294-365d6c80-8dc8-11eb-9a8f-4787ba1440f5.jpg)

**Comment by tut98** [comment]
Please remove the gambling site from the wrap and it will be good to go

**Comment by Liyones** [comment]
Hey Tut sorry for late answer i was busy with school and irl problems , here you go
![template_Buritto](https://user-images.githubusercontent.com/60038193/113302381-44e3e080-9300-11eb-879a-10a3fe7a9ebc.jpg)

**Comment by tut98** [comment]
Wrap's on its way as `kockata_1`
