### ISSUE TITLE
Custom wrap request

### ISSUE THREAD

**Issue by NotFunni** [saesrpg/donation-vehicle-shaders#25]
Vehicle ID: 482
Wrap access locked to usernames (leave blank if public): Cimba12, Ferthistheking17, Bassewass, xpro, cheaty.
Name for wrap (e.g tutPD): RebelsKustoms

[https://cdn.discordapp.com/attachments/206766247910703104/642871683920953366/template_Buritto2.png]

**Comment by tutgreco** [comment]
Usernames were corrected in this update
