### ISSUE TITLE
Custom Wrap San Andreas Interceptors

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#251]
**Vehicle ID**
598

**Wrap name**
gang_sai

**Needs testing**
No

**Wrap image**
![SAI_FINAL_512px](https://user-images.githubusercontent.com/46720463/112733462-84957b80-8f40-11eb-8da5-89869c75bed9.png)

**Comment by IEDaryl** [comment]
Approved
