### ISSUE TITLE
ZoRo's Constum wrap

### ISSUE THREAD

**Issue by ZoRo12425** [saesrpg/donation-vehicle-shaders#255]
**Vehicle ID** police LV 598

**Wrap access** ZoRo124

**Needs testing** Yes, please.

**Thread for reward change** N/A for now.

**Translations** N/A

**Wrap image**
![9sgKTZ3h](https://i.imgur.com/9sgKTZ3.png)

Note: I would like to put it instead of my zoro124_1 wrap.

**Comment by tut98** [comment]
Please upload file to github, and export with lossless PNG so that it doesn't use quality unnecessarily 🙂

**Comment by ZoRo12425** [comment]
Done.

**Comment by tut98** [comment]
https://imgur.com/a/RF4vC8G

**Comment by ZoRo12425** [comment]
you can cancel this, Vote went bad. Thanks for testing.
