### ISSUE TITLE
Gang Management wrap for San Andreas Federal Police

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#256]
**Vehicle ID:** 598

**Wrap name:** gang_safp

**Needs testing:** No

**Wrap image**
![halo-2](https://user-images.githubusercontent.com/72228343/112938745-93c32780-9100-11eb-999b-9a4e2d08dc01.png)

**Comment by tut98** [comment]
Please submit as 512x512, then Gang Management will review your wrap.

**Comment by LAPDSpanishVEN** [comment]
Updated, sorry for the inconvenience
![SAFP Wrap](https://user-images.githubusercontent.com/72228343/112966241-6be3bc00-9120-11eb-9929-07a3bf7e3d04.png)

**Comment by SAESHenry** [comment]
Approved
