### ISSUE TITLE
Velo's Custom Wrap Request

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#257]
**Vehicle ID**
480

**Wrap access**
velona77

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/26126/donation-velo-amount-30-00gbp

**Translations**

**Wrap image**
![comet](https://user-images.githubusercontent.com/46403782/113348659-8cd62800-933f-11eb-97a4-113ab193e89d.png)

**Comment by tut98** [comment]
https://imgur.com/a/ZotbICL

**Comment by Velona77** [comment]
Looks alright, can be pushed live

**Comment by tut98** [comment]
Wrap's on its way as `velona77_6`
