### ISSUE TITLE
Terry's Custom Wrap Request

### ISSUE THREAD

**Issue by TheMetalizer** [saesrpg/donation-vehicle-shaders#258]
**Vehicle ID**
598

**Wrap access**
rizacem, velona77, zizi31, ayturk1905, pekecan, sinanreis

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/26145/donation-terry-amount-20-00-gbp

**Translations**
N/A

**Wrap image**
![image](https://user-images.githubusercontent.com/48535190/113441220-94a4d380-93f6-11eb-9b7c-cc73a0128f9b.png)

**Comment by tut98** [comment]
Can you trim it down to say 6 usernames?

**Comment by TheMetalizer** [comment]
> Can you trim it down to say 6 usernames?

Updated.

**Comment by tut98** [comment]
https://imgur.com/a/tfgcsGE
