### ISSUE TITLE
Custom wrap BloodZ  Skin

### ISSUE THREAD

**Issue by anxhelo00** [saesrpg/donation-vehicle-shaders#259]
**Vehicle ID**
Damaged Glendale

**Wrap access**
 anxhelo00
**Needs testing**

**Thread for reward change**
maybe
**Translations**
 https://saesrpg.uk/topic/26079/donation-blaze-amount-20-00-gbp?_=1617469670806
**Wrap image**
https://imgur.com/gallery/VeKiVkJ

**Comment by tut98** [comment]
Wrap looks good to me, but please upload the file here to github

**Comment by anxhelo00** [comment]
https://i.imgur.com/kKXAOwJ_d.webp?maxwidth=760&fidelity=grand

**Comment by anxhelo00** [comment]
![](https://media.discordapp.net/attachments/811948370960580618/825841005646970960/Blazewrap.png)

**Comment by tut98** [comment]
Wrap's on its way as `anxhelo00_1`
