### ISSUE TITLE
rapmachin3re custom wrap request

### ISSUE THREAD

**Issue by rapmachin3re** [saesrpg/donation-vehicle-shaders#260]
**Vehicle ID**
604

**Wrap access**
 rapmachin3re

**Needs testing**
 Yes

**Thread for reward change**
 https://saesrpg.uk/topic/26225/rap-change-reward

**Translations**
 Akciq Respect -> Action Respect ; Kokainov Kral -> Cocaine King ; Tejak Nokaut -> Heavy Knockout ( This guy is a meme in my country if the words are not in it the wrap the wrap wont look good at all there is noting such as insults or bad behavior in it. )

**Wrap image**

![template_glenshit](https://user-images.githubusercontent.com/81902663/113505839-90d19800-9541-11eb-8873-fa79bb054f51.jpg)

**Comment by tut98** [comment]
You sure you want it to be only 256x256? Details will be very vague.
Other than that, wrap looks ok.

**Comment by Liyones** [comment]
Hey @tut98 im the guy who made the wrap , seems the guy used wrong way to upload it from discord directly and that cause to make it low size , uploaded the correct and original one , I think it's good to go now :+1:

**Comment by tut98** [comment]
Wraps on its way as `rapmachin3re_1`
