### ISSUE TITLE
Santos custom wrap request

### ISSUE THREAD

**Issue by Blizzard-fs** [saesrpg/donation-vehicle-shaders#261]
**Vehicle ID**
402

**Wrap access**
badass123

**Needs testing**
yes, if it looks good for you you can push it live right away

**Thread for reward change**
https://saesrpg.uk/topic/26242/nebraskian-s-reward-change?_=1617581898806

**Translations**
No need

**Wrap image**
![TEMPLATE_BLAZE_IT](https://user-images.githubusercontent.com/58548607/113526208-6cb19d80-95b9-11eb-8ff7-d6eb8dd65c16.png)

**Comment by tut98** [comment]
> **Needs testing**
> yes, if it looks good for you you can push it live right away

Tested and looks as expected, wrap's on its way as `badass123_1`
