### ISSUE TITLE
bas260's custom wrap. 

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#262]
I'd like this wrap to replace the bas260_3
It should be a fbi rancher wrap. 

**Vehicle ID**
490

**Wrap access**
bas260

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/26272/donation-bas260-amount-50-00-gbp

**Translations**

**Wrap image**
![RANCHER_INTERCEPTOR_512px](https://user-images.githubusercontent.com/46720463/113752947-d347d000-970d-11eb-9bec-9be4b7bce615.png)

**Comment by tut98** [comment]
Wrap's on its way
