### ISSUE TITLE
Hell Raisers MC Custom Wrap

### ISSUE THREAD

**Issue by Franklin880** [saesrpg/donation-vehicle-shaders#263]
**Vehicle ID**
482

**Wrap access**
jack269, franklinclint, isis02, tomaz96, witti, suporter, judas00

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/26295/woytex-s-reward-change

**Translations**
N/A

**Wrap image**

![franklin](https://user-images.githubusercontent.com/47274304/114015085-9e509000-9869-11eb-88fa-7a439442ea60.jpg)

**Comment by tut98** [comment]
Are you sure it needs a preview?
The logos will wrap around well. There is a guide layer in the photoshop file that will help.

**Comment by Franklin880** [comment]
@tut98 No need for a preview then if you say so!

**Comment by tut98** [comment]
Wraps on its way as `franklinclint_1`

**Comment by tut98** [comment]
Changing to `jack269_1`
