### ISSUE TITLE
Vynee's Wrap 

### ISSUE THREAD

**Issue by Vynee** [saesrpg/donation-vehicle-shaders#264]
Vehicle ID
604

Wrap access
MotazAttia

Needs testing
Yes
Thread for reward change
https://saesrpg.uk/topic/26386/vynee-s-reward-change
Translations
N/A
Wrap image
![1](https://user-images.githubusercontent.com/82264967/114267072-164dc000-99fa-11eb-8e23-3ea643b0bcd0.png)

**Comment by tut98** [comment]
https://imgur.com/a/EWSAvPa

**Comment by Vynee** [comment]
@tut98 is cool thank you for testing 
When I can Sort it?

**Comment by tut98** [comment]
It will be live once we add a 'completed' label and the issue gets closed

**Comment by Vynee** [comment]
@tut98 Just do it Soon :)

**Comment by tut98** [comment]
Please keep usernames lowercase going forwards!
Wrap's on its way as `motazattia_1`
