### ISSUE TITLE
SAM custom wrap

### ISSUE THREAD

**Issue by steven517** [saesrpg/donation-vehicle-shaders#265]
**Vehicle ID**
490

**Wrap access**
n/a

**Needs testing**
yes

**Thread for reward change**
just needs tested for now, SAM will request it once the wrap is complete

**Translations**
n/a

**Wrap image**
![SAMfbirancher2](https://user-images.githubusercontent.com/67033453/114317959-d523e180-9ac7-11eb-9023-9e0e3d0ff3f9.png)

**Comment by tut98** [comment]
https://imgur.com/a/aDEtnlO

**Comment by steven517** [comment]
All good thanks, you can close this
