### ISSUE TITLE
Blue's Cutom Wrap REQ

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/donation-vehicle-shaders#266]
**Vehicle ID** 
482

**Wrap access**
blue35

**Needs testing**
yes, last one had terribly bad looking ingame.

**Thread for reward change**
https://saesrpg.uk/topic/26412/blue-s-reward-change

**Translations**
N/A

**Wrap image**
![blue_buritto](https://user-images.githubusercontent.com/62670831/114321603-590bb700-9b24-11eb-9d2a-5decc3db5ebd.jpg)

**Comment by tut98** [comment]
Please keep it 256x256 or 512x512. I recommend 512x512 if you don't want it to look bad.

**Comment by BlueSAES** [comment]
i will get it updated soon, but no idea how to since I'm not the one who made it. Could you give a hand

**Comment by tut98** [comment]
Has to be done by the designer, as simply upscaling to 512x512 will not improve the quality

**Comment by Vynee** [comment]
@tut98 Just Do it Soon :)

**Comment by BlueSAES** [comment]
should be done i think
![template_Buritto](https://user-images.githubusercontent.com/62670831/114732534-458e6500-9d4b-11eb-9d52-f8fe64ff0f69.jpeg)

**Comment by tut98** [comment]
Wrap's on its way as `blue35_1`
