### ISSUE TITLE
Custom Wrap for DUFF

### ISSUE THREAD

**Issue by Duffy1907** [saesrpg/donation-vehicle-shaders#27]
I want this wrap added on a burrito : vehicle id is 482

Account Name : fener1907
you can add burrito instead of hotring racer 3 at cripz base ( please remove hotring racer 3 )

![template_Buritto](https://user-images.githubusercontent.com/46969530/70050786-d514f700-15e0-11ea-8ab0-a3676a66869f.png)

**Comment by tutgreco** [comment]
reopening this so that the required changes can be requested

**Comment by Duffy1907** [comment]
![template_Buritto](https://user-images.githubusercontent.com/46969530/71304411-65bc4700-23d7-11ea-9891-ec42efe9d8ea.png)
