### ISSUE TITLE
BRINKS Costum Wrap

### ISSUE THREAD

**Issue by ZoRo12425** [saesrpg/donation-vehicle-shaders#270]
**Vehicle ID** 598

**Wrap access** 
ZoRo124-lapd0070-ALIJR007

**Needs testing** Yes, please.

**Thread for reward change** https://saesrpg.uk/topic/26538/zoro-s-reward-change

**Wrap image**
![template](https://i.imgur.com/2yN1xj7.jpg)

Note: If possible please name the wrap as BRINKS_1 (if not, replace it with zoro124_1) Thanks!

**Comment by tut98** [comment]
Right side text needs fixing https://imgur.com/a/F7kKrzZ

**Comment by Liyones** [comment]
![template](https://user-images.githubusercontent.com/60038193/115965647-6b292480-a52a-11eb-8bf8-5063a501b078.jpg)
@tut98 looks cool , fixed ;)

**Comment by ZoRo12425** [comment]
Fixed, we can go forward with it.

**Comment by tut98** [comment]
> **Wrap access**
> ZoRo124-lapd0070-ALIJR007
>(if not, replace it with zoro124_1) Thanks!

Replacing existing wrap and adding the 2 new names. Please keep usernames lower-case :)
Wrap's on its way!
