### ISSUE TITLE
Markus' Custom Wrap

### ISSUE THREAD

**Issue by Markus139** [saesrpg/donation-vehicle-shaders#272]
**Vehicle ID** 402

**Wrap access** kalevipoeg

**Needs testing** yes

**Thread for reward change** https://saesrpg.uk/topic/26544/markus-s-reward-change

**Translations** English

**Wrap image** ![alt text](https://cdn.discordapp.com/attachments/584741992630714391/835521093879857152/template.png) or https://cdn.discordapp.com/attachments/584741992630714391/835521093879857152/template.png

**Comment by tut98** [comment]
https://imgur.com/a/nTm2DCQ

**Comment by Markus139** [comment]
Perfect, that can pass then!

**Comment by Markus139** [comment]
Actually no, color needs adjusting.

**Comment by tut98** [comment]
OK thanks for the fast response - if you send final image soon I can include it in today's batch

**Comment by Markus139** [comment]
https://cdn.discordapp.com/attachments/584741992630714391/835670707278184489/unknown.png

Could I also get a test on this real quick?

**Comment by tut98** [comment]
What exactly needs changing? I can recolor if needed.
The image you sent is a screenshot of Photoshop and not an actual image we can use.

**Comment by Markus139** [comment]
![image](https://user-images.githubusercontent.com/47225938/115976311-63db3880-a575-11eb-901e-4b4d0bffee77.png)

I need this color if you can do it and test it and provide screenshots. It's grey-like.

**Comment by tut98** [comment]
Afraid I'll need your designer to do this by themselves.
Alternatively if you can DM (Discord) me your .psd file I can do it now.

**Comment by Markus139** [comment]
![image](https://user-images.githubusercontent.com/47225938/115976361-f4197d80-a575-11eb-9cf5-f42fb1b69cfc.png)

Does this work?

**Comment by tut98** [comment]
It will have to be darker, think \#BDBDBD or so.
Maybe change the front stripes too?
As it's just a color change it wouldn't need testing though.

**Comment by Markus139** [comment]
Moment

**Comment by tut98** [comment]
Clock is ticking :clock1130:

**Comment by Markus139** [comment]
![image](https://user-images.githubusercontent.com/47225938/115976467-152e9e00-a577-11eb-9906-eb55172b835a.png)

**Comment by Markus139** [comment]
Did I make it? And when are they pushed live?

**Comment by tut98** [comment]
Please send as 512x512 dimensions.
Once an issue has the 'accepted' label the ETA is 72 hours.

**Comment by Markus139** [comment]
![image](https://user-images.githubusercontent.com/47225938/115976491-5a52d000-a577-11eb-8d04-5f2b62bcce77.png)

This?

**Comment by tut98** [comment]
That will do.
Wrap's on its way as `kalevipoeg_1`
