### ISSUE TITLE
LandShark's custom wrap

### ISSUE THREAD

**Issue by LandSharkSAFP** [saesrpg/donation-vehicle-shaders#274]
**Vehicle ID** 598

**Wrap access** landsharkppppp

**Needs testing** Yes

**Thread for reward change** Will be made later

**Translations** ---

**Wrap image** 
![Landshark_Policewrap (1)](https://user-images.githubusercontent.com/63316571/117035494-ada9e880-ad04-11eb-8aa3-b7bcd5c51e8b.png)

**Comment by tut98** [comment]
https://imgur.com/a/0wA9xEn

**Comment by LandSharkSAFP** [comment]
![Landshark_Policewrap (2)](https://user-images.githubusercontent.com/63316571/117479237-5d2ec700-af60-11eb-9d85-ec9a66474640.png)

- Dial 911 text fixed, can be uploaded

**Comment by tut98** [comment]
Wrap's on its way as `landsharkppppp_2`
