### ISSUE TITLE
Kok's Custom Wrap

### ISSUE THREAD

**Issue by kokwedy** [saesrpg/donation-vehicle-shaders#275]
**Vehicle ID**

400
**Wrap access**

![KokLandstalker](https://user-images.githubusercontent.com/83719502/117178601-e74d2300-adda-11eb-9321-fac05e717d52.png)

**Needs testing**

Yes
**Thread for reward change**

https://saesrpg.uk/topic/26678/kok-s-reward-change?_=1620230905917
**Translations**

------
**Wrap image**

![KokLandstalker](https://user-images.githubusercontent.com/83719502/117178411![KokLandstalker](https://user-images.githubusercontent.com/83719502/117178454-b79e1b00-adda-11eb-9161-c01aab3566d1.png)1351579b2a0f.png)

**Comment by kokwedy** [comment]
can the colour of vehicle be little darker without touching logos?

**Comment by tut98** [comment]
It's not possible for color function to not affect the logo's

**Comment by kokwedy** [comment]
alright then, it looks good anyway, we can move on next step.
