### ISSUE TITLE
JukyPlatinium's wrap request

### ISSUE THREAD

**Issue by JukyPlatinium** [saesrpg/donation-vehicle-shaders#278]
**Vehicle ID**

https://wiki.multitheftauto.com/wiki/File:Policelv.png
**Wrap access**

jukyplatinium
**Needs testing**

Yes
**Thread for reward change**

**Translations**

**Wrap image**

https://i.ibb.co/3c9SBGM/pdlv.png

**Comment by steven517** [comment]
https://imgur.com/a/E8vVGsz

**Comment by steven517** [comment]
Wrap's on its way as `jukyplatinium_1`
