### ISSUE TITLE
BRINKS Costum Wrap_3

### ISSUE THREAD

**Issue by ZoRo12425** [saesrpg/donation-vehicle-shaders#279]
**Vehicle ID**
427

**Wrap access**
ZoRo124-lapd0070-ALIJR007

**Needs testing**
No.

**Thread for reward change**
https://saesrpg.uk/topic/26538/zoro-s-reward-change?_=1620511228135

**Translations**
N/A

**Wrap image**
![6yq8bV9](https://user-images.githubusercontent.com/74672374/117590939-23151f00-b132-11eb-88d5-3cda2a510285.png)

**Comment by tut98** [comment]
Please remove the helper layer

**Comment by ZoRo12425** [comment]
Done.
