### ISSUE TITLE
Custom Wrap for Joshbond

### ISSUE THREAD

**Issue by Joshbond98** [saesrpg/donation-vehicle-shaders#28]
Vehicle ID: 14889 & 14890
Wrap access locked to usernames (leave blank if public): joshbond
Name for wrap (e.g tutPD): JoshbondSAFP

**Comment by tutgreco** [comment]
Feedback was sent to designer of your wrap a while ago, awaiting it be posted here

**Comment by Joshbond98** [comment]
https://imgur.com/a/8pmzrho

Update one seen in the above link

**Comment by tutgreco** [comment]
wrap looks fine except for a distortion which i believe is related to the vehicle, not the wrap, but your designer is by all means welcome to try and get rid of it if they wish to.
https://cdn.discordapp.com/attachments/308955445568077824/661783805454974996/dss.png

**Comment by Joshbond98** [comment]
Hi tut, I am no longer part of SAFP and most likely will be going to crim. So please do not worry about this wrap. Thanks for your time/help so far.

**Comment by tutgreco** [comment]
10-4, closing. please request it to be opened again if you change your mind
