### ISSUE TITLE
Sollozzo's Custom Wrap Request

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#280]
**Vehicle ID**
427 Enforcer

**Wrap access**
Sollozzo, 40salih

**Needs testing**
No, thanks

**Translations**
Full english

**Wrap image**
![MIT_ENFORCER](https://user-images.githubusercontent.com/62222691/118058428-7be0f380-b38e-11eb-8069-fd83d11aa7d8.png)

---

**Vehicle ID**
598 Police LV

**Wrap access**
Sollozzo, 40salih

**Needs testing**
No, thanks

**Translations**
Full english

**Wrap image**
![mit-anti-gang](https://user-images.githubusercontent.com/62222691/118058681-0cb7cf00-b38f-11eb-9b8e-d5c5a647aff5.png)

**Comment by tut98** [comment]
Wraps are on their way as `sollozzo_12` and `sollozzo_13`, respectively
