### ISSUE TITLE
Turismo

### ISSUE THREAD

**Issue by Sharlock016** [saesrpg/donation-vehicle-shaders#281]
**Vehicle ID**
 451

**Wrap access**
 sharlock

**Needs testing**
 Yes

**Thread for reward change**
 https://saesrpg.uk/topic/26779/donation-undefined-amount-30-00-gbp/1?_=1620946310012

**Translations**
 all english character 
(İhtiyaroyundami)=Is oldman in the game

**Wrap image**
 https://imgur.com/a/QUF0oa3

**Comment by tut98** [comment]
Please upload the file straight to github with 512x512 dimensions. Then one of us will be able to test it for you 😃

**Comment by steven517** [comment]
https://imgur.com/a/y8LrYly

If you wish to make any revisions please make sure to just drag and drop the file straight into GitHub to upload the image.

**Comment by Sharlock016** [comment]
> https://imgur.com/a/y8LrYly
> 
> Herhangi bir revizyon yapmak isterseniz, lütfen resmi yüklemek için dosyayı doğrudan GitHub'a sürükleyip bıraktığınızdan emin olun.
> Aksi takdirde, gitmek için iyi olup olmadığını bana bildirin.

**Comment by steven517** [comment]
Wrap is on its way as `sharlock_1`

**Comment by steven517** [comment]
Wrap is live
