### ISSUE TITLE
BLUE'S CUSTOM WRAP

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/donation-vehicle-shaders#282]
**Vehicle ID**

494

**Wrap access**

Blue35 

**Needs testing**

YES PLEASE

**Thread for reward change**

https://saesrpg.uk/topic/26815/blue-s-rew-change

**Translations**

N/A

**Wrap image**

![wrap_blue](https://user-images.githubusercontent.com/62670831/118295192-3f271080-b4e4-11eb-87ae-dd0dd35e52e1.jpg)

**Comment by steven517** [comment]
https://imgur.com/a/b9tJdgU

**Comment by BlueSAES** [comment]
Looks decent, it's good to go!

**Comment by steven517** [comment]
Wrap is on its way as `blue35_3`

**Comment by steven517** [comment]
Wrap is live
