### ISSUE TITLE
Brinks Costum wrap_3

### ISSUE THREAD

**Issue by ZoRo12425** [saesrpg/donation-vehicle-shaders#283]
**Vehicle ID**
427

**Wrap access**
ZoRo124-lapd0070-ALIJR007

**Needs testing**
Yes.

**Thread for reward change**
N/A

**Wrap image**
![HGVvW1a](https://user-images.githubusercontent.com/74672374/118378772-37e02f80-b5d6-11eb-9449-42d5c5c11f52.png)

Note:(there were some mistakes with my zoro124_3 wrap, So I want to put this one instead of it.)

**Comment by steven517** [comment]
https://imgur.com/a/DtdLSKl

**Comment by ZoRo12425** [comment]
It looks ok, we can load it in-game.

**Comment by steven517** [comment]
Wrap is on its way as `zoro124_3`

**Comment by steven517** [comment]
the fixed wrap is live
