### ISSUE TITLE
Glendale Wrap

### ISSUE THREAD

**Issue by MaliciousGirlFriend** [saesrpg/donation-vehicle-shaders#284]
**Vehicle ID**
604

**Wrap access**
malicious

**Needs testing**
yes

**Thread for reward change**
<https://saesrpg.uk/topic/26831/donation-malicious-amount-20-00-gbp>

**Translations**
kurva infront of the wrap everyone knows what this means

**Wrap image**
<
![A](https://user-images.githubusercontent.com/84158178/118404006-6c54f980-b671-11eb-9686-11350ce514ed.png)
>

**Comment by steven517** [comment]
https://imgur.com/a/qOiQDA0
Feel free to make any revisions, otherwise let me know if its good to go.

**Comment by MaliciousGirlFriend** [comment]
![A](https://user-images.githubusercontent.com/84158178/118414004-78a57a80-b6a2-11eb-9274-b6fe14cecd88.png)
Lets try it now (just edited the word infront)

**Comment by steven517** [comment]
https://imgur.com/a/DNIKiuf
putting text on that spot probably wont work very well as its on a curve, maybe move the text to the hood/bonnet.
Also please make the image size 512x512 as that is the max image resolution we accept.

**Comment by MaliciousGirlFriend** [comment]
![Untitled-1](https://user-images.githubusercontent.com/84158178/118414487-1c902580-b6a5-11eb-9c93-715ac351b1c3.png)

**Comment by steven517** [comment]
https://imgur.com/a/wPpBoQp
looks good to me, let me know if its good to go.

**Comment by MaliciousGirlFriend** [comment]
Yep good to go <3

**Comment by steven517** [comment]
wrap is on its way as `malicious_1`

**Comment by steven517** [comment]
Wrap is live
