### ISSUE TITLE
Juanes12 Custom Wrap

### ISSUE THREAD

**Issue by Juanes12a** [saesrpg/donation-vehicle-shaders#286]
**Vehicle ID**  (451) turismo 

**Wrap access** juanes12

**Needs testing** yes

**Thread for reward change** **https://saesrpg.uk/topic/26890/juanes-s-reward-change**

**Translations** N/A 

**Wrap image**
![Juanes1](https://user-images.githubusercontent.com/78461831/119018610-e03d1d80-b961-11eb-8f88-84dec138312b.png)

**Comment by tut98** [comment]
https://imgur.com/a/gUUjUIx

**Comment by Juanes12a** [comment]
Can you test this one please
![juanes_fix1](https://user-images.githubusercontent.com/78461831/119028961-aa059b00-b96d-11eb-87c2-2d4bdd490c4e.png)

**Comment by steven517** [comment]
https://imgur.com/a/v2PHhzf
You didn't flip the text so its still the wrong way

**Comment by steven517** [comment]
https://imgur.com/a/URHPBNL
I've corrected this for you, let me know if its good to go now.

**Comment by steven517** [comment]
wrap is on its way as `juanes12_2`

**Comment by steven517** [comment]
wrap is live
