### ISSUE TITLE
Glendale Wrap For Nulgath (gay)

### ISSUE THREAD

**Issue by MaliciousGirlFriend** [saesrpg/donation-vehicle-shaders#287]
**Vehicle ID**
604

**Wrap access**
Throng0 / malicious

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/26298/reward-change

**Translations**
Nope
**Wrap image**
![Ouch](https://user-images.githubusercontent.com/84158178/119030232-e7881980-b9a9-11eb-9cf1-b51224ac519b.png)

**Comment by steven517** [comment]
https://imgur.com/a/Ok7Hh8l

**Comment by MaliciousGirlFriend** [comment]
Confirmed

**Comment by steven517** [comment]
wrap is on its way as `throng0_2`

**Comment by steven517** [comment]
wrap is live

**Comment by steven517** [comment]
@MaliciousGirlFriend 
We need to have the isreal flag on the trunk/boot of the car removed. We allow people to represent their culture but provoking another is a step too far and just causes unneeded fights.

**Comment by MaliciousGirlFriend** [comment]
![Uploading Ouch.png…]()

**Comment by MaliciousGirlFriend** [comment]
![Ouch](https://user-images.githubusercontent.com/84158178/119182388-1f0ec880-ba73-11eb-881a-d4feba9a1b7d.png)

**Comment by steven517** [comment]
wrap is on its way as `throng0_2`

**Comment by steven517** [comment]
Wrap is live
