### ISSUE TITLE
Alfred's wrap request

### ISSUE THREAD

**Issue by AlfredCripz** [saesrpg/donation-vehicle-shaders#288]
**Vehicle ID**
604
**Wrap access**
ops111

**Needs testing**
nope

**Thread for reward change**
https://saesrpg.uk/topic/26894/alfred-s-reward-change

**Translations**
Milliyetci Hareket Partisi is politicial party at turkey 

**Wrap image**
![image](https://user-images.githubusercontent.com/84539697/119036726-bdd6ee80-b9b9-11eb-9580-fdf0464b0add.png)

**Comment by steven517** [comment]
Wrap is on its way as `ops111_1`
