### ISSUE TITLE
Latino's Custom Wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#289]
**Vehicle ID**598

**Wrap access** carbon12

**Needs testing** Yes

**Thread for reward change** To be edited soon

**Translations** N/A

**Wrap image** 
![policelv1](https://user-images.githubusercontent.com/56209707/119160383-35426780-ba26-11eb-9e86-6cbcd57c9ebb.png)

**Comment by tut98** [comment]
https://imgur.com/a/kQE3uMS
