### ISSUE TITLE
Custom Wrap for Klay

### ISSUE THREAD

**Issue by Klay683** [saesrpg/donation-vehicle-shaders#29]
Vehicle ID: 598 Police LV (GTA5)
Wrap access locked to usernames (leave blank if public): bendhiab
Name for wrap (e.g tutPD): FBI CAR warp
![template1](https://user-images.githubusercontent.com/59097609/71284093-39b2ae80-2362-11ea-9197-d79f3657c69d.png)

**Comment by tutgreco** [comment]
Please correct the text on left side of the car, you need to rotate it 180 degrees else it'll appear incorrectly ingame.

Design note: I recommend you use another font which can be better read especially from longer distances, else it'll look like thin lines 20 meters away.

**Comment by Klay683** [comment]
![CE87B41B-9F08-4775-9EA2-9121B020F103](https://user-images.githubusercontent.com/59097609/71308394-61eeeb80-23fc-11ea-84fe-d9bfe2a6636b.jpeg)

**Comment by SAESKain** [comment]
Ignore tut's wrong tags.

It needs to look like this https://i.imgur.com/X1p9I1B.png cus right now it looks like this https://i.imgur.com/cO5WVyT.png

**Comment by Klay683** [comment]
https://imgur.com/a/mDd3sZL @SAESKain  Updated :)

**Comment by Klay683** [comment]
@SAESKain Updated 
https://imgur.com/a/AEMVEHM
https://imgur.com/a/AEMVEHM

**Comment by tutgreco** [comment]
I've reviewed your wrap, can you please look into the following.

- **995** decal on the boot/trunk needs to be moved a little bit up towards the rear windshield (it's too far rear so the text is partially cut off)
- There are some issues with the sides on the doors, but as i said it's to do with the vehicle, not the wrap. (just a fyi)
- **0995** decal on the right side next to the front right door is slightly cut off. Can you move it further to the right (towards the front of the vehicle).
@Klay683

**Comment by Klay683** [comment]
https://imgur.com/a/xBczzMa
![DB0F3236-F0F8-4DD2-9F6A-CE119AC476B3](https://user-images.githubusercontent.com/59097609/71826392-198f2900-309e-11ea-9678-a6f93bd02315.jpeg)
@tutgreco

**Comment by tutgreco** [comment]
Looks fine. Thanks for your patiency. You'll be notified on the moment it's added.

**Comment by Klay683** [comment]
Finally..... thnx for the service @tutgreco  and @SAESKain <3

**Comment by ZM1707** [comment]
Another one

[https://www.southernhighlandsfirewoodpros.com.au](https://www.southernhighlandsfirewoodpros.com.au
)
[https://www.adelaidewardrobes.com.au](https://www.adelaidewardrobes.com.au)
