### ISSUE TITLE
Latinoo's Custom Wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#290]
**Vehicle ID** 598

**Wrap access** carbon12

**Needs testing** Yes

**Thread for reward change** https://saesrpg.uk/topic/26919/latinoo-s-reward-change/1?_=1621892684707

**Translations** N/A

**Small note** Please re-place this with the other wrap named "carbon12_1"

**Wrap image**
![FOX_1](https://user-images.githubusercontent.com/56209707/119411286-27a41080-bcb8-11eb-98aa-8b37a73c5b32.png)

**Comment by steven517** [comment]
https://imgur.com/a/EfXx4ME

**Comment by Latinoo** [comment]
Could you test this one please 
![Fox2](https://user-images.githubusercontent.com/56209707/119412244-959d0780-bcb9-11eb-9fa7-d546146619fb.png)

**Comment by steven517** [comment]
![image](https://user-images.githubusercontent.com/67033453/119412436-1bfd1d80-bca9-11eb-84d6-3c0b8f6c2165.png)

**Comment by Latinoo** [comment]
Looks good for me can be uploaded thank you for testing

**Comment by steven517** [comment]
Wrap is on its way as `carbon12_1`

**Comment by steven517** [comment]
wrap is live
