### ISSUE TITLE
request to test these wraps.

### ISSUE THREAD

**Issue by jean75002** [saesrpg/donation-vehicle-shaders#291]
**Vehicle ID**
451,480,400 

**Wrap access**
jean75002,Samuel

**Needs testing**
 YES

**Thread for reward change**
N/A

**Translations**
 N?A

**Wrap image**

![template_lamborghini](https://user-images.githubusercontent.com/84804322/119749296-34b63080-be6d-11eb-8dc6-0cad037635a2.png)

![template_comet](https://user-images.githubusercontent.com/84804322/119749303-397ae480-be6d-11eb-9f6e-9264c4e7ec25.png)

![template](https://user-images.githubusercontent.com/84804322/119749312-3ed82f00-be6d-11eb-9807-c8517b17b764.png)

**Comment by steven517** [comment]
Turismo: https://imgur.com/a/HxaPdmS
Comet: https://imgur.com/a/I98AoAH
Landstalker: https://imgur.com/a/9FRqVay
