### ISSUE TITLE
BOPE

### ISSUE THREAD

**Issue by Saesbope** [saesrpg/donation-vehicle-shaders#292]
![template_newsvan](https://user-images.githubusercontent.com/84943189/119980262-7096e600-bf92-11eb-832f-4f1937fb7769.png)
![template_supergt](https://user-images.githubusercontent.com/84943189/119980268-71c81300-bf92-11eb-9b1f-d4302371557e.png)
![template_sultanciv](https://user-images.githubusercontent.com/84943189/119980271-7260a980-bf92-11eb-83ec-ec0d097dcc89.png)
![template_NRG500](https://user-images.githubusercontent.com/84943189/119980274-72f94000-bf92-11eb-8b43-c7c7e5067fa1.png)
![Template_PoliceSultan](https://user-images.githubusercontent.com/84943189/119980277-7391d680-bf92-11eb-9fc3-a67842480c3b.png)
![template_PoliceLV](https://user-images.githubusercontent.com/84943189/119980279-742a6d00-bf92-11eb-8bdf-fbc9facefea2.png)
![template_lamborghini](https://user-images.githubusercontent.com/84943189/119980281-74c30380-bf92-11eb-8eb2-e1d54c41fd0a.png)
![template_glenshit](https://user-images.githubusercontent.com/84943189/119980283-755b9a00-bf92-11eb-8226-a439441db54e.png)
![template_fordcrown](https://user-images.githubusercontent.com/84943189/119980286-75f43080-bf92-11eb-9ac1-de987c43b792.png)
![template_fbi_ranger](https://user-images.githubusercontent.com/84943189/119980289-768cc700-bf92-11eb-944f-7226b0f3121a.png)
![template_enforcer](https://user-images.githubusercontent.com/84943189/119980290-77255d80-bf92-11eb-92d9-137cae17b302.png)
![template_comet](https://user-images.githubusercontent.com/84943189/119980293-77bdf400-bf92-11eb-9d1a-32b126fde86d.png)
![template_Buritto](https://user-images.githubusercontent.com/84943189/119980297-78568a80-bf92-11eb-8374-e2e0ddfc25ab.png)

<! - You can get the ID at https://wiki.multitheftauto.com/wiki/Vehicle_IDs -> 427.451.480.482.490.506.522.560.582.596.597.604

Wrap access
<! - Leave it blank if someone can use the wrap, otherwise, indicate usernames -> Samuel3021

Need test
<! - Indicate 'yes' or 'no' if the wrap needs to be tested or not
NOTE: You can view your wrap on your own server by installing our wrap testing feature: https://github.com/NanoBob/saesrpg-wrap-testing
You can still have your wrap viewed by us, but it should be 10x faster to view for yourself! -> NO

Reward change topic
<! - Link your donation or reward change discussion by requesting this package. If left blank and a test is requested, the test may take a while to process, as you have no donations to claim rewards. -> https://saesrpg.uk/topic/26967/car-exchange

Translations
<! - If the wrapper contains a language that is not readable in English, add translations here, with reference to the part of the vehicle it is painted on. You must show the FOREIGN and ENGLISH version in plain text -> n / a

Wrap image
<! - Attach the file here, do not use third-party image hosts. The file extension must be .PNG using the dimensions 512x512 or 256x256 ->

**Comment by steven517** [comment]
You need to upload the picture of the wrap here

**Comment by tut98** [comment]
Thanks. From top to bottom, your wraps are on their way as `samuel3021_1` to `samuel3021_13`
