### ISSUE TITLE
orten_23

### ISSUE THREAD

**Issue by mag1kSS** [saesrpg/donation-vehicle-shaders#293]
**Vehicle ID**
604

**Wrap access**
moemen12

**Needs testing**
No
**Thread for reward change**
No

**Translations**

**Wrap image**
![Medellin-Cartel-WRAP](https://user-images.githubusercontent.com/84975890/119996748-f3d22f00-bfc6-11eb-9397-ebc49c786acb.png)

**Comment by tut98** [comment]
Wrap's on its way as `moemen12_2`. As per new rules it has been downscaled to 512x512
