### ISSUE TITLE
GM wrap for SAFD

### ISSUE THREAD

**Issue by x-Afufu** [saesrpg/donation-vehicle-shaders#295]
**Vehicle ID** : 407

**Wrap name** : group_safd

**Needs testing**: Yes

**Wrap image**: https://i.imgur.com/9kikxTu.png

**Comment by tut98** [comment]
If you want to, you can test your wrap using the [shader resource here](https://github.com/NanoBob/saesrpg-wrap-testing).
As a side note, please upload the image file here so that it will embed!

**Comment by x-Afufu** [comment]
https://user-images.githubusercontent.com/67375771/122341544-4068b480-cf4c-11eb-8c5c-dba2cad5be76.png

**Comment by x-Afufu** [comment]
Tried testing it, but it does not seem to load in. I think it needs to be tested from your end.

**Comment by tut98** [comment]
https://imgur.com/a/dVsXyQ8

**Comment by x-Afufu** [comment]
Perfect. Thank you.

**Comment by tut98** [comment]
Wrap's on its way as `gang_safd`
