### ISSUE TITLE
Latinoos Custom wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#296]
**Vehicle ID**: 598

**Wrap access**: carbon12

**Needs testing**: Yes

**Thread for reward change**: To be edited soon

**Translations**: N/A

**Wrap image** 
![a7a](https://user-images.githubusercontent.com/56209707/122802454-5ef3e600-d293-11eb-8852-91fbca8877d6.png)

**Comment by tut98** [comment]
I'm afraid this cannot go on a police wrap! Please pick another design or alternatively a different vehicle.

**Comment by Latinoo** [comment]
![POLICE_LV_FOX-1](https://user-images.githubusercontent.com/56209707/123515757-cb416180-d666-11eb-9233-5f1be50e7c7a.png)

**Comment by steven517** [comment]
https://imgur.com/a/lUhEG8D
Passenger side text needs to be flipped

**Comment by Latinoo** [comment]
![Uploading POLICE_LV_FOX.png…]()

**Comment by Latinoo** [comment]
![POLICE_LV_FOX](https://user-images.githubusercontent.com/56209707/123533111-c1f4db00-d6e0-11eb-8aa7-f56869d6e4af.png)

**Comment by steven517** [comment]
looks good https://imgur.com/a/iGakavQ
Wrap is on its way as `carbon12_2`

**Comment by steven517** [comment]
wrap is live
