### ISSUE TITLE
Kok's Custom wrap

### ISSUE THREAD

**Issue by kokwedy** [saesrpg/donation-vehicle-shaders#298]
**Vehicle ID**
604

**Wrap access**
![UE-WRAP23](https://user-images.githubusercontent.com/83719502/124725633-acb85180-df15-11eb-94a0-63735ef5489c.png)

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/post/307124

**Comment by tut98** [comment]
We do not support resolutions of 375x375. Please choose 256x256 or 512x512 🙂

**Comment by Liyones** [comment]
@tut98 this should be fine now

![Uploading Hnet.com-image.png…]()

**Comment by tut98** [comment]
I'm fairly sure this won't need testing as the roof is essentially 1:1 of what you're looking on at the image. If you would still like this tested could you please install our test resource [here](https://github.com/NanoBob/saesrpg-wrap-testing)

**Comment by kokwedy** [comment]
Alright, lets just continue without testing.

**Comment by tut98** [comment]
Wrap's on its way as `kok_2`
