### ISSUE TITLE
MeRo's Custom Wrap

### ISSUE THREAD

**Issue by Xearo0o** [saesrpg/donation-vehicle-shaders#299]
**Vehicle ID** 604

**Wrap access** dragonwarrior

**Needs testing** no

**Thread for reward change** https://saesrpg.uk/topic/27641/mero-s-reward-change

**Translations** N/A

**Wrap image** https://media.discordapp.net/attachments/863072081238294538/863072401323065394/template_glenshit.png

**Comment by Liyones** [comment]
Hello,
Well first of all please edit your request and follow the format which is:

> **Vehicle ID**
> 
> 
> **Wrap access**
> 
> 
> **Needs testing**
> 
> 
> **Thread for reward change**
> 
> 
> **Translations**
> 
> 
> **Wrap image**
> 
> 

Second do not use 3rd party image hosts like imgur or imbb, after you complete your request drag the wrap here under the request.

**Comment by tut98** [comment]
As advised above please upload the file directly to your github post - I can see you edited the file host in your post, but we prefer it directly embedded :)

As far as testing goes I'll be honest that one looks good to me - if you do think it needs testing, you're welcome to test it using the [wrap testing resource here](https://github.com/NanoBob/saesrpg-wrap-testing)

**Comment by Xearo0o** [comment]
ok no need to test it

**Comment by Liyones** [comment]
@Xearo0o i think you didn't understand what Tut told you, let me explain, Don't use any link for the wrap so if you have the wrap in your desktop , drag it from desktop > google > here and wait till it end loading then click on "comment", or you can simply click in this line 
![image](https://user-images.githubusercontent.com/60038193/125202452-8ffc8080-e26b-11eb-9d4e-7f87129c5c73.png)

**Comment by Xearo0o** [comment]
![Uploading template_glenshit.png…]()

**Comment by Xearo0o** [comment]
![template_glenshit](https://user-images.githubusercontent.com/87246804/125202707-7106ea00-e27d-11eb-89a6-3d488f5a809f.png)

**Comment by Xearo0o** [comment]
@tut98 good now?

**Comment by tut98** [comment]
It is, thank you

**Comment by steven517** [comment]
https://imgur.com/a/cUhUuXX

Looks good to me, let me know if you are happy with it @Xearo0o

**Comment by Xearo0o** [comment]
> https://imgur.com/a/cUhUuXX
> 
> Looks good to me, let me know if you are happy with it @Xearo0o

yea thats good

**Comment by steven517** [comment]
wrap is on its way as `dragonwarrior_1`

**Comment by steven517** [comment]
Wrap is live
