### ISSUE TITLE
Custom wrap for Dice

### ISSUE THREAD

**Issue by DiceFBI** [saesrpg/donation-vehicle-shaders#30]
Vehicle ID: Super GT (Shelby GR1)
Wrap access locked to usernames (leave blank if public):
Name for wrap (e.g tutPD): ahegao

Don't judge me, 1312.

![template](https://user-images.githubusercontent.com/59609991/71898445-fc239300-3161-11ea-91be-46d4ce7ad417.png)

**Comment by tutgreco** [comment]
Wrap looks fine. You'll be notified on the date it's added

**Comment by tutgreco** [comment]
@DiceFBI wrap is on our server now.

**Comment by DiceFBI** [comment]
Thanks :)
