### ISSUE TITLE
kiraa's custom wrap

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#300]
Vehicle ID 604

Wrap access:kira12345
Needs testing: yes plz

Thread for reward change: https://saesrpg.uk/topic/27653/kiraa-reward-change?_=1626099569776
Translations N/A

Wrap image
![123-Recovered](https://user-images.githubusercontent.com/81694756/125316318-ec28d880-e32f-11eb-8b90-42d86ff72b19.png)

**Comment by Liyones** [comment]
Please use the correct size 512x512 or 256x256  but i recommend 512x512 for better quality.

**Comment by Liyones** [comment]
I've changed the size (requested by Kiraa)
![125316318-ec28d880-e32f-11eb-8](https://user-images.githubusercontent.com/60038193/125338300-ed65ff80-e347-11eb-9fb8-9bf08b9f3570.png)

**Comment by steven517** [comment]
https://imgur.com/a/yJU93sb

Let me know if its good to go. @KiraaTheHustla

**Comment by KiraaTheHustla** [comment]
> https://imgur.com/a/yJU93sb
> 
> Let me know if its good to go. @KiraaTheHustla

**Comment by KiraaTheHustla** [comment]
looks awesome tysm <3

**Comment by steven517** [comment]
wrap is on its way as `kira12345_1`

**Comment by steven517** [comment]
Wrap is live
