### ISSUE TITLE
Niklaus's custom wrap

### ISSUE THREAD

**Issue by Niklaus-187** [saesrpg/donation-vehicle-shaders#301]
**Vehicle ID**
519

**Wrap access**
xxmrtrollstylexx

**Needs testing**
No, thanks.

**Thread for reward change**
https://saesrpg.uk/topic/27671/niklaus-s-reward-change

**Wrap image**
![Test3](https://user-images.githubusercontent.com/66783522/125517244-bdc9a73d-406f-4d83-af12-81b090998284.png)

**Comment by steven517** [comment]
wrap is on its way as `xxmrtrollstylexx_4`

**Comment by steven517** [comment]
Wrap is live
