### ISSUE TITLE
Ovalles's Custom Wrap

### ISSUE THREAD

**Issue by Ovallees** [saesrpg/donation-vehicle-shaders#303]
**Vehicle ID** 428 (Burrito)

**Wrap access** FelixOvalles12

**Needs testing** yes

**Thread for reward change**  To be edited soon

**Translations** N/A 

**Wrap image**
![unknown](https://user-images.githubusercontent.com/77178639/126406741-16ba8ba3-c911-4225-aa42-9d2b00754000.png)

**Comment by tut98** [comment]
In case you're not aware, wraps can now be tested on your local server by [downloading this resource](https://github.com/NanoBob/saesrpg-wrap-testing).
If you would like us to give you a preview please export the image canvas - a screenshot of the canvas won't work!

**Comment by Ovallees** [comment]
that's how they passed it to me

**Comment by tut98** [comment]
Please ask them to export as png as screenshots aren't compatible.
You could ask if they want to test it themselves as that might give them more creative freedom.

**Comment by Ovallees** [comment]
![](https://i.imgur.com/WzrOL87.png)

**Comment by Ovallees** [comment]
there would be ok?

**Comment by Ovallees** [comment]
There it is

**Comment by Ovallees** [comment]
![](https://i.imgur.com/WzrOL87.png)

**Comment by tut98** [comment]
https://imgur.com/a/Gp6hTk4

**Comment by Ovallees** [comment]
can be pushed live thanks for testing

**Comment by tut98** [comment]
Wraps on its way as `felixovalles12_1`
