### ISSUE TITLE
Cristian's custom wrap

### ISSUE THREAD

**Issue by cristiancscobar** [saesrpg/donation-vehicle-shaders#305]
**Vehicle ID**
604

**Wrap access**
CristianEscobar

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/27787/donation-cristian-amount-15-00-gbp/3?_=1627460066903

**Translations**
n/a

**Wrap image**

![cristianwrap](https://user-images.githubusercontent.com/67033453/127295299-52a29dea-025b-41bb-a5fd-065cea5c2a3d.png)

**Comment by steven517** [comment]
wrap is on its way as `CristianEscobar_1`

**Comment by steven517** [comment]
Wrap is live
