### ISSUE TITLE
kiraa's sgt wrap

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#308]
**Vehicle ID** 506

**Wrap access** kira12345

**Needs testing** yes plz

**Thread for reward change** https://saesrpg.uk/topic/27854/donation-kiraa?_=1627596479769

**Translations** N/A

**Wrap image** 
![template](https://user-images.githubusercontent.com/81694756/127573301-369e3aeb-9d62-4cdf-ba95-3723aa20d4b2.png)

**Comment by steven517** [comment]
https://imgur.com/a/PKMSebG

**Comment by KiraaTheHustla** [comment]
Rlly good

**Comment by KiraaTheHustla** [comment]
can u test this one plz
![Uploading template.png…]()

**Comment by steven517** [comment]
https://imgur.com/a/5xnWUjx

**Comment by KiraaTheHustla** [comment]
the 2nd one plz looks seksi

**Comment by steven517** [comment]
wrap is on its way as `kira12345_2`

**Comment by KiraaTheHustla** [comment]
if it still not in live serveur can i change it with that one plz ?
![sgt pnl](https://user-images.githubusercontent.com/81694756/127777648-5333d621-54a1-4827-b9d8-c833f9d1dfbe.png)

**Comment by tut98** [comment]
> if it still not in live serveur can i change it with that one plz ?
> ![sgt pnl](https://user-images.githubusercontent.com/81694756/127777648-5333d621-54a1-4827-b9d8-c833f9d1dfbe.png)

It's not - please state whether or not you need this tested

**Comment by KiraaTheHustla** [comment]
yes test it plz

**Comment by tut98** [comment]
> yes test it plz

https://imgur.com/a/8XaxGSz

**Comment by steven517** [comment]
looks good now 
![image](https://user-images.githubusercontent.com/67033453/127783313-63a25505-1183-43bf-906d-6e9f070ad9d2.png)
let me know if you are happy with it and ill go ahead and push it.

**Comment by KiraaTheHustla** [comment]
tysm <3 <3<3

**Comment by KiraaTheHustla** [comment]
both cars looks good ty

**Comment by steven517** [comment]
Wrap is on its way as `kira12345_2`

**Comment by steven517** [comment]
wrap is live
