### ISSUE TITLE
Velo's new wrap

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#309]
**Vehicle ID**
549

**Wrap access**
velona77, rizacem

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/27855/donation-velo-amount-15-00-gbp

**Translations**
n/a

**Wrap image**
![marlboro tampa](https://user-images.githubusercontent.com/46403782/127582333-55889373-b4d8-4e48-9a6c-be93b64bfd09.png)

**Comment by steven517** [comment]
wrap is on its way as `velona77_7`

**Comment by steven517** [comment]
Wrap is live
