### ISSUE TITLE
Arma's custom wrap

### ISSUE THREAD

**Issue by Arma3131** [saesrpg/donation-vehicle-shaders#31]
Vehicle ID: 400
Wrap access locked to usernames (leave blank if public): james69 / jaja55
Name for wrap (e.g tutPD): PB-Wrap

https://imgur.com/5vmAGxo

**Comment by tutgreco** [comment]
Please let us know if you're satisfied with this:
https://imgur.com/a/CWoMfT4

**Comment by Arma3131** [comment]
ye i'm :D
