### ISSUE TITLE
New Custom Wraps

### ISSUE THREAD

**Issue by TheMetalizer** [saesrpg/donation-vehicle-shaders#310]
First of all, I'd like to get rid of `rizacem_3` and replace it with this one:

**Vehicle ID**
490
**Wrap access**
rizacem,velona77,zizi31,pekecan
**Needs testing**
No
**Translations**
N/A
**Wrap image**
![fbirancher-poh](https://user-images.githubusercontent.com/48535190/127589055-217e2eba-0087-43fc-9f73-792d8a020815.png)

___

And I'd like to request 2 new shaders as following:

**Vehicle ID**
490
**Wrap access**
rizacem,velona77,zizi31,pekecan
**Needs testing**
No
**Translations**
N/A
**Wrap image**
![fbirancher-pohwhite](https://user-images.githubusercontent.com/48535190/127589133-6f332fc2-9863-4db5-99d8-44136359c575.png)

___

**Vehicle ID**
549
**Wrap access**
rizacem,velona77,zizi31,pekecan
**Needs testing**
No
**Translations**
N/A
**Wrap image**
![tampa-redbull](https://user-images.githubusercontent.com/48535190/127589227-da66617a-194c-479d-b532-d52b87900562.png)

**Thread for the donation**
https://saesrpg.uk/topic/27848/donation-terry-amount-70-00-gbp

**Comment by steven517** [comment]
wraps are on the way as `rizacem_3`(replaced) `rizacem_5` and `rizacem_6` respectively

**Comment by steven517** [comment]
Wraps are live
