### ISSUE TITLE
kiraa's 2nd wrap (turismo)

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#311]
Vehicle ID

451
Wrap access

KIRA12345
Needs testing

Yes
Thread for reward change

https://saesrpg.uk/topic/27865/donation-kiraa-amount-15-00-gbp
N/A
Wrap image

![hsyPV6u](https://user-images.githubusercontent.com/81694756/127754965-57a435c9-8157-4e86-96fc-53b88e3e58e5.png)

**Comment by steven517** [comment]
https://imgur.com/a/e5NnX3U

The "just do it" text needs to be flipped, other than that it looks good.

**Comment by KiraaTheHustla** [comment]
![hsyPV6u (1)](https://user-images.githubusercontent.com/81694756/127774531-8fc76621-0c2b-4376-9c9a-7cec444c53e8.png)

**Comment by steven517** [comment]
Wrap is on its way as `kira12345_3`

**Comment by steven517** [comment]
wrap is live
