### ISSUE TITLE
Custom Wrap M7mDGr7_2

### ISSUE THREAD

**Issue by M7mDGr7** [saesrpg/donation-vehicle-shaders#314]
**Vehicle ID**
604

**Wrap access**
m7mdgr7

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/28145/m7-s-reward-change

**Wrap image**
![The Outfit Custom Wrap](https://user-images.githubusercontent.com/77129717/129613561-a7490fb2-f49a-4f19-b019-140e260f4f54.png)

**Comment by Liyones** [comment]
Hey @M7mDGr7 can you please upload the wrap directly to github, i mean do not use 3rd party image hosts like imgur.

**Comment by M7mDGr7** [comment]
Already done.

**Comment by steven517** [comment]
wrap is on its way as `m7mdgr7_2`

**Comment by steven517** [comment]
Wrap is live
