### ISSUE TITLE
Juanes's Custom Wrap

### ISSUE THREAD

**Issue by Juanes12a** [saesrpg/donation-vehicle-shaders#315]
Vehicle ID 559

Wrap access juanes12

Needs testing No

Thread for reward change https://saesrpg.uk/topic/28229/juanes-s-reward-change

Translations N/A

Wrap image 

![](https://cdn.discordapp.com/attachments/817596651412652073/877967037262090290/Juanes_1.PNG)

**Comment by steven517** [comment]
wrap is on its way as `juanes12_3`

**Comment by steven517** [comment]
wrap is live
