### ISSUE TITLE
elblue's Jester Custom Wrap Request

### ISSUE THREAD

**Issue by xblue1** [saesrpg/donation-vehicle-shaders#316]
**Vehicle ID**: 559

**Wrap access**: talking

**Needs testing**: no

**Thread for reward change**: https://saesrpg.uk/topic/28293/donation-xblue-amount-10-00-gbp

**Translations**: -

**Wrap image**:
![elbluejester1](https://user-images.githubusercontent.com/89312419/130329758-5f2aa472-e8f7-4c3a-89e5-77a23718dd05.png)

**Comment by tut98** [comment]
You may want to remove the black lines as they are photoshop-helpers

**Comment by xblue1** [comment]
Updated

**Comment by steven517** [comment]
wrap is on its way as `talking_1`

**Comment by steven517** [comment]
wrap is live
