### ISSUE TITLE
Latinoos Custom Wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#317]
**Vehicle ID** 559

**Wrap access** carbon12

**Needs testing** No

**Thread for reward change** https://saesrpg.uk/topic/28232/donation-latinoo-amount-20-00-gbp?_=1629658817691

**Translations** N/A

**Wrap image** 
![latinojester](https://user-images.githubusercontent.com/56209707/130366945-3cc958b9-c798-4d06-b926-86da71006f2c.png)

**Comment by steven517** [comment]
wrap is on its way as `carbon12_3`

**Comment by steven517** [comment]
wrap is live
