### ISSUE TITLE
Element's custom warp

### ISSUE THREAD

**Issue by TheRealElement** [saesrpg/donation-vehicle-shaders#32]
Vehicle ID: 598 Police LV (GTA5)
Wrap access locked to usernames (leave blank if public): denis10
Name for wrap (e.g tutPD):SWAT Dodge warp
Warp: https://imgur.com/a/20y4oXc

**Comment by tutgreco** [comment]
Please let us know if you're satisfied with this:
https://imgur.com/a/d7OcHRG

**Comment by TheRealElement** [comment]
A bit buggy, can you test this one please: https://imgur.com/a/XGgySjO

**Comment by tutgreco** [comment]
https://imgur.com/a/jIPmkfV

**Comment by TheRealElement** [comment]
Eh, well close it as for now I'll try to create something else, thanks for helping!
