### ISSUE TITLE
Reggi's custom wrap request

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/donation-vehicle-shaders#320]
**Vehicle ID**

Police LV (598)
Landstalker (400)

**Wrap access**

xr3gg1x
blue35

**Needs testing**

I checked but still check it out if there is any issue or something

**Thread for reward change**

https://saesrpg.uk/topic/28481/donation-reggi-amount-40-00-gbp

**Translations**

n/a

**Wrap image**

![landstalkerbwi](https://user-images.githubusercontent.com/62670831/131272343-a2f7bab0-15be-4584-8994-42fd4155a3cf.png)
![lvcarbwi](https://user-images.githubusercontent.com/62670831/131272371-f15f5b0d-87dc-45be-b99b-7e8d45eed045.png)

**Comment by BlueSAES** [comment]
first one for landstalker, second one is lv police car

**Comment by steven517** [comment]
the landstalker looks good, but you may want to increase the text size on the police lv, we only allowed 512x512 images so the text is pretty unclear
https://imgur.com/a/rKM1uCh

**Comment by steven517** [comment]
wraps are on their way as:
Landstalker = `xr3gg1x_1`
Police LV = `xr3gg1x_2`

**Comment by steven517** [comment]
Wraps are live
