### ISSUE TITLE
Rondaw custom wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#321]
Posting this on behalf of rondaw , requested by him.

**Vehicle ID**
604

**Wrap access**
league1

**Needs testing**
Yes, but i think it looks fine.

**Thread for reward change**

https://saesrpg.uk/topic/28575/donation-rondaw-amount-20-00-gbp?_=1630624176482

**Translations**
N/A

**Wrap image**
![rondaw_glendale2 (1)](https://user-images.githubusercontent.com/60038193/131930344-b97b8003-7a71-4069-86a9-af51f3213191.png)

**Comment by tut98** [comment]
Wraps can be tested at San Fierro carshop's upper floor. Please use this or your local server :)

**Comment by Liyones** [comment]
@tut98 Hello, i don't think this need to be tested, can be added.

**Comment by steven517** [comment]
wrap is on its way as `league1_1`
