### ISSUE TITLE
Weppo Custom Wrap 

### ISSUE THREAD

**Issue by WeppoW** [saesrpg/donation-vehicle-shaders#322]
**Vehicle ID** 582

**Wrap access** ghostpro222, st3v3n517

**Needs testing** no

**Thread for reward change**
https://saesrpg.uk/topic/28666/donation-point-balance-weppo?_=1630949910627

**Translations** -

**Wrap image**
![Weppo1](https://user-images.githubusercontent.com/88065746/132257355-bcc67e33-f321-4d10-879a-1b2bfd2d5ff3.png)

**Comment by steven517** [comment]
wrap is on its way as `ghostpro222_1`

**Comment by steven517** [comment]
Wrap is live
