### ISSUE TITLE
Spanish Custom Wraps Updated 

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#323]
**Vehicle ID:** 416

**Wrap access:** lapd0070

**Needs testing:** No

**Thread for reward change:** https://saesrpg.uk/post/318106

**Comments:** Hello here, I wanted to add two wraps and remove wraps that I don't use, which are in the SAES database.
I need a little help, as I am not 100% sure about the name of the wraps that I want to remove. 

- Wrap: lapd0070_5 can be removed
- Wrap: lapd0070_4 I think it's a 596, if so, it can be removed
- Wrap: lapd0070_7 can be removed

**Wrap images:**

![ambu](https://user-images.githubusercontent.com/72228343/132597632-f258175b-e00b-4c90-aba7-659061aab278.png)

![lsa](https://user-images.githubusercontent.com/72228343/132597642-9469738c-14da-4380-a95c-d95a75d4c6af.png)

**Comment by tut98** [comment]
Removed **lapd0070_5** (416), **lapd0070_7** (400).
Did not remove **lapd0070_4** as it is ID 490 SAM.

Fort carson Ambulance on its way as **lapd0070_1**
Jefferson Ambulance on its way as **lapd0070_3**

Other remaining wraps associated with your account are: lapd0070_2 (490 SAFD), lapd0070_6 (596 SAI), lapd0070_8 (596 BCSO)

**Comment by LAPDSpanishVEN** [comment]
Thanks for the help regarding the wraps removed. You can remove the SAI wrap (lapd0070_6 - 596 SAI) I would really appreciate it.

**Comment by steven517** [comment]
`lapd0070_6` removed
