### ISSUE TITLE
Kree's generic wrap request

### ISSUE THREAD

**Issue by dark41Kree** [saesrpg/donation-vehicle-shaders#324]
Vehicle ID: 559(jester) and 561(stratum)

Wrap access: dark41

Needs testing: No

Thread for reward change:https://saesrpg.uk/topic/28837/kree-s-reward-change

[I want to add this wrap to 2 Stratum's and one Jester]

Generic wrap:
![8n1](https://user-images.githubusercontent.com/90441919/132828826-5d12295f-8a47-417d-829c-66147adf108b.png)

**Comment by Liyones** [comment]
Hello @dark41Kree , Please upload the file directly to Github , do not use 3rd party image hosts like imgur or any other websites. File extension must be .PNG using 512x512 or 256x256 dimensions.

**Comment by tut98** [comment]
Please use the correct issue format for generic wraps 👍 
https://github.com/saesrpg/donation-vehicle-shaders/issues/new/choose
