### ISSUE TITLE
Brother's custom wraps

### ISSUE THREAD

**Issue by Brotherhoodman** [saesrpg/donation-vehicle-shaders#327]
**Vehicle ID**
559

**Wrap access**
brotherhoodman my account name

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/28884/brother-s-reward-change

**Translations**
None

**Wrap image**

![ledsupra2](https://user-images.githubusercontent.com/90584517/133010633-ce746ed4-9d30-42b9-950a-b1901cd6dc77.png)
![r34supra](https://user-images.githubusercontent.com/90584517/133010634-c0a934b9-a233-4cb6-846d-95a3516f6ce8.png)
![brotherrtsupra](https://user-images.githubusercontent.com/90584517/133010636-dc56f248-8b3a-44eb-83be-ea686fc929d8.png)

**Comment by steven517** [comment]
wraps are on their way as:
Green: `brotherhoodman_1`
Blue and grey: `brotherhoodman_2`
Black neon: `brotherhoodman_3`
