### ISSUE TITLE
Laggiaze's custom silvia

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/donation-vehicle-shaders#329]
**Vehicle ID**
436

**Wrap access**
di26key

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/28912/donation-laggiaze-amount-10-00-gbp

**Translations**
N/A

**Wrap image**
![dcsky](https://user-images.githubusercontent.com/49839598/133338661-f9b10404-6478-4a35-ad2c-a1fbe78bcf23.jpg)

**Comment by tut98** [comment]
Wrap's on its way as `di26key_1`
