### ISSUE TITLE
Howlze ~ Donation Wrap

### ISSUE THREAD

**Issue by Howlze** [saesrpg/donation-vehicle-shaders#33]
Vehicle ID: 598 (Police Buffalo)
Wrap access locked to usernames (leave blank if public): howlze, dyam98, hassoni, sparky
Name for wrap (e.g tutPD): howlzeFOX
Wrap: https://cdn.discordapp.com/attachments/597893674571005953/670294351779463168/request.jpg

**Comment by Howlze** [comment]
Making some edits, please wait.

**Comment by DemienD** [comment]
![FOX Shader v2 1](https://user-images.githubusercontent.com/15146566/73119891-3e254500-3f68-11ea-9161-2c1355fbd302.jpg)

Edits done, final version

**Comment by saesrpg** [comment]
Are you sure its 402 and not `copcarvg 598` ?

**Comment by Howlze** [comment]
I blame Dyam, Mr. @saesrpg - and yes, it's the police buffalo

**Comment by tutgreco** [comment]
Wrap looks OK, however the rear bumper stripes and right side stripes didn't match up the right way; this is an issue with the mod and not your shader, so there really isn't much I can recommend doing than keep it as is.

As a side note please only request wraps which fit according to our [wrap rules](https://saesrpg.uk/topic/8309/about-donation-wraps). The one provided is about 3x the scale of our limit (1024x1024) thus by having us downscale it it'll lose a great bunch of quality and even further losses when compressing the wrap. 
Please correct this.

**Comment by Howlze** [comment]
Here is the updated .dds fitting the requirements, @tutgreco: https://cdn.discordapp.com/attachments/616037412304453645/673276153276137492/howlzeFOX.dds
