### ISSUE TITLE
Durby's custom supra

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/donation-vehicle-shaders#330]
**Vehicle ID**
559

**Wrap access**
giris_1

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/28936/donation-durby-amount-20-00-gbp?_=1631830226769>

**Translations**
no

**Wrap image**
![SUPRA-OLAYI](https://user-images.githubusercontent.com/49839598/133692423-2bcf1daf-4b50-409d-8540-91925f54c586.jpg)

**Comment by tut98** [comment]
Wrap's on its way, thanks for providing the name in the issue 👍

**Comment by tut98** [comment]
Renaming the wrap as requested, will be live soon
