### ISSUE TITLE
Laggi's custom silvia rework

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/donation-vehicle-shaders#331]
**Vehicle ID**
436

**Wrap access**
di26key

**Needs testing**
no

**Thread for reward change**
https://saesrpg.uk/topic/28912/donation-laggiaze-amount-10-00-gbp

**Translations**
N/A

**Wrap image**
![dcsilvia](https://user-images.githubusercontent.com/49839598/133708809-5c0e0ae2-343c-4020-97d5-2e41f1e8b03c.jpg)

**Comment by tut98** [comment]
Updated wrap on its way as `di26key_1`
