### ISSUE TITLE
Latinoos custom wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#332]
Vehicle ID: 559

Wrap access: carbon12

Needs testing: No

Thread for reward change:

Translations: N/A

Wrap image 
![template_supra](https://user-images.githubusercontent.com/56209707/133720233-0d370033-3090-496f-b7b2-7471de1cbf2b.jpg)

Please replace this wrap with the one called "carbon12_3" thanks

**Comment by tut98** [comment]
Wrap's on its way, thanks for providing file name
