### ISSUE TITLE
Troyano Custom Wraps

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#333]
**Vehicle 1**

----------

**Vehicle ID:** 490

**Wrap access:** troyano2012

**Needs testing:** No

**Thread for reward change:** https://saesrpg.uk/post/318952

**Wrap image:**

![template_fbiRancher](https://user-images.githubusercontent.com/72228343/133820330-dc675758-431b-4248-bbd4-4264989c39d2.png)

-----

**Vehicle 2**

-----

**Vehicle ID:** 598

**Wrap access:** troyano2012

**Needs testing:** No

**Thread for reward change:** https://saesrpg.uk/post/318952

**Wrap image:** 

![template_policeLV](https://user-images.githubusercontent.com/72228343/133820413-de353665-0612-4eae-8110-6417be7aabdd.png)

**Comment by tut98** [comment]
First one is ok, but second one lacks a 'y' in 'military' to keep it readable in English

**Comment by LAPDSpanishVEN** [comment]
Wrap fixed

![template_policeLV](https://user-images.githubusercontent.com/72228343/133865561-babd7adc-47d5-4316-bb8b-9464504e3602.png)

**Comment by tut98** [comment]
2nd on its way as `troyano2012_2`
