### ISSUE TITLE
Spanish Custom Wrap #9

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#335]
**Vehicle ID:** 416

**Wrap access:** lapd0070

**Needs testing:** No

**Thread for reward change:** https://saesrpg.uk/post/319449

**Wrap image:**

![wrap1](https://user-images.githubusercontent.com/72228343/133881161-31f3291d-9cc4-44e9-b279-9541a570da14.png)

**Comment by tut98** [comment]
Wrap's on its way as `lapd0070_5`

**Comment by LAPDSpanishVEN** [comment]
Sorry for the inconvenience. The lapd0070_5 wrap is already in use. This wrap was not added to the server. Could it be added to the server again with another name?

**Comment by tut98** [comment]
There's currently only one instance of `lapd0070_5` on the server. These are the wraps you currently have:
![alt text](https://i.imgur.com/fpRdiUa.png)

**Comment by LAPDSpanishVEN** [comment]
Maybe it was a problem with the admin, he said that it was not in the database, I will try to contact another admin in-game to check this again, I will keep this topic open until an admin sort the donation or retifies the status of the wrap, i will keep you updated about this.

**Comment by tut98** [comment]
Try again

**Comment by LAPDSpanishVEN** [comment]
The wrap was added by another administrator, apparently it was a panel error. Works now

Thanks for your time and sorry for the inconvenience.
