### ISSUE TITLE
Halo Custom Wrap Change

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#338]
**Vehicle ID** 559

**Wrap access:** buch

**Needs testing:** No

**Thread for reward change:** https://saesrpg.uk/post/320968

**Wrap image:**

![supra](https://user-images.githubusercontent.com/72228343/135704443-21dec252-0389-449e-b95e-8960c91d7156.png)

**Comment by steven517** [comment]
wrap is on its way as `buch_11`

**Comment by steven517** [comment]
wrap is live
