### ISSUE TITLE
JoNa/halo's custom warp

### ISSUE THREAD

**Issue by jonathan959** [saesrpg/donation-vehicle-shaders#34]
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): buch / jonathan959 / zoomspeed
Name for wrap (e.g tutPD): SAFP-warp
https://imgur.com/a/Wum0q2y

**Comment by tutgreco** [comment]
I have reviewed your design. Notes:

Right side: "Federal" on doors is slightly cut off from the left, the F can only be half seen.
Rear bumper: "Federal police" is distorted, can you please move it a small bit down as shown below
https://cdn.discordapp.com/attachments/308956559201796097/676179911169409054/unknown.png

@jonathan959

**Comment by jonathan959** [comment]
Can u send me a full ss of the car please? It would help a lot

**Comment by tutgreco** [comment]
See album: https://imgur.com/a/Ldnzvyd

**Comment by jonathan959** [comment]
hey! thank u very much for those pics, it has been moved down and it's smaller now, also can u make the car's color SAFP blue instead of black? I believe this is the RGB code #004B98
https://imgur.com/a/sGGjKpM

**Comment by tutgreco** [comment]
It appears that way by default, there's currently no way to change it. It's just the world reflecting onto the vehicle.

I have edited the rear bumper text to fit right on. If you're happy with that, let us know and we'll push it to live server.
https://i.imgur.com/KloMbgx.png

**Comment by jonathan959** [comment]
Yeah its better now, u can put it live whenever ur free 👌👌

**Comment by tutgreco** [comment]
Okay, expect it soon!
**SAFP-wrap**
(was written as "warp" on your issue, but I realise it was a typo)

**Comment by jonathan959** [comment]
I didnt realize, its ok with me and u think it can be today? And if not can u inform me when its live please

**Comment by tutgreco** [comment]
I cannot inform you of the date. The issue will be closed at release date.

**Comment by jonathan959** [comment]
hey! I haven't heard about the shader almost for a week, any news on the shader?

**Comment by tutgreco** [comment]
I'm afraid not.
