### ISSUE TITLE
Cargobob custom wrap [TEST]

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#343]
**Vehicle ID**
548

**Needs testing**
Yes, can you please test it for me, the cargobob wrap doesn't work ingame for some reason.

**Wrap image**
![template_cargobob](https://user-images.githubusercontent.com/60038193/138240251-be684d23-76ed-411d-865e-362996d58a99.png)

**Comment by tut98** [comment]
There's a new release for the wraps resource [here](https://github.com/NanoBob/saesrpg-wrap-testing/releases/tag/1.0.3)
