### ISSUE TITLE
GOES Custom wrap

### ISSUE THREAD

**Issue by fandimo** [saesrpg/donation-vehicle-shaders#348]
**Vehicle ID**
427

**Wrap access**
Fandi123

**Needs testing**
No

**Thread for reward change**
https://saesrpg.uk/topic/29593/donation-fandi-amount-10-00-gbp

**Translations**
N/A

**Wrap image**
![template_enforcer](https://user-images.githubusercontent.com/93490560/139599174-3b88025a-b048-4fa8-a1fd-5e8fd63bf5a5.png)

**Comment by steven517** [comment]
wrap is on its way as `fandi123_1`

**Comment by steven517** [comment]
wrap is live
