### ISSUE TITLE
Youssef's Costume warp

### ISSUE THREAD

**Issue by youssef-bb** [saesrpg/donation-vehicle-shaders#349]
Vehicle ID
402

Wrap access
settthboss

Needs testing
Tested , No thanks

Thread for reward change
https://saesrpg.uk/topic/29594/youssef-s-reward-change

Translations
N/A

Wrap image
![template](https://user-images.githubusercontent.com/93038475/139601637-ed8eecd1-648b-46bc-ac00-2930b3917eef.png)

**Comment by steven517** [comment]
wrap is on its way as `settthboss_1`

**Comment by steven517** [comment]
wrap is live
