### ISSUE TITLE
Klay Costum Warp #2

### ISSUE THREAD

**Issue by Klay683** [saesrpg/donation-vehicle-shaders#35]
Vehicle ID:598
Wrap access locked to usernames (leave blank if public): bendhiab
Name for wrap (e.g tutPD): Klay police car warp 
https://imgur.com/a/5xvCoOI
https://imgur.com/a/5xvCoOI

**Comment by tutgreco** [comment]
I have added a background to it and upscaled to 512x512 but besides that, wrap is approved and is on its way.

**Comment by Klay683** [comment]
@tutgreco
