### ISSUE TITLE
Brothers custom wrap #2

### ISSUE THREAD

**Issue by Brotherhoodman** [saesrpg/donation-vehicle-shaders#350]
Vehicle ID
559

Wrap access
brotherhoodman my account name

Needs testing
No

Thread for reward change
https://saesrpg.uk/topic/29675/brothers-reward-change

Translations
None

Wrap image
![template_supra-1](https://user-images.githubusercontent.com/90584517/140659056-e2f64234-9b4a-44c3-8673-ad3ff68cadea.png)
![template_supra-Recovered](https://user-images.githubusercontent.com/90584517/140659059-d618b55a-f906-4b67-9015-2fb20d68ad0d.png)

**Comment by steven517** [comment]
Wraps on their way
Yellow wrap: `brotherhoodman_4`
Blue wrap: `brotherhoodman_5`

**Comment by steven517** [comment]
wraps are live
