### ISSUE TITLE
Youssef's custom Warp

### ISSUE THREAD

**Issue by youssef-bb** [saesrpg/donation-vehicle-shaders#352]
**Vehicle ID**
604

**Wrap access**
setttheboss

**Thread for reward change**
https://saesrpg.uk/topic/29849/youssef-s-rewards-change

**Translations**
N/A

**Wrap image**

![BB](https://user-images.githubusercontent.com/93038475/142020285-e79a6032-c8ce-4525-90a2-8b8986f72c79.png)

**Comment by tut98** [comment]
Please rescale image dimensions as 512x512

**Comment by youssef-bb** [comment]
@tut98 i tried many times but i can't can u tell me how to do that ?

**Comment by tut98** [comment]
In some applications it's under Image tab -> Image size.
I can resize it myself but you'll have to expect worse quality, so it may be ideal to re-test it after downscaling if you want to be sure.

**Comment by youssef-bb** [comment]
will i edit it after all ty here it is 
![Warp](https://cdn.discordapp.com/attachments/903244350367096842/910499739282321438/template_glenshit12.png)

**Comment by tut98** [comment]
It's ok. Wrap's on its way as `setttheboss_2`
