### ISSUE TITLE
Latinoos Custom Wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#353]
**Vehicle ID** 559

**Wrap access** carbon12

**Thread for reward change** -

**Translations** -

**Wrap image** 
![template_supra-1_Edited](https://user-images.githubusercontent.com/56209707/142300530-f6e59cd5-8731-4a5a-b03f-b1b593bca0bf.png)

Could you also delete every wrap is uploaded in the server that are mine? Except the "carbon12_3" thanks 👍

**Comment by tut98** [comment]
Wrap's on its way replacing `carbon12_1`
The wrap `carbon12_2` has been removed.
