### ISSUE TITLE
Reeyzee's Custom Warp

### ISSUE THREAD

**Issue by Reeyzee** [saesrpg/donation-vehicle-shaders#354]
**Vehicle ID**
559

**Wrap access**
clash1

Thread for reward change
https://saesrpg.uk/topic/29010/donation-point-balance-reeyzee

**Wrap image**
![Reeyzee](https://user-images.githubusercontent.com/95066420/143587217-95fa963a-f698-4287-8031-b0e023143771.png)

**Comment by tut98** [comment]
Wrap is on its way as `clash1_1`

**Comment by steven517** [comment]
Live
