### ISSUE TITLE
Spanish Custom Wrap 

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#355]
**Vehicle ID:** 497

**Wrap access:** lapd0070

**Thread for reward change:** https://saesrpg.uk/post/328348

**Wrap image**
![SAMHELI](https://user-images.githubusercontent.com/72228343/144646628-86088169-6f5d-4f7f-9039-496cf5b68b80.png)

**Comment by tut98** [comment]
Wrap's on its way as `lapd0070_6`

**Comment by steven517** [comment]
live
