### ISSUE TITLE
costum wrap

### ISSUE THREAD

**Issue by mag1kSS** [saesrpg/donation-vehicle-shaders#357]
Vehicle ID
519

Wrap access
mag1ks

Thread for donation 
https://saesrpg.uk/topic/30048/donation-undefined-amount-10-00-gbp/2
![107715065-8502eb80-6cdf-11eb-84d2-bf1b4cc77f81](https://user-images.githubusercontent.com/84975890/144765052-c8237d18-a82d-40d2-879d-a483c95fa5d4.png)

**Comment by tut98** [comment]
Wrap's on its way as `mag1ks_1`

**Comment by WenDo21** [comment]
Hola, 

As you can see in the link below, that's my custom wrap. I do not want to share it with you nor with anyone else.

( link to my wrap request back in March https://github.com/saesrpg/donation-vehicle-shaders/issues/228 )

I want the wrap to get removed asap.

Thanks in advance!

**Comment by steven517** [comment]
> Hola,
> 
> As you can see in the link below, that's my custom wrap. I do not want to share it with you nor with anyone else.
> 
> ( link to my wrap request back in March #228 )
> 
> I want the wrap to get removed asap.
> 
> Thanks in advance!

the wrap has been changed

**Comment by Dizzyyyyyy** [comment]
Hello, this wrap belongs to me and I do not want you to use it, thanks. (https://github.com/saesrpg/donation-vehicle-shaders/issues/211)

**Comment by tut98** [comment]
Reverting and closing this issue.

If you want to use a wrap that already exists ingame, contact the owner for permission and have an admin sort the wrap for you 👍
