### ISSUE TITLE
ugabuga Custom Wrap

### ISSUE THREAD

**Issue by UGABUGA24** [saesrpg/donation-vehicle-shaders#359]
**Vehicle ID**

559 Jester
**Wrap access**

(ugabuga)
**Thread for reward change**

https://saesrpg.uk/topic/30049/donation-undefined-amount-20-00-gbp?_=1638736103887
**Translations**

**Wrap image**

https://i.imgur.com/W0T8vkC.pn
![W0T8vkC](https://user-images.githubusercontent.com/95589708/144764733-dd41c725-2b3e-4f66-99b5-f4dede019f72.png)
g

**Comment by steven517** [comment]
wrap is on its way as `ugabuga_1` you will be notified when the wrap is live.

**Comment by steven517** [comment]
Live
