### ISSUE TITLE
Custom wrap request

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#36]
Vehicle ID: 598 Police LV (GTA5)
Wrap access locked to usernames (leave blank if public): bardo45 (me)
Name for wrap (e.g tutPD): HellcatPolice
https://i.imgur.com/s8S9cM9.png
-link updated with a small tweak (tut)

**Comment by tutgreco** [comment]
In accordance with the new naming convention used for wraps we've renamed your wrap(s) to:
bardo45_1
