### ISSUE TITLE
Spanish Custom Wrap 

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#360]
**Vehicle ID:** 416

**Wrap access:** lapd0070

**Thread for reward change:** https://saesrpg.uk/post/328650

**Wrap image**
![SAFD Ambu](https://user-images.githubusercontent.com/72228343/144916299-9f6dd3df-31eb-4223-8678-16dfb260a850.png)

**Comment by steven517** [comment]
sorry for the delay, didn't notice this was here 
wrap is on its way as `lapd0070_7` :)

**Comment by steven517** [comment]
Live
