### ISSUE TITLE
Minex's Custom Wrap Request

### ISSUE THREAD

**Issue by mubeen55** [saesrpg/donation-vehicle-shaders#361]
**Vehicle ID**
519

**Wrap access**
mubeen

**Donation Thread**
https://saesrpg.uk/topic/30170/donation-minexdovahkin-amount-10-00-gbp

**Wrap image**
![remap](https://user-images.githubusercontent.com/96307070/146579164-d9c3d224-0303-48da-a804-e96c95d5603a.png)

**Needs Testing**
No

**Comment by tut98** [comment]
Added as `mubeen_1`
