### ISSUE TITLE
Kaizokuu

### ISSUE THREAD

**Issue by Kaizooku** [saesrpg/donation-vehicle-shaders#362]
**Vehicle ID**
559

**Wrap access**
Kaizokuu and dousuca

**Thread for reward change**
https://saesrpg.uk/topic/30281/donation-undefined-amount-10-00-gbp

**Translations**
/

**Wrap image**

![template_supra_11](https://user-images.githubusercontent.com/96664982/147392545-a86aad48-5ca8-482e-8d0e-681d26bb1f05.png)

**Comment by tut98** [comment]
Added as `kaizokuu_1`
(please take note of it being lowercase)
