### ISSUE TITLE
PaiN'S custom wrap request

### ISSUE THREAD

**Issue by PaiN500** [saesrpg/donation-vehicle-shaders#363]
**Vehicle ID:** 604

**Wrap access:** siyar210, hessan210

**Thread for reward change:** https://saesrpg.uk/topic/30207/donation-undefined-amount-30-00-gbp/3?_=1640011243430

**Translations:** -

**Wrap image:** https://i.imgur.com/gTW1N8e.png

**Comment by tut98** [comment]
Which username is the owner of this wrap?

**Comment by PaiN500** [comment]
siyar210

**Comment by tut98** [comment]
Added as `siyar210_1`
