### ISSUE TITLE
Kodigo's costume wrap

### ISSUE THREAD

**Issue by kodigo21** [saesrpg/donation-vehicle-shaders#366]
**Vehicle ID**

561
**Wrap access**

**Thread for reward change**

https://saesrpg.uk/topic/30339/donation-undefined-amount-10-00-gbp?_=1640891542317

**Translations**

el jefe = the boss

**Wrap image**

![template_glenshit](https://user-images.githubusercontent.com/96799401/147781796-09621b29-e1ca-4b8f-a12d-902ae42a0ae5.png)

**Comment by tut98** [comment]
Wrap's on its way as `eduuh96_2`

**Comment by steven517** [comment]
live
