### ISSUE TITLE
xBlue's custom wrap request

### ISSUE THREAD

**Issue by xblue1** [saesrpg/donation-vehicle-shaders#367]
**Vehicle ID**
519

**Wrap access**
talking

**Thread for reward change**
https://saesrpg.uk/topic/30361/donation-undefined-amount-50-00-gbp

**Translations**

**Wrap image**
![xblueshamalwrap](https://user-images.githubusercontent.com/89312419/147862884-90923442-2a00-4e25-9632-a90ffb1dd96f.png)

**Comment by Latinoo** [comment]
.

**Comment by steven517** [comment]
wrap is on its way as ```talking_2```

**Comment by steven517** [comment]
Live
