### ISSUE TITLE
Sanfara's custom wrap request

### ISSUE THREAD

**Issue by Sanfara44** [saesrpg/donation-vehicle-shaders#368]
**Vehicle ID**559

**Wrap access** midoprock

**Thread for reward change**
https://saesrpg.uk/topic/30383/sanfara-s-reward-change

**Translations** N/A

**Wrap image**
![20220104_152150](https://user-images.githubusercontent.com/68815648/148204213-627edc64-1533-4e60-b7e1-2dc71dc0c393.png)

**Comment by tut98** [comment]
Please use the correct image dimensions (256x256 or 512x512) and embed the image in your issue

**Comment by Sanfara44** [comment]
> Please use the correct image dimensions (256x256 or 512x512) and embed the image in your issue

Done, I hope everything is good now.

**Comment by tut98** [comment]
Added as `midoprock_1`
