### ISSUE TITLE
Mystic's Wrap Request

### ISSUE THREAD

**Issue by Mystic404** [saesrpg/donation-vehicle-shaders#369]
**Vehicle ID**
559 - Jester

**Wrap access**
bonobos19

**Thread for reward change**
https://saesrpg.uk/topic/30478/donation-undefined-amount-10-00-gbp

**Translations**

**Wrap image**

![mystic1j](https://user-images.githubusercontent.com/97537695/148973832-b14fd4ac-0d2a-4395-83fe-018cc670eeef.png)

**Comment by steven517** [comment]
live
