### ISSUE TITLE
Custom wrap request Sollozzo

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#37]
Vehicle ID: 598 Police LV (GTA5)
Wrap access locked to usernames (leave blank if public): sollozzo (me)
Name for wrap : PoliceNationaleLV
[https://i.imgur.com/zsIlt4h.png](url)

UPDATE : https://i.imgur.com/HAb23iU.png

**Comment by tutgreco** [comment]
Wrap looks ok, but the rear license plate has to go. Not only is it not within the boundaries of the plate, but the vehicle also has its own plate which will hide the text on your wrap. 
The shadow layer also needs to be deleted. It mostly serves as a reference for where the vehicle creaks and edges are; doesn't look good with it on. The game engine also provides lighting for the vehicle, so it won't look completely flat even if the wrap is 100% white with decals.

**Comment by SOLLOZZO-SAES** [comment]
There is it, update meets your expectations :
https://i.imgur.com/HAb23iU.png

**Comment by SOLLOZZO-SAES** [comment]
Can we test the texture on the vehicle to see if it fits good ?
Thanks

**Comment by tutgreco** [comment]
I have tested it when I replied to you saying it looks fine. After the wrap is added to the server, you can at any time re-open this issue and submit a change to the wrap.

**Comment by tutgreco** [comment]
In accordance with the new naming convention used for wraps we've renamed your wrap(s) to:
sollozzo_1

**Comment by SOLLOZZO-SAES** [comment]
Hello Tutgreco, thanks for uploading the shader, but the left side of the car is not symmetrical to the right side. Can we try this file before a possible edition? Thank you

Image : https://i.imgur.com/fPJM9Va.png

**Comment by tutgreco** [comment]
It's correct it indeed is not symmetrical. This is a technical issue with the vehicle. Neither of your wraps fixes it and I'm sorry to say it won't be fixed that easily and I'm afraid it'll waste our time for what it's worth. Therefore I'm closing your request.

**Comment by SOLLOZZO-SAES** [comment]
I changed the texture because the left part was higher than the right part so this comes from my error, so that it could meet my expectations.  I would like to donate more to have multiple vehicles with the same texture so I think it can save time for the future

**Comment by SOLLOZZO-SAES** [comment]
Thanks sir, I did not question the mechanics of the image but my error on a slight elevation of the strip on the left which causes deformation on the vehicle.  Thank you very much for this update. See you soon.
