### ISSUE TITLE
LandShark's Custom Wrap Request

### ISSUE THREAD

**Issue by SAFP-LandShark** [saesrpg/donation-vehicle-shaders#370]
**Vehicle ID** 559

**Wrap access** landsharkppppp

**Thread for reward change** https://saesrpg.uk/topic/30490/landshark-s-reward-change

**Translations** Everything is English on the wrap.

**Wrap image** ![landsharkjesterwrap](https://user-images.githubusercontent.com/97612417/149167539-f630289d-4894-4f83-88d1-9dcaad9ab155.png)

**Comment by tut98** [comment]
Added as `landsharkppppp_1`
