### ISSUE TITLE
Nevs Custom Wrap Request

### ISSUE THREAD

**Issue by KingNevs** [saesrpg/donation-vehicle-shaders#371]
**Vehicle ID**
559 (Jester)

**Wrap access**
svennivenni

**Thread for reward change**
https://saesrpg.uk/topic/30511/nevs-reward-change?_=1642030723454

**Translation**
No text except from my ingame name: Nevs.

**Wrap image**
![RACER NEVS](https://user-images.githubusercontent.com/81906735/149247055-2cd34386-c8d4-4b29-827a-af1be7092873.png)

**Comment by steven517** [comment]
wrap is on its way as `svennivenni_1` you will be notified here when it is live.

**Comment by steven517** [comment]
live
