### ISSUE TITLE
Wrap request Stratum

### ISSUE THREAD

**Issue by Ekkohama** [saesrpg/donation-vehicle-shaders#372]
**#warp1**
**Vehicle ID**
561

**Wrap access**
**hamataher**

**Wrap image**
https://imgur.com/7bC6BaD

**Comment by tut98** [comment]
Please embed the image on Github, and make sure to upload the image with correct image dimensions (512x512)

**Comment by Ekkohama** [comment]
Vehicle ID
561

Wrap access
hamataher

Wrap image
![ekkoo_AudiRs7](https://user-images.githubusercontent.com/88112715/150024955-3ba4e1b0-630c-495d-bd68-d64d4840ae23.png)

**Comment by steven517** [comment]
wrap is on its way as `hamataher_1` you will be notified here when it is live

**Comment by steven517** [comment]
wrap is live
