### ISSUE TITLE
Staylok Wrap Request

### ISSUE THREAD

**Issue by staylok453** [saesrpg/donation-vehicle-shaders#373]
Vehicle ID 559 (Jester)

Wrap access staylok

Thread for reward change https://saesrpg.uk/topic/30634/staylok-reward-change
(No need for testing)

  
![staylokRTsupra](https://user-images.githubusercontent.com/98068709/150262923-bebe5789-8990-4fd1-9064-e8f9e7ebd521.png)

Translations Everything is English on the wrap.

**Comment by steven517** [comment]
wrap is on its way as `staylok_1` you will be notified here when it is live

**Comment by steven517** [comment]
wrap is live
