### ISSUE TITLE
kiraa wrap's

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#374]
**Vehicle ID** 604 / 411

**Wrap access** kira12345

**Thread for reward change**  https://saesrpg.uk/topic/30700/kiraa-reward-change?_=1643027243064

**Translations** N/A

**Wrap image** 
![gTW1N8e](https://user-images.githubusercontent.com/81694756/150832756-f06eec3f-4ef6-4073-90bf-86950189ea02.png)

![150832756-f06eec3f-4ef6-4073-90bf-86950189ea02](https://user-images.githubusercontent.com/81694756/151464377-86cc628d-0e7c-49d8-ad18-db16db17523a.png)

**Comment by steven517** [comment]
Wraps on their way as `kira12345_5` and `kira12345_6`

**Comment by steven517** [comment]
I live your wrap bro https://discord.com/channels/229936715383439361/701751955797573652/936329255493718066
