### ISSUE TITLE
Acez Custom Wrap Request

### ISSUE THREAD

**Issue by aczdne** [saesrpg/donation-vehicle-shaders#375]
**Vehicle ID** 506

**Wrap access** theclub

**Thread for reward change** https://saesrpg.uk/topic/30712/acez-s-reward-change

**Translations** -

**Wrap image** 

![template](https://user-images.githubusercontent.com/98418317/151032393-a1b5df29-497f-4e15-9f13-6815a67b963f.png)

**Comment by steven517** [comment]
wrap is on its way as `theclub_1`

**Comment by steven517** [comment]
wrap is live

**Comment by aczdne** [comment]
thanks^^
