### ISSUE TITLE
Brother's custom wraps #3

### ISSUE THREAD

**Issue by Brotherhoodman** [saesrpg/donation-vehicle-shaders#378]
Vehicle ID
411

Wrap access
brotherhoodman my account name

Needs testing
No

Thread for reward change
https://saesrpg.uk/topic/30823/brother-reward-change-04-02-2022

Translations
None

Wrap image
![Infernus_brother_2](https://user-images.githubusercontent.com/90584517/152597407-deff53e4-b650-4749-b057-7d78551657c9.png)
![infernus_brother_3](https://user-images.githubusercontent.com/90584517/152597410-8828e58d-1d95-4570-ad02-740329dd1c26.png)
![infernus_brother1](https://user-images.githubusercontent.com/90584517/152597412-27a39cde-e698-4759-8ccf-659a61c9e8a8.png)

**Comment by steven517** [comment]
Wraps are on their was as `brotherhoodman_1`(blue/lightning) `brotherhoodman_2`(blue/orange) `brotherhoodman_3`(lines)

**Comment by steven517** [comment]
wraps are live
