### ISSUE TITLE
SlapBobs's Custom Wrap

### ISSUE THREAD

**Issue by SlapBobs** [saesrpg/donation-vehicle-shaders#379]
Vehicle ID
598

Wrap access
serkan1106

Thread for reward change
https://saesrpg.uk/topic/30856/slapbobs-s-reward-change/1

Doesn't need testing

![template](https://user-images.githubusercontent.com/99148964/152705855-c0325488-7f1a-4a20-b3ed-5ad00144aba7.png)

**Comment by steven517** [comment]
Police vehicle wraps must be realistic, this is not realistic at all. Please refer to this topic for emergency vehicle shadering rules: https://saesrpg.uk/topic/10859/donation-emergency-vehicles-shaders , request denied

**Comment by SlapBobs** [comment]
Updated
