### ISSUE TITLE
Custom wraps request | CAMELS IN DA HOUSE

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/donation-vehicle-shaders#38]
Hey ! I would like to get 4 custom wraps : https://saesrpg.uk/topic/16231/donation-matizz-amount-20-00-gbp ! 

1 - Vehicle ID: SuperGT (506)
Wrap access locked to username: matizz
Name for wrap: camels1
PNG: https://i.imgur.com/7OjyKlR.png

2 - Vehicle ID: Landstalker (400)
Wrap access locked to username: matizz
Name for wrap: camels2
PNG: https://i.imgur.com/5gobDY0.png

3 - Vehicle ID: Sultan (560)
Wrap access locked to username: matizz
Name for wrap: camels3
PNG: https://i.imgur.com/j0AWRFW.png 

4 - Vehicle ID: Burrito (482)
Wrap access locked to username: matizz
Name for wrap: camels4
PNG: https://i.imgur.com/AjjeEEl.png

Thanks !

**Comment by tutgreco** [comment]
ID 506: you've moved the template down vertically, please undo the placement changes according to template.
ID 400: everything looks fine with the exception of the rear being a little questionable: https://imgur.com/a/p1BT1Cd
ID 560: mirror the top text (hood, roof)
ID 482: looks fine

**Comment by iMatizZ** [comment]
@tutgreco fixed : 
SuperGT (506) : https://i.imgur.com/9EGiWC8.png
Landstalker (400) : https://i.imgur.com/R12CaBb.png 
Sultan (560) : https://i.imgur.com/rWtCzlF.png

**Comment by tutgreco** [comment]
ID 560 fix: https://imgur.com/a/HCBxpXQ

Things look acceptable and the wraps are on their way

**Comment by tutgreco** [comment]
In accordance with the new naming convention used for wraps we've renamed your wrap(s) to:
matizz_1
matizz_2
matizz_3
matizz_4
