### ISSUE TITLE
PinkyyyTinkyyys request

### ISSUE THREAD

**Issue by PinkyyyTinkyyy** [saesrpg/donation-vehicle-shaders#380]
**Name for wrap**
Pinkyyy1
Generic Wrap For Turismo 451
Tested in sf car shop
![pinkyyyrainbowhearts](https://user-images.githubusercontent.com/66016253/152712872-155392ac-02e2-4a89-b6f7-c335c4fcc9a8.jpg)

Thank you <3

**Comment by steven517** [comment]
wrap is on its way as `neonhearts`

**Comment by PinkyyyTinkyyy** [comment]
Thanks!
