### ISSUE TITLE
Aoxy's Custom Wrap Request

### ISSUE THREAD

**Issue by aoxi35** [saesrpg/donation-vehicle-shaders#381]
**Vehicle ID**
411

**Wrap access**
Aox1640S shiroi36

**Thread for reward change**
https://saesrpg.uk/topic/30858/aoxy-s-reward-change

**Translations**
N/A

**Wrap image**
![aoxyinfernus1](https://user-images.githubusercontent.com/89259380/152796315-7a66ed11-2f0d-4657-9d6d-a00bc702496f.png)

**Comment by steven517** [comment]
wrap is on its way as `aox1640s_1`

**Comment by steven517** [comment]
wrap is live
