### ISSUE TITLE
Evans's Custom Wrap Request 

### ISSUE THREAD

**Issue by Evans1971** [saesrpg/donation-vehicle-shaders#382]
**Vehicle ID**

519
**Wrap access**

As1414140
**Thread for reward change**

https://saesrpg.uk/topic/30860/evans-s-reward-change
**Translations**

**Wrap image**
Needs Testing: No

![remap](https://user-images.githubusercontent.com/90685449/152806968-7b2004e9-da6b-424a-9c9b-119d2cd9a165.png)

**Comment by steven517** [comment]
do you want this to be a generic wrap for everybody to use? or a custom wrap for yourself?

**Comment by steven517** [comment]
wrap is on its way as `as1414140_1`

**Comment by steven517** [comment]
wrap is live
