### ISSUE TITLE
Latinos Custom Wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#384]
**Vehicle ID** 411 559

**Wrap access** carbon12

**Thread for reward change** https://saesrpg.uk/topic/30266/donation-undefined-amount-10-00-gbp

**Translations** -

**Needs testing:** No

**Wrap image**
![remap3](https://user-images.githubusercontent.com/56209707/153089284-fa2528ea-976d-44cd-b109-c267ad53e35c.png)
![remap](https://user-images.githubusercontent.com/56209707/153089290-351ef7eb-e8a0-435f-b539-8f2ce7de14f8.png)
![remap2](https://user-images.githubusercontent.com/56209707/153089291-d1c258ac-81c6-4bda-b91f-a5aae43f5ded.png)

**Comment by steven517** [comment]
wraps on their way as `carbon12_2`(pink jester), `carbon12_4`(yellow), `carbon12_5`(white and black)

**Comment by steven517** [comment]
wraps are live
