### ISSUE TITLE
SlapBobs Custom Wrap

### ISSUE THREAD

**Issue by SlapBobs** [saesrpg/donation-vehicle-shaders#385]
Vehicle ID
598

Wrap access
serkan1106

Thread for reward change
https://saesrpg.uk/topic/30856/slapbobs-s-reward-change/1

Doesn't need testing

![template](https://user-images.githubusercontent.com/99148964/153089341-76bd0c4e-c571-4612-ae47-84998ceb9fe7.jpg)

**Comment by steven517** [comment]
wrap is on its way as `serkan1106_1`

**Comment by steven517** [comment]
wrap is live
