### ISSUE TITLE
Toteking custom wraps 

### ISSUE THREAD

**Issue by toteking233** [saesrpg/donation-vehicle-shaders#386]
**Vehicle ID**
Vehicle ID
559

Wrap access
toteking123

Needs testing
No

Translations
None

Wrap image 
![Legashader](https://user-images.githubusercontent.com/99298498/153094614-42924275-25c6-4a8f-b769-e3c87184a381.png)
![Lega2](https://user-images.githubusercontent.com/99298498/153094792-cd96fc83-e091-4e95-8066-e6097170f2e4.png)
![Lega3](https://user-images.githubusercontent.com/99298498/153094947-e45d2b64-59b8-447c-8188-f25fa399cddc.png)

**Comment by steven517** [comment]
wraps on their way as `toteking123_1`, `toteking123_2` and `toteking123_3` respectively

**Comment by steven517** [comment]
wrap is live
