### ISSUE TITLE
Staylok Custom Wrap

### ISSUE THREAD

**Issue by staylok453** [saesrpg/donation-vehicle-shaders#387]
*Vehicle ID 559 (Jester)

Wrap access staylok

(No need for testing)
![wrap](https://user-images.githubusercontent.com/98068709/153333285-39224e21-ff58-499c-aeb0-1838e0153af6.png)

**Comment by steven517** [comment]
Can you translate the non English text please

**Comment by staylok453** [comment]
yendo no, llegando= not going, arriving

**Comment by tut98** [comment]
Thanks, please save the file with 512x512 dimensions. Try to avoid upscaling the image itself as it doesn't gain any quality from doing so

**Comment by steven517** [comment]
Wrap is on its way as `staylok_2`
