### ISSUE TITLE
Spanish Custom Wrap #9

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#388]
**Vehicle ID:** 407

**Wrap access:** lapd0070

**Thread for reward change:** https://saesrpg.uk/post/336177

**Wrap image**
![SAFD1](https://user-images.githubusercontent.com/72228343/153649785-f2015872-73ab-4eac-a775-2150155c15db.png)

**Comment by tut98** [comment]
On its way as `lapd0070_9`
