### ISSUE TITLE
alius custom wrap 

### ISSUE THREAD

**Issue by alius420** [saesrpg/donation-vehicle-shaders#389]
`**Vehicle ID**: 415
**Wrap access** alius
**Translations**: N/A
**Needs testing**: No
**Wrap Image**: 
![image](https://user-images.githubusercontent.com/55201691/153730894-f24cacd0-1801-4507-a65a-dd39ccea6ae8.png)

**Comment by steven517** [comment]
wrap is on its way as `alius_1`
