### ISSUE TITLE
Custom Wraps request MrSlow

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/donation-vehicle-shaders#39]
Link to my donation topic
https://saesrpg.uk/topic/16159/donation-mrslowguy-amount-50-00gbp?_=1584545385400

I would also like to request screen shots, in case anything needs to be fixed. It'll be easier to fix the issue if we know what it's looking like.

 Thanks in advance!

Vehicle ID: 598 Police LV ( GTA 5 ) 
Wrap access locked to usernames (leave blank if public): MrSlowGuy
Name for wrap (e.g tutPD): SAFPCharger

https://i.imgur.com/CwMvUJo.png

Vehicle ID: 451 Turismo (Lamborghini)
Wrap access locked to usernames (leave blank if public): MrSlowGuy
Name for wrap (e.g tutPD): SAFPTurismo

https://i.imgur.com/OnFgcQ0.png

**Comment by tutgreco** [comment]
ID 598 looks fine.
ID 451 may need adjustments: https://imgur.com/a/UXTrfdS

**Comment by MrSlowGuy** [comment]
Here we go. Attempt number 2! Fingers crossed! 

ID 451: https://imgur.com/a/lff8794

**Comment by tutgreco** [comment]
If you remove the text "SAES       SAFP" on the top rear side (on both sides of the end of the mid strip) and the 3 shades of color (red, blue) on the center roof (on both sides of the mid strip) I think it'll look fine.

**Comment by MrSlowGuy** [comment]
One more time!
https://imgur.com/a/0ynFfsW

**Comment by tutgreco** [comment]
In accordance with the new naming convention used for wraps we've renamed your wrap(s) to:
mrslowguy_1
mrslowguy_2

**Comment by MrSlowGuy** [comment]
Hello, I was wondering if I could have this tested

https://imgur.com/a/toFxc7B
