### ISSUE TITLE
latinos custon wrap

### ISSUE THREAD

**Issue by Latinoo** [saesrpg/donation-vehicle-shaders#390]
**Vehicle ID** 411

**Wrap access** carbon12

**Needs testing**: No

**Wrap image**
![remap](https://user-images.githubusercontent.com/56209707/153729671-f1a7d417-01e1-4133-8547-7dacbb1a4c0d.jpg)

Hey I made some changes in the wrap could you replace this with the wrap "carbon12_5" thank you

**Comment by steven517** [comment]
the updated wrap is on its way
