### ISSUE TITLE
Evans's Custom Wrap Request

### ISSUE THREAD

**Issue by Evans1971** [saesrpg/donation-vehicle-shaders#391]
**Vehicle ID**

415

**Wrap access**

As1414140

**Thread for reward change**

https://saesrpg.uk/topic/30927/donation-evans-amount-10-00-gbp

**Translations**

**Wrap image**

Needs Testing : No

![remap](https://user-images.githubusercontent.com/90685449/153762249-370b4e7a-b785-49a5-8830-6dfa7d7eccbc.png)

**Comment by steven517** [comment]
wrap is on its way as `as1414140_2`
