### ISSUE TITLE
Juanes12 Custom Wrap Resquest

### ISSUE THREAD

**Issue by Juanes12a** [saesrpg/donation-vehicle-shaders#392]
**Vehicle ID**
411

**Wrap access**
juanes12

**Thread for reward change**
https://saesrpg.uk/topic/30935/juanes-s-reward-change

**Needs testing;** no
**Wrap image**
![remap-2](https://user-images.githubusercontent.com/78461831/153940490-7ca40129-19d6-4b2b-8297-35ef115142e5.png)

**Comment by steven517** [comment]
wrap is on its way as `juanes12_4`
