### ISSUE TITLE
Yoko's Custom Wrap Request

### ISSUE THREAD

**Issue by IamYoko** [saesrpg/donation-vehicle-shaders#393]
Vehicle ID
411

Wrap access
officialjosuea

Thread for reward change
https://saesrpg.uk/topic/30938/donation-undefined-amount-30-00-gbp/1?_=1644874123140

Needs testing; no
![alt text](https://i.imgur.com/oYx29Ea.png)

**Comment by steven517** [comment]
wrap is on its way as `officialjosuea_1`
