### ISSUE TITLE
Toteking Custom Wraps

### ISSUE THREAD

**Issue by toteking233** [saesrpg/donation-vehicle-shaders#394]
Vehicle ID
Vehicle ID
559

Wrap access
toteking123

Needs testing
No

Translations
None

Wrap image 
![legi](https://user-images.githubusercontent.com/99298498/153964929-a46202c6-79f9-4c63-9388-8a7fb96adfb2.png)
![legi2](https://user-images.githubusercontent.com/99298498/153964944-39787e80-b59f-4b4e-a22d-2939efa4ca61.png)
![legi3](https://user-images.githubusercontent.com/99298498/153964956-e9be68ba-cb6b-4f78-8752-797db897efbc.png)

**Comment by toteking233** [comment]
@steven517 :D:D 3 more sorry boring u :( i wil do donation for this 3

**Comment by steven517** [comment]
wraps are on their way as `toteking223_4`(green), `toteking223_5`(blue), `toteking223_6`(red)
