### ISSUE TITLE
Rondaw's Custom Wraps

### ISSUE THREAD

**Issue by Melouu74** [saesrpg/donation-vehicle-shaders#396]
**Vehicle ID**
561

**Wrap access**
league1

**Need Testing**
No

**Translations**
N/A

**Wrap image**
![NnpUa6y (1)](https://user-images.githubusercontent.com/97673435/155413596-c5b06180-ef1b-4125-8951-a2f61036814d.png)
![template_AudiRs7 (1)](https://user-images.githubusercontent.com/97673435/155413604-b582e4e7-c157-4ae6-99aa-9a4478e9cf9f.png)

**Comment by steven517** [comment]
Wraps are live as `league1_2` and `league1_3` respectively
