### ISSUE TITLE
Brother's custom wraps Electric Boogaloo 2

### ISSUE THREAD

**Issue by Brotherhoodman** [saesrpg/donation-vehicle-shaders#399]
Vehicle ID
541 (Bullet), 480 (comet)

Wrap access
brotherhoodman my account name

Needs testing
No

Thread for reward change
https://saesrpg.uk/topic/31279/brother-s-reward-change

Translations
None

Wrap image
![bullet1](https://user-images.githubusercontent.com/90584517/157153142-fed06569-748c-4a5a-98d9-b2eadbdd694a.png)
![bullet3](https://user-images.githubusercontent.com/90584517/157153153-b036d287-5191-4641-9101-f5088ee830f6.png)
![comet2](https://user-images.githubusercontent.com/90584517/157153156-442568ce-e5c4-4c55-806a-e8ac96b51535.png)
![GENERIC-WRAP1](https://user-images.githubusercontent.com/90584517/157161696-9c4a7c57-77a8-45df-a121-25d2c2515269.png)
![GENERIC-WRAP2](https://user-images.githubusercontent.com/90584517/157161702-9d838655-1cd7-455e-9433-83f48277ba0f.png)

**Comment by tut98** [comment]
Wraps 1, 2 and 4 looks fairly non-specific and might be able to go as generic wraps, which costs half that of a custom wrap.

For wrap 1, you would need to remove the "vice city" text

If you would like them added as generic wraps, please remove the template crop and instead make the design fill the entire canvas

**Comment by Brotherhoodman** [comment]
Done!

**Comment by tut98** [comment]
Custom wraps on their way as `brotherhoodman_4`, `brotherhoodman_5`, `brotherhoodman_6` and generic wraps `lines2`, `triangular2`
