### ISSUE TITLE
Klay/HasH CostumWarp

### ISSUE THREAD

**Issue by Klay683** [saesrpg/donation-vehicle-shaders#40]
Vehicle ID: 560
Wrap access locked to usernames (leave blank if public):bendhiab/olp
Name for wrap (e.g tutPD):PB-sultan
https://i.imgur.com/p8NEjuh.png

Vehicle ID:  400
Wrap access locked to usernames (leave blank if public):bendhiab/olp
Name for wrap (e.g tutPD):PB-Landstalker
https://i.imgur.com/DiEWXyN.png

@tutgreco  I need those warps to be tested please,including SS before uploading it

**Comment by tutgreco** [comment]
@ ID 506, is it following a template? To me it looks like a generic wrap, which essentially is an image that fits on any vehicle, hence it's not needed to be made using a template.
If you want it as a generic wrap, please upload it where it fills the entire canvas and not with any clipping masks.

**Comment by Klay683** [comment]
ID506,no need to be tested , we can go with the two other warps @tutgreco

**Comment by tutgreco** [comment]
Ok, previews: https://imgur.com/a/6aVsBDf
I can fix ID 560 for you within 1-2 weeks if you're not able to get it to look right.

**Comment by Klay683** [comment]
ID 400 Updated 
![78127E6D-E806-4850-9E95-9A73AFE28416](https://user-images.githubusercontent.com/59097609/77303879-f3b80e80-6cf3-11ea-845a-4bece4bd3d7c.jpeg)

**Comment by Klay683** [comment]
ID 560 updated too
![F4D2CFD0-69E5-459D-926E-8BB5DD92FEA2](https://user-images.githubusercontent.com/59097609/77312229-e9047600-6d01-11ea-9ac3-b7a5d777f790.jpeg)

**Comment by tutgreco** [comment]
560 hood and roof text direction is incorrect.

> I can fix ID 560 for you within 1-2 weeks if you're not able to get it to look right.

Provide the photoshop document in which case.

**Comment by Klay683** [comment]
@tutgreco 
I v' fixed the text on both roof and hood in case it 's wrong please indicate to the correct direction on the following image,
in any other case photoshop file has been sent to you
https://imgur.com/a/SacxIgj
[sultan-pb.zip](https://github.com/saesrpg/donation-vehicle-shaders/files/4369964/sultan-pb.zip)

**Comment by tutgreco** [comment]
Ok, thanks for submitting the project file. As stated above we only accept submissions of certain image resolutions, please respect that in the future. I've exported it from your photoshop document as 1024x1024.

**Comment by tutgreco** [comment]
Your G65 wrap is not passing to server as the image does not meet the accepted resolution. Sultan is fine and is on its way.

**Comment by Klay683** [comment]
Check this @tutgreco 
https://cdn.discordapp.com/attachments/582610935995170817/693139651812261929/4545454545.png

**Comment by tutgreco** [comment]
> Check this @tutgreco
> https://cdn.discordapp.com/attachments/582610935995170817/693139651812261929/4545454545.png

Simply upscaling the already exported image will result in loss of quality and cost a lot of unnecessary space. Can you please look into exporting it from Photoshop as 256x256 or 512x512.

**Comment by Klay683** [comment]
@tutgreco 
https://imgur.com/a/zSdD7tE

**Comment by tutgreco** [comment]
That one is not 256x256, 512x512 or 1024x1024. That means I cannot add it as I stated above.

**Comment by Klay683** [comment]
This one plz @tutgreco 
https://i.imgur.com/POD2nlih.jpg

**Comment by tutgreco** [comment]
wraps added as 'bendhiab_1' and 'bendhiab_2'
