### ISSUE TITLE
Manda's Custom Wrap

### ISSUE THREAD

**Issue by Manda1312** [saesrpg/donation-vehicle-shaders#400]
**Vehicle ID**
561

**Wrap access**
mootez1312

**Thread for reward change**
https://saesrpg.uk/topic/31322/manda-s-reward-change
**Translations**
N/A
**Wrap image**
![undefined - Imgur](https://user-images.githubusercontent.com/101360756/157742984-1fcec343-0c83-48a9-8cca-38772b8bba6c.png)

**Comment by tut98** [comment]
On its way as `mootez1312_1`
