### ISSUE TITLE
General's Custom Wrap

### ISSUE THREAD

**Issue by ElPendejoN** [saesrpg/donation-vehicle-shaders#401]
**Vehicle ID** 
596

**Wrap access** 
elpendejo

**Thread for reward change**  
https://saesrpg.uk/topic/31386/donation-undefined-amount-30-00-gbp

**Translations** 
N/A

**Wrap image** 

![crownvic rick template 2](https://user-images.githubusercontent.com/76622708/158087669-1bebbc24-6dba-4525-91a6-6d5502174cb9.png)

**Comment by steven517** [comment]
wrap is on its way as `elpendejo_1`
