### ISSUE TITLE
Spanish Reward Change Custom Wraps

### ISSUE THREAD

**Issue by LAPDSpanishVEN** [saesrpg/donation-vehicle-shaders#402]
Greetings, I want to add new custom wraps; And remove (lapd0070_8) and (lapd0070_5)
If I'm not wrong, the [lapd0070_8](https://github.com/saesrpg/donation-vehicle-shaders/issues/313) is a Police LS and [lapd0070_5](https://github.com/saesrpg/donation-vehicle-shaders/issues/335) is a Ambulance. If I am correct, please remove those two wraps.

-----
**New Custom Wraps**
----

**Thread for reward change:** https://saesrpg.uk/post/339595

**Vehicle ID:** 579

![huntley](https://user-images.githubusercontent.com/72228343/158192996-fd9e2a9a-c3e9-491e-a3e1-50ca0bd7f685.png)

---

**Vehicle ID:** 561

![brinksstratum](https://user-images.githubusercontent.com/72228343/158193120-9ae5cf57-f16d-4901-b47f-9d7ce04b6041.png)

**Wrap Acess:** lapd0070

**Comment by tut98** [comment]
579 on its way as `lapd0070_5`
561 on its way as `lapd0070_8`
