### ISSUE TITLE
Curvy's custom wrap

### ISSUE THREAD

**Issue by Curvyyy** [saesrpg/donation-vehicle-shaders#403]
**Vehicle ID**
598

**Wrap access**
elyessmaoui

**Thread for reward change**
https://saesrpg.uk/topic/31407/donation-undefined-amount-10-00-gbp?_=1647366376603

**Translations**
none

**Wrap image**

![swat wrap](https://user-images.githubusercontent.com/101663413/158440018-6df82860-788e-41dd-8d0f-ad9f5406699d.png)

**Comment by tut98** [comment]
On its way as `elyessmaoui_1`
