### ISSUE TITLE
Skinner's Custom wrap request

### ISSUE THREAD

**Issue by Spicey30** [saesrpg/donation-vehicle-shaders#404]
**Vehicle ID**

411
**Wrap access**
ItzSpicey

**Thread for reward change**
https://saesrpg.uk/topic/31371/reward-change-elksex-6?_=1647506610341

**Translations**
The only word i have non English its the (Παναθηναΐκος) its a name of a Greek football team also the wrap is based on it Proofs in the Link (https://www.google.com/search?q=panathinaikos&rlz=1C1PRFI_enGR986GR986&tbm=isch&sxsrf=APq-WBvj4eb7pxaxiUj8V5yTKzUfhQesNw:1647506778071&source=lnms&sa=X&ved=2ahUKEwj8h5aC4cz2AhW5gP0HHXF0DQUQ_AUoAnoECAEQBA&biw=1745&bih=890&dpr=1.1)
**Wrap image**

![image](https://user-images.githubusercontent.com/62817925/158771692-dd2f3421-1578-4bbb-8d50-2a14359382b4.png)

**Comment by tut98** [comment]
Please upload image as 512x512 with a background color (e.g. black)

**Comment by Spicey30** [comment]
> 
Hi Sir tut you mean like that? sorry i'm new to this things hhahaah
blob:https://imgur.com/21f4a444-f4fb-4304-8414-8f651779a6b0

**Comment by tut98** [comment]
On its way as `itzspicey_1`
