### ISSUE TITLE
Blue's Custom Wrap

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/donation-vehicle-shaders#405]
**Vehicle ID**
598

**Wrap access**
blue35

**Thread for reward change**
I haven't made one yet, I want to see if wrap can be added first.

**Translations**
n/a

**Wrap image**
 

![zart](https://user-images.githubusercontent.com/62670831/159124168-0ee3291e-b563-4d62-8db6-e43fe85a223b.png)

**Comment by tut98** [comment]
Looks good, there's just a few things that needs changing - any flags on emergency vehicles must be of the US, and the image scale must be 512x512

**Comment by BlueSAES** [comment]
Should be done now.
![lvcar](https://user-images.githubusercontent.com/62670831/159127537-b1b6c6ab-eed9-4d3d-a4b6-431a55d5273c.png)

**Comment by tut98** [comment]
On its way as `blue35_4`
