### ISSUE TITLE
PinkyyyTinkyyy custom wrap

### ISSUE THREAD

**Issue by PinkyyyTinkyyy** [saesrpg/donation-vehicle-shaders#407]
**Vehicle ID**
600 Picador

**Wrap access**
Just me --> t1nk3rt0ts
**Thread for reward change**
https://saesrpg.uk/topic/31582/donation-undefined-amount-40-00-gbp?_=1648251114058

**Translations**
none

Image has already been tested in game car shop

**Wrap image**
![pikachupicador](https://user-images.githubusercontent.com/66016253/160218787-90e01865-831e-4989-826c-db7b3e3affc1.png)

**Comment by tut98** [comment]
Looks good, but I'll have to take it with image dimensions 512x512 instead of 1029x1010 - are you able to test and confirm it looks good at those dimensions?

**Comment by steven517** [comment]
I've gone ahead and resized and tested the wrap, all looks good

The wrap is on its way as `t1nk3rt0ts_1`

**Comment by PinkyyyTinkyyy** [comment]
Ah thanks so much guys!  👍
