### ISSUE TITLE
kiraa's comet

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#408]
**Vehicle ID** 480 comet

**Wrap access** kira12345

**Thread for reward change** https://saesrpg.uk/topic/31623/donation-undefined-amount-10-00-gbp?_=1648489280117

**Translations** N/A

**Wrap image**
![Sans titre-2](https://user-images.githubusercontent.com/81694756/160513256-6df474f2-f471-4cb1-b662-b6a1f43c7298.png)

**Comment by tut98** [comment]
Hey @KiraaTheHustla, we can only accept it with 512x512 image dimensions, are you able to check if it looks OK with those?

**Comment by KiraaTheHustla** [comment]
![Sans titre-1](https://user-images.githubusercontent.com/81694756/160646761-e5c52aa8-fbf3-407c-892e-b0f5bf858aba.png)
ye looks good

**Comment by steven517** [comment]
wrap is on its way as `kira12345_7`

**Comment by steven517** [comment]
Wrap is live
