### ISSUE TITLE
Dufabo'z Custom Wrap

### ISSUE THREAD

**Issue by Dufabo** [saesrpg/donation-vehicle-shaders#409]
**Vehicle ID** 598

**Wrap access**

**Thread for reward change**
https://saesrpg.uk/topic/31744/dufabo-z-reward-change-april

**Wrap image**
![NOW ITS THE END](https://user-images.githubusercontent.com/46716444/161795401-08d793d8-3b62-4cc4-a661-59faa3287d64.png)

**Comment by tut98** [comment]
On its way as `dufabo1900_1`
