### ISSUE TITLE
FOX Wrap v3

### ISSUE THREAD

**Issue by DemienD** [saesrpg/donation-vehicle-shaders#41]
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): dyam98 & FOX Members
Name for wrap (e.g tutPD): FOXv3

![Shader_FOX_v3 2](https://user-images.githubusercontent.com/15146566/77251177-383c9f00-6c4d-11ea-9dd3-3ea4c97a892f.jpg)

**Comment by tutgreco** [comment]
Wrap added as dyam98_1
