### ISSUE TITLE
Kanox car wrapping

### ISSUE THREAD

**Issue by KanoX1** [saesrpg/donation-vehicle-shaders#411]
**Vehicle ID**
559

**Wrap access**
Valgitin

**Thread for reward change**
 https://saesrpg.uk/topic/31880/kanox-reward-change

**Translations**
 This cabron is me, at the top of the vehicle

**Wrap image**

![WRAP_Supra](https://user-images.githubusercontent.com/80906242/164297696-660e8e87-8483-473c-93db-30fa8e8ae844.png)

**Comment by KanoX1** [comment]
I don't understand how the resolution? just mount the images and put them small

**Comment by tut98** [comment]
Okay, no problem - I've upscaled and the wrap is on its way as `valgitin_2`
