### ISSUE TITLE
Envoltura de coche Kanox

### ISSUE THREAD

**Issue by KanoX1** [saesrpg/donation-vehicle-shaders#412]
**Vehicle ID**
598

**Wrap access**
Valgitin

**Thread for reward change**
https://saesrpg.uk/topic/31880/kanox-reward-change

**Translations**
 

**Wrap image**

![WRAP_Police](https://user-images.githubusercontent.com/80906242/164299621-570897d0-315c-40da-9a6d-4e2d9982e42e.png)

**Comment by tut98** [comment]
Hi, would it be possible for you to remove the pink color to keep it in line with the emergency wrap rules please?

**Comment by KanoX1** [comment]
ok i'm repairing it.

**Comment by KanoX1** [comment]
![WRAP_Police (1)](https://user-images.githubusercontent.com/80906242/164577518-24d2d434-b2e9-4178-b343-54a8687be965.png)

**Comment by tut98** [comment]
On its way as `valgitin_3`
