### ISSUE TITLE
Kuny's car wrapping

### ISSUE THREAD

**Issue by lion4ik98** [saesrpg/donation-vehicle-shaders#413]
Vehicle ID
506

Wrap access
lion4ik98

Thread for reward change
https://saesrpg.uk/topic/31939/kuny-reward-change

Translations

Wrap image
![tc2](https://user-images.githubusercontent.com/103755608/165113763-a8266157-c316-4f0f-958e-0e2ae1f74a2b.jpg)

**Comment by tut98** [comment]
On its way as `lion4ik98_1`
