### ISSUE TITLE
Fandi-custum warp cars

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpg/donation-vehicle-shaders#414]
**Vehicle ID**  411

**Wrap access** 
![03F7D3AE-904B-48B3-AC2A-EEE1AAE3C10B](https://user-images.githubusercontent.com/104403749/165200611-d11561ff-f0ad-4600-8057-042b210919a7.png)

 fandi1

**Thread for reward change**

**Translations**

**Wrap image**

**Comment by tut98** [comment]
The wrap image doesn't use our template which you can find through issue #1, besides we only accept image dimensions of 256x256 or 512x512

**Comment by FandiMohammed** [comment]
![Untitled1(1)](https://user-images.githubusercontent.com/104403749/165269790-d2864717-368c-453a-a867-a050c85980e1.png)

**Comment by tut98** [comment]
It looks like it's a pattern that's clipped onto our template - if that's the case, I'll gladly upload it as a Generic wrap, which costs half that of a Custom wrap if you'd like.
If you want it as a Generic wrap, please upload the image in 512x512 dimensions without the template, so just the original image

**Comment by FandiMohammed** [comment]
![Untitled1(1)](https://user-images.githubusercontent.com/104403749/165366498-207e1288-08e5-493d-ab04-8153d67bfbca.png)

**Comment by FandiMohammed** [comment]
fixed

**Comment by tut98** [comment]
It's not really - the image dimensions are 760x632, while we require a fixed 512x512 or 256x256.

As a side note, my offer to upload this as a generic wrap still stands.

**Comment by FandiMohammed** [comment]
![165200611-d11561ff-f0ad-4600-8057-042b210919a7](https://user-images.githubusercontent.com/104403749/165382621-23a9f3b9-2af9-468b-8ced-2574e1af6383.png)
   this one is 512x512

**Comment by tut98** [comment]
It's not made using our template which can be found through issue #1

**Comment by FandiMohammed** [comment]
![Untitled1(1)](https://user-images.githubusercontent.com/104403749/165425630-4ad7072d-293c-4734-9a03-3159b6ab3c90.png)
 512x512 fixed

**Comment by tut98** [comment]
Would you like the wrap added as generic wrap?
That means it can go on any vehicle in the game without requiring a template, because it's a pattern - it's also 50% the cost of a custom wrap.

For instructions on requesting generic wraps, see my 2nd comment on this issue

**Comment by FandiMohammed** [comment]
yes

**Comment by tut98** [comment]
It looks like we already have a similar generic wrap on the server named `dollars`. Would you like that rather than the one you submitted? (If you rather have the one you made, please submit as 512x512 image dimensions)

**Comment by FandiMohammed** [comment]
![Screenshot 2022-04-27 052944](https://user-images.githubusercontent.com/104403749/165548092-458ecf7e-e74d-4256-8b68-e94c5121122a.png)

**Comment by tut98** [comment]
I've cropped the 2nd last picture you sent, on its way as `dollars2`
