### ISSUE TITLE
fandi-skyline

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpg/donation-vehicle-shaders#415]
**Vehicle ID** 401

**Wrap access** fandi123_2 
![68747470733a2f2f692e696d6775722e636f6d2f734d636c4a65452e706e67](https://user-images.githubusercontent.com/104403749/167693259-5f16c1f4-0a6e-452f-ba84-daa9d5ea548d.png)

 

**Thread for reward change**

**Translations**

**Wrap image**

**Comment by tut98** [comment]
ID 401 is not modded by us I'm afraid. You can find list of wrap-able vehicles through issue #1 
You can find more information on requesting wraps on the issue above

**Comment by FandiMohammed** [comment]
Ops i mean ID 402 @tut98

**Comment by tut98** [comment]
Sorry, the wrap template is not owned by us.
As a side note, when requesting wraps please add a fill layer as background (e.g. gray, or the wrap's primary color) and save the image as 512x512 image dimensions

[More information on requesting wraps](https://github.com/saesrpg/donation-vehicle-shaders/issues/1)

**Comment by FandiMohammed** [comment]
![532-5325352_clip-movis-2-fast-furious-paul-walker-skyline](https://user-images.githubusercontent.com/104403749/165366402-5e13f8ee-0f3a-4923-803f-db2dc03eeb0f.png)

**Comment by FandiMohammed** [comment]
fixed
 @tut98

**Comment by tut98** [comment]
Thanks, but the wrap is not made using our template, thus we're unable to add it to the server.

More info on using our templates and requesting wraps can be found in the link on my previous reply

**Comment by FandiMohammed** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f734d636c4a65452e706e67](https://user-images.githubusercontent.com/104403749/165425233-cdce495a-b5c5-441d-bae5-b9ee12e73e72.png)

**Comment by FandiMohammed** [comment]
fixed

**Comment by FandiMohammed** [comment]
@tut98

**Comment by tut98** [comment]
FYI - the wrap access needs to be a 'username'

On its way as `fandi123_2`
