### ISSUE TITLE
Fandi-jester

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpg/donation-vehicle-shaders#416]
**Vehicle ID** 
559

**Wrap access**
 Fandi123_3
![165425045-6cbd3257-9974-4e0c-84eb-1293d59f065e](https://user-images.githubusercontent.com/104403749/167692633-3cdbc893-0529-4122-97e6-05aec724b59f.png)

**Thread for reward change**

**Translations**

**Wrap image**

**Comment by tut98** [comment]
The wrap is not using our template which you can find by reading issue #1

**Comment by FandiMohammed** [comment]
![Untitled1(3)](https://user-images.githubusercontent.com/104403749/165269248-45454c4d-1ef3-4d9c-9829-51930e740c0f.png)
 oh ok i will change to this one

**Comment by FandiMohammed** [comment]
@tut98

**Comment by tut98** [comment]
Thank, are you able to save the image as 512x512 image dimensions please - it's currently 473x419

[More info on requesting wraps](https://github.com/saesrpg/donation-vehicle-shaders/issues/1)

**Comment by tut98** [comment]
The wrap is using our template, but it doesn't fit onto the template properly - it seems to have been stretched vertically and lost a fair amount of quality. Please download our template and make the necessary adjustments

**Comment by FandiMohammed** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f734d636c4a65452e706e67(1)](https://user-images.githubusercontent.com/104403749/165425045-6cbd3257-9974-4e0c-84eb-1293d59f065e.png)

**Comment by FandiMohammed** [comment]
@tut98 confrim pls

**Comment by tut98** [comment]
On its way as `fandi123_3`

**Comment by FandiMohammed** [comment]
any news about added to the ame?
