### ISSUE TITLE
Blue's New Wrap

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/donation-vehicle-shaders#417]
**Vehicle ID**
490

**Wrap access**
blue35

**Thread for reward change**
https://saesrpg.uk/topic/32075/blue-s-reward-change

**Translations**
The signature on the trunk belongs to Atatürk, the rest should be obvious, and the ones on the sides are emergency number.

**Wrap image**

![turkpolisison](https://user-images.githubusercontent.com/62670831/167302944-b1c05058-e7ff-4238-a1eb-1c3a4061fb4b.png)

**Comment by tut98** [comment]
Please keep design English
