### ISSUE TITLE
Custom Wrap for Jester (Toyota Supra)

### ISSUE THREAD

**Issue by miny1997** [saesrpg/donation-vehicle-shaders#418]
**Vehicle ID**
Jester 559

**Wrap access**
SPNNX (only me)

**Thread for reward change**
https://saesrpg.uk/topic/32088/donation-undefined-amount-10-00-gbp

**Translations**
藤原 とうふ 店 ( 自家用 ) - Fujiwara tofu store (for private use)

For reference: It's the car from the anime Initial D.

**Wrap image**
https://cdn.discordapp.com/attachments/973311365513113682/973708917588762675/tofucar_1_test.png

**Comment by tut98** [comment]
On its way as `spnnx_1`

**Comment by steven517** [comment]
wrap is live
