### ISSUE TITLE
Winter-Jester

### ISSUE THREAD

**Issue by Woytex** [saesrpg/donation-vehicle-shaders#419]
**Vehicle ID**

559
**Wrap access**

Winter_Soldier555
**Thread for reward change**

**Translations**

**Wrap image**

![559](https://user-images.githubusercontent.com/86136606/168171196-3fb4271a-030c-44f5-9386-186f3c4e7dd6.jpg)

**Comment by steven517** [comment]
You might want to test the wrap in the SF carshop before requesting it here. The rear image will be upside down in game. Please make the necessary fixes to the wrap and request again.
