### ISSUE TITLE
Winter-jester

### ISSUE THREAD

**Issue by Woytex** [saesrpg/donation-vehicle-shaders#420]
**Vehicle ID**
 559

**Wrap access**
 Winter_Soldier555

**Thread for reward change**

**Translations**

**Wrap image**

![559](https://user-images.githubusercontent.com/86136606/168177595-b012ef68-ac81-422b-9399-6b1ee3f7e95a.jpg)

**Comment by steven517** [comment]
You just re-posted the exact same thing. Please follow my instructions here: https://github.com/saesrpg/donation-vehicle-shaders/issues/419
