### ISSUE TITLE
kiraa's wrap

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#421]
**Vehicle ID** 604

**Wrap access** kira12345

**Thread for reward change**  https://saesrpg.uk/topic/32141/kiraa-reward-change?_=1652484957711

**Translations** N/A

**Wrap image** 
![Sans titre-1](https://user-images.githubusercontent.com/81694756/168403436-bce78588-e1b2-4e76-9d62-968b7ed43f49.png)

if possible to delete (kira12345_1 / kira12345_2 / kira12345_4 / kira12345_6)
and thnx

**Comment by KiraaTheHustla** [comment]
@tut98 / @steven517  👋

**Comment by tut98** [comment]
> if possible to delete (kira12345_1 / kira12345_2 / kira12345_4 / kira12345_6) and thnx

Done pending resource restart, but the new wrap replaces `kira12345_1`
