### ISSUE TITLE
Liberty reward change Custom Wrap

### ISSUE THREAD

**Issue by mag1kSS** [saesrpg/donation-vehicle-shaders#423]
**Vehicle ID**
561

**Wrap access**
Mag1kS

**Thread for reward change**
https://saesrpg.uk/topic/32212/liberty-reward-change
**Translations**

**Wrap image**
![template_AudiRs7](https://user-images.githubusercontent.com/84975890/170287327-1f9d6809-eb85-4739-8451-5509777a414f.jpg)

**Comment by tut98** [comment]
On its way as `mag1ks_2`
