### ISSUE TITLE
Curvy's Custom Wrap

### ISSUE THREAD

**Issue by Curvyyy** [saesrpg/donation-vehicle-shaders#424]
**Vehicle ID**
411

**Wrap access**
elyessmaoui

**Thread for reward change**
https://saesrpg.uk/topic/32222/curvy-s-reward-change

**Translations**
none

**Wrap image**
![21](https://user-images.githubusercontent.com/101663413/170726264-3b709a0f-b73d-40a9-a4b9-33098289a638.jpg)

**Comment by tut98** [comment]
on its way as `elyessmaoui_2`
