### ISSUE TITLE
Custom Wrap Malicious

### ISSUE THREAD

**Issue by MaliciousGirlFriend** [saesrpg/donation-vehicle-shaders#426]
**Vehicle ID**
560

**Wrap access**
Malicious,voli,amrosh

**Thread for reward change**
https://saesrpg.uk/topic/32310/donation-malicious-amount-10-00-gbp 
i have tested the wrap so u dont need to

**Translations**
BAT tunisian group name , وحدات التدخل = intervention units (on doors)

**Wrap image**
![template](https://user-images.githubusercontent.com/84158178/171910098-93d51926-851e-4a9a-a501-8728cd20d187.png)

**Comment by tut98** [comment]
As this is an emergency wrap its contents should be kept English and American for flags - as a side note we only accept image sizes of 256x256 and 512x512

**Comment by MaliciousGirlFriend** [comment]
It should not be an emergency wrap. meanwhile i want my country flag im not going to put american flag for no reason on my car
![wiouw](https://user-images.githubusercontent.com/84158178/171994691-c2a1e0a1-0a2d-4e80-99eb-3289650d976d.png)

**Comment by tut98** [comment]
Intervention units should conform to our emergency services wrap rules 🙂 

Please recreate your issue if you are able to make these changes

**Comment by MaliciousGirlFriend** [comment]
but i have already changed the wrap as u can see above
