### ISSUE TITLE
Custom wrap - nekranox - Alpha (Ford Mustang GT)

### ISSUE THREAD

**Issue by nekranox** [saesrpg/donation-vehicle-shaders#428]
**Vehicle ID**
602

**Wrap access**
nekranox

**Thread for reward change**
https://saesrpg.uk/topic/32340/donation-nekranox-amount-30-00-gbp/

**Translations**
none

**Wrap image**
![nox_mustangGT](https://user-images.githubusercontent.com/3071115/172005467-b2c0e562-8fb6-40af-91e0-8178718a631f.png)

**Comment by tut98** [comment]
I've had to downsize the wrap to 512x512, but it's now on its way as `nekranox_1`

**Comment by nekranox** [comment]
template was 1024, my bad
