### ISSUE TITLE
MrSlowGuy - Custom car wrap

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/donation-vehicle-shaders#43]
Hey I was wondering if y’all could test this out for me .

Vehicle Name: Burrito
Vehicle ID: 482
Custom Wrap: 

https://imgur.com/a/toFxc7B

**Comment by tutgreco** [comment]
Review: https://imgur.com/a/Ncg98km

As a side note we've updated the naming convention for custom wraps, so there's no need to provide info on that. We'll only need to know the username(s) that can receive the wrap for their donation vehicles.

**Comment by MrSlowGuy** [comment]
Okay, hard copy tut. I updated it after some discussion with my group. Could you please test it to see if it works and how it would look once implemented ? 


!!! Also !!! 

I know you told me to upload it as .png but I’m not sure how to do that with imgur. I’d happy re do it if you gave me some tips 

Vehicle Name: Burrito
Vehicle ID: 482
Custom wrap: 
https://i.imgur.com/0Rnwwz9.jpg

**Comment by tutgreco** [comment]
Review: https://imgur.com/a/SAKgipA

**Comment by tutgreco** [comment]
Are you withdrawing the request? @MrSlowGuy
