### ISSUE TITLE
Kodigo Custom Warps

### ISSUE THREAD

**Issue by kodigo21** [saesrpg/donation-vehicle-shaders#430]
**Vehicle ID**
 506 - 482 - 400 - 604 

**Wrap access**

**Thread for reward change**

https://saesrpg.uk/topic/32350/donation-kodigo-amount-40-00-gbp/1?_=1654439338627

**Wrap image**
Super GT - 506:
https://i.imgur.com/l8Pc4EB.png

Burrito - 482:
https://i.imgur.com/YYql68E.png

 Landstalker - 400:
https://i.imgur.com/TJ5uyZd.png

Glendale shit - 604:
https://i.imgur.com/NJEKEFn.png

**Comment by steven517** [comment]
wraps on their way as:
SGT: `eduuh96_3`
Burrito: `eduuh96_4`
Landstalker: `eduuh96_5`
Glendale shit: `eduuh96_6`
