### ISSUE TITLE
Andrew's Custom Wrap

### ISSUE THREAD

**Issue by MastermindReaper** [saesrpg/donation-vehicle-shaders#432]
**Vehicle ID**
560
**Wrap access**
locked to me AndrewYoung561

**Thread for reward change**
https://saesrpg.uk/topic/32362/donation-undefined-amount-28-00-gbp

**Translations**

**Wrap image**
(Okay all done, thank you for the being patient)
![Outfit logo Sutan lv](https://user-images.githubusercontent.com/92995646/172386100-b184158b-4eba-4d17-8519-7d8aa3af22c3.png)

**Comment by tut98** [comment]
On its way as `andrewyoung561_1`

**Comment by MastermindReaper** [comment]
Just in case you don't see it above, it should look like this
![Outfit logo Sutan lv](https://user-images.githubusercontent.com/92995646/172700326-05382e3b-efb6-4732-ad5c-85c021e1f2b0.png)
.

**Comment by tut98** [comment]
If you send us the original pattern image in 512x512 we can add it as a generic wrap, which only charges you half that a custom wrap would @MastermindReaper

**Comment by MastermindReaper** [comment]
![LV pattern](https://user-images.githubusercontent.com/92995646/172770451-20a801f6-8286-400e-aac6-9cec39e498be.png)
![custom sultan](https://user-images.githubusercontent.com/92995646/172770464-3be1dbea-b4fa-4f18-b813-fcbaec65adbf.png)
 
Here you go

**Comment by tut98** [comment]
Would you also like the custom wrap?

**Comment by MastermindReaper** [comment]
Yes please
