### ISSUE TITLE
Skinner DILDO Wrap

### ISSUE THREAD

**Issue by Spicey30** [saesrpg/donation-vehicle-shaders#433]
**Vehicle ID**600

**Wrap access**
  Rn N/A

**Thread for reward change**
 N/A ill make reward change soon once i finish and the other  one wrap

**Translations**

**Wrap image**

![template_picador](https://user-images.githubusercontent.com/62817925/172274336-d31a2de1-7e5a-4441-912e-0523fb4324a8.png)

**Comment by tut98** [comment]
On its way as `itzspicey_2`
