### ISSUE TITLE
BOB wrap

### ISSUE THREAD

**Issue by rabyewiw** [saesrpg/donation-vehicle-shaders#434]
**Vehicle ID**
451 ( turismo )

**Wrap access**
rabyewiw

**Thread for reward change**
https://saesrpg.uk/topic/32332/donation-undefined-amount-10-00-gbp
**Translations**
none

**Wrap image**
https://imgur.com/a/e7SapbS

**Comment by steven517** [comment]
wrap is on its way as `rabyewiw_1`

in the future please make image resolutions 512x512 and make the background a solid colour, not transparent, thank you!
