### ISSUE TITLE
velo's custom wrap request

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#435]
**Vehicle ID**
502

**Wrap access**
velona77

**Thread for reward change**
https://saesrpg.uk/topic/32425/donation-undefined-amount-15-00-gbp?_=1654988896502

**Wrap image**
![velo hr3](https://user-images.githubusercontent.com/46403782/173210153-4e510e35-7735-4d72-9188-4c4c06ff2ec2.png)

**Comment by steven517** [comment]
wrap is on its way as `velona77_8`

In the future please make the background of the image a solid colour, not transparent, thank you!
