### ISSUE TITLE
Bisollini - Custom Wrap Request.

### ISSUE THREAD

**Issue by Bisollini** [saesrpg/donation-vehicle-shaders#436]
**Vehicle ID**
411

**Wrap access**
alex0107

**Thread for reward change**
https://saesrpg.uk/topic/30416/donation-point-balance-bisollini?_=1654889963543

**Translations**
N/A

**Wrap image**
![image](https://user-images.githubusercontent.com/91908268/173230507-831d106c-fe20-43a7-9b6c-3e0bbd1d6189.png)

**Comment by steven517** [comment]
wrap is on its way as `alex0107_1`
