### ISSUE TITLE
Fandi Custom warps

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpg/donation-vehicle-shaders#438]
**Vehicle ID** 
411 
559 
 506
 

**Wrap access**
 
Fandi123_6 
Fandi123_7  
Fandi123_8

**Thread for reward change** 
 
https://saesrpg.uk/topic/32585/fandi-rewardchange

**Translations** 

**Wrap image**

![68747470733a2f2f692e696d6775722e636f6d2f734d636c4a65452e706e67 1263](https://user-images.githubusercontent.com/104403749/175768477-5e0cc618-fbf3-45f6-8e13-bf7965670baa.jpg)

![341634546546](https://user-images.githubusercontent.com/104403749/174907332-3cf86556-eb93-40ca-b829-555c7bb10c1a.jpg)

![MvrnrZy (2)](https://user-images.githubusercontent.com/104403749/174907940-d2e36a5b-0f55-4a0b-be95-fe4998679f3e.jpg)

**Comment by tut98** [comment]
Sorry, that first image is not using a template owned by us

**Comment by FandiMohammed** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f734d636c4a65452e706e67 1263](https://user-images.githubusercontent.com/104403749/174976645-77891a2c-3dd5-45b2-a942-87fe92f73ed3.jpg)

**Comment by FandiMohammed** [comment]
done sir

**Comment by FandiMohammed** [comment]
@tut98 @steven517

**Comment by tut98** [comment]
Live
