### ISSUE TITLE
ICE POLICE - Custom car wrap review/test

### ISSUE THREAD

**Issue by icepolice** [saesrpg/donation-vehicle-shaders#44]
Hello,

I want to test those 2 car shaders.

Vehicle Name: POLICE LV
Vehicle ID: 598

Pleaese send me per PM the Screenshot's to my discord or forum.
Forum: https://saesrpg.uk/user/james
Discord: James69#9106
![ICE_v1](https://user-images.githubusercontent.com/46728904/77664000-63ddc300-6f86-11ea-9e85-460861a50f55.png)
![ICE_v2](https://user-images.githubusercontent.com/46728904/77664004-650ef000-6f86-11ea-8976-add274725143.png)

**Comment by tutgreco** [comment]
Review sent to discord profile
