### ISSUE TITLE
HolySkillzZ's custom's wrap

### ISSUE THREAD

**Issue by HolySkillzZ** [saesrpg/donation-vehicle-shaders#443]
**598 Police LV**

**holyskillzz  and diabled**

**https://saesrpg.uk/topic/32676/donation-undefined-amount-20-00-gbp?_=1656619540912**

**Translations**

**
![Dodge wrap](
![Dodge wrap test 2](https://user-images.githubusercontent.com/108236356/176947797-74b2d262-0365-46dd-be87-749fcaa40508.png)
)
**

**Comment by steven517** [comment]
wrap is on its way as `holyskillzz_1`
