### ISSUE TITLE
alone's custom wrap

### ISSUE THREAD

**Issue by badbunny404** [saesrpg/donation-vehicle-shaders#444]
**Vehicle ID**
411

**Wrap access**
alone1

**Thread for reward change**
https://saesrpg.uk/topic/32679/donation-undefined-amount-15-00-gbp?_=1656783107805

**Translations**
N/A

**Wrap image**
![rw0I6Mj](https://user-images.githubusercontent.com/77053374/177015310-30309bb2-a596-404c-be45-1ea32b8d412d.png)

**Comment by tut98** [comment]
on its way as `alone1_1`
