### ISSUE TITLE
Anas' Custom Wrap.

### ISSUE THREAD

**Issue by Procipez** [saesrpg/donation-vehicle-shaders#445]
**Vehicle ID**
  402

**Wrap access**
 CyberGhost

**Thread for reward change**
 https://saesrpg.uk/topic/32658/donation-anas-amount-10-00gbp)

**Translations**
 N/A

**Wrap image**
 
![template](https://user-images.githubusercontent.com/108623142/177048553-4ec06f27-8c85-4847-b1ac-cb2dbc1f5f9a.png)

**Comment by steven517** [comment]
wrap is on its way as `cyberghost_1`
