### ISSUE TITLE
Flex's Custom Wrap.

### ISSUE THREAD

**Issue by Flex200** [saesrpg/donation-vehicle-shaders#446]
**Vehicle ID**

598
**Wrap access**

midou200

**Thread for reward change**
https://saesrpg.uk/topic/32766/flex-s-reward-change

**Translations**
N/A

**Wrap image**
![wrap](https://user-images.githubusercontent.com/108627381/177198750-f614a8e9-4fa0-4da4-b044-083577a50fc9.png)

**Comment by steven517** [comment]
wrap is on its way as `midou200_1`

**Comment by steven517** [comment]
MY apologies, this wrap needs to be redesigned. Non American flags are not allowed on Police vehicles

**Comment by Flex200** [comment]
> MY apologies, this wrap needs to be redesigned. Non American flags are not allowed on Police vehicles

I have redesigned the wrap

**Comment by steven517** [comment]
the new wrap is on its way, same name
