### ISSUE TITLE
Custom Wraps - Rolly

### ISSUE THREAD

**Issue by Rolly-E** [saesrpg/donation-vehicle-shaders#447]
**Vehicle ID**
<598>

**Wrap access**
Rollyking

**Thread for reward change**
<https://saesrpg.uk/topic/32770/donation-rolly-amount-50-00-gbp?_=1656941746289 / https://saesrpg.uk/topic/32772/donation-point-balance-rolly?_=1656941746292>

**Translations**
no need

**Wrap image**
<https://i.imgur.com/vxHEQXJ.jpg>

----

**Vehicle ID**
<519>

**Wrap access**
Rollyking

**Thread for reward change**
<https://saesrpg.uk/topic/32770/donation-rolly-amount-50-00-gbp?_=1656941746289 / https://saesrpg.uk/topic/32772/donation-point-balance-rolly?_=1656941746292>

**translations**
no need

**Wrap image*
<https://i.imgur.com/yJkOaIJ.jpg>

----

**Vehicle ID**
<411>

**Wrap access**
Rollyking

**Thread for reward change**
<https://saesrpg.uk/topic/32770/donation-rolly-amount-50-00-gbp?_=1656941746289 / https://saesrpg.uk/topic/32772/donation-point-balance-rolly?_=1656941746292>

**translations**
no need

**Wrap image**
<https://i.imgur.com/ZoD5oJw.jpg>

----

**Vehicle ID**
<494>

**Wrap access**
Rollyking

**Thread for reward change**
<https://saesrpg.uk/topic/32770/donation-rolly-amount-50-00-gbp?_=1656941746289 / https://saesrpg.uk/topic/32772/donation-point-balance-rolly?_=1656941746292>

**translations**
no need

**Wrap image**
<https://i.imgur.com/mGtUEdR.jpg>

------

**Vehicle ID** 
<541>

**Wrap access**
Rollyking

**Thread for reward change**
<https://saesrpg.uk/topic/32770/donation-rolly-amount-50-00-gbp?_=1656941746289 / https://saesrpg.uk/topic/32772/donation-point-balance-rolly?_=1656941746292>

**translations**
no need

**Wrap image**
<https://i.imgur.com/SCxFrvP.jpg>

**Comment by steven517** [comment]
@Rolly-E please drag and drop the files directly into your GitHub request

**Comment by steven517** [comment]
user has been banned, when/if you are unbanned make another request
