### ISSUE TITLE
Custom Shader - FoxZilla

### ISSUE THREAD

**Issue by LahanaFTW** [saesrpg/donation-vehicle-shaders#448]
**Vehicle ID**
 
598

**Wrap access**
 
mertt and MI-6 Members

**Thread for reward change**
 
https://saesrpg.uk/topic/28761/donation-point-balance-foxzilla I will make reward change.

**Translations**
 
There is only a one sentence: "Semper Occultus" it means always secret and already it's writing under that.

**Wrap image**
[](https://i.imgur.com/F55ssm2.png)
https://i.imgur.com/F55ssm2.png

**Comment by steven517** [comment]
wrap is on its way as `mertt_1`
