### ISSUE TITLE
ICE POLICE - Customs wrap request

### ISSUE THREAD

**Issue by icepolice** [saesrpg/donation-vehicle-shaders#45]
Hi,
We like to request the following wrap:
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): james69,glastras96
![ICE_v1](https://user-images.githubusercontent.com/46728904/77675937-503a5880-6f96-11ea-9e02-2399bdf991e6.png)

**Comment by tutgreco** [comment]
Wrap added as 'james69_1'
