### ISSUE TITLE
FBI Custom Wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#452]
**Vehicle ID**
598

**Wrap access**
dhiamlaih

**Thread for reward change**
https://saesrpg.uk/topic/32820/donation-undefined-amount-15-00-gbp

**Translations**
N/A, everything is clear.

**Wrap image**
![liyones](https://user-images.githubusercontent.com/60038193/177893992-ffc4ce87-fa12-459d-b600-0b6aa074fd62.png)

**Comment by steven517** [comment]
wrap is on its way as `dhiamlaih_1`
