### ISSUE TITLE
Malicious Custom wrap

### ISSUE THREAD

**Issue by MaliciousGirlFriend** [saesrpg/donation-vehicle-shaders#453]
**Vehicle ID**
400

**Wrap access**
malicious

**Thread for reward change**
https://saesrpg.uk/topic/32850/malicious-reward-change , you dont need to test the wrap already tested it

**Translations**
none

**Wrap image**
![template](https://user-images.githubusercontent.com/84158178/178039891-116d56ab-a8b9-4bff-99a5-c0e5a43a0e23.jpg)

**Comment by steven517** [comment]
wrap is on its way as `malicious_3`
