### ISSUE TITLE
pook's custom wrap

### ISSUE THREAD

**Issue by Xpooks** [saesrpg/donation-vehicle-shaders#454]
**Vehicle ID**
598

**Wrap access**
username: chadi147

**Thread for reward change**

https://saesrpg.uk/topic/32581/donation-xpooks-amount-20-00-gbp/1
( I will make a change request once the wrap is live)

**Translations**
None everything in English

**Wrap image**
![big](https://user-images.githubusercontent.com/46722231/178106542-ddac86a4-0d18-4a80-b509-ee258b5937be.png)

**Comment by tut98** [comment]
On its way as `chadi147_1`
