### ISSUE TITLE
M7mDGr7 Custom Wraps

### ISSUE THREAD

**Issue by M7mDGr7** [saesrpg/donation-vehicle-shaders#455]
**Vehicle ID**
541

**Wrap access**
M7mDGr7

**Thread for reward change**
will be requested soon

**Translations**
-/

**Wrap image**

![bullet wrap 1](https://user-images.githubusercontent.com/77129717/178124867-6a2597d5-17cf-4ffa-99f2-06a26c60f4ed.png)
![bullet wrap 2](https://user-images.githubusercontent.com/77129717/178124869-62691004-9b64-494b-a2bb-558a525a758f.png)

**Comment by tut98** [comment]
On their way as `m7mdgr7_6` and `m7mdgr7_7` respectively
