### ISSUE TITLE
Cookie's Dope AF custom wrap

### ISSUE THREAD

**Issue by HollowCookieDoge** [saesrpg/donation-vehicle-shaders#456]
**Vehicle ID**
506

**Wrap access**
 it says to leave blank if anyone can use it but if its needed username:addictedcookie

**Thread for reward change**
https://saesrpg.uk/topic/32882/donation-undefined-amount-10-00-gbp?_=1657487568980

**Translations**

**Wrap image**

![HKSHADER](https://user-images.githubusercontent.com/109044975/178163828-54a4c827-2198-4bfa-91b9-1055e89b13fe.png)

**Comment by steven517** [comment]
please include who will have access to the wrap
