### ISSUE TITLE
Yazzan custom wrap

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpg/donation-vehicle-shaders#457]
**Vehicle ID** 561

**Wrap access** Greenchek212_1

**Thread for reward change** https://saesrpg.uk/topic/32886/donation-undefined-amount-25-00-gbp?_=1657497707144

**Translations**

**Wrap image** 
![0gmJ0uO](https://user-images.githubusercontent.com/104403749/178167230-00869691-00d6-43c4-82a7-1f30b654c3fc.jpg)

**Comment by tut98** [comment]
On its way as `greenchek212_1`
