### ISSUE TITLE
Jonas133 custom wrap

### ISSUE THREAD

**Issue by jonas13362** [saesrpg/donation-vehicle-shaders#459]
**Vehicle ID**
411

**Wrap access**
jonas13362

**Donation Thread**
(https://saesrpg.uk/topic/32891/donation-undefined-amount-25-00-gbp)

**Wrap image**
![space](https://user-images.githubusercontent.com/6437975/178257279-0eb53ed5-81c5-40c9-bc8d-fcccf54f9952.png)

**Comment by tut98** [comment]
On its way as `jonas13362_1`
