### ISSUE TITLE
Rolly Custom Wraps

### ISSUE THREAD

**Issue by Rolly-E** [saesrpg/donation-vehicle-shaders#460]
**Vehicle ID**
<541>

**Wrap access**
rollyking

**Wrap image**
[<
![image](https://user-images.githubusercontent.com/108678466/178622967-560b01af-6959-4b21-b1a4-bef58540b07f.png)
>]

**Vehicle ID**
<494>

**Wrap access**
rollyking

**Wrap image**

![image](https://user-images.githubusercontent.com/108678466/178629173-56570a2d-d2d4-49e6-b29e-88977e1f8ae4.png)

**Vehicle ID**
<411>

**Wrap access**
rollyking

**Wrap image**

![image](https://user-images.githubusercontent.com/108678466/178623045-39fa4110-963b-4919-8926-87ef0e3134bc.png)

**Vehicle ID**
<519>

**Wrap access**
rollyking

**Wrap image**

![image](https://user-images.githubusercontent.com/108678466/178624258-2b9b61ac-3190-43d0-8a6f-2fe309bdfaed.png)

- Donation Tracking Topic:

https://saesrpg.uk/topic/32772/donation-point-balance-rolly?_=1657672744703

**Comment by steven517** [comment]
wraps on their way as:
Pink sgt: `rollyking_1`
Black hotring 1: `rollyking_2`
Grey Infernus: `rollyking _3`
black and white hotring 1: `rollyking_4`
Louis Vuitton texture: `rollyking_5`
