### ISSUE TITLE
reket's Police LS wrap

### ISSUE THREAD

**Issue by reketitekkep6hjus** [saesrpg/donation-vehicle-shaders#462]
**Vehicle ID**
596

**Wrap access**
mikupro, garrett2011

**Thread for reward change**
Will add it later. No need to test.

**Translations**
POLITSEI - POLICE
INFO - self explanatory
**Wrap image**
![final](https://user-images.githubusercontent.com/109255441/179071884-94486dbc-693f-4d6e-a64d-812d5749f274.png)

**Comment by tut98** [comment]
Lettering will need to be English - for more information on rules for emergency services wraps, see #1

**Comment by reketitekkep6hjus** [comment]
I have seen numerous police vehicles with similar themes like "POLIS", whats the difference between them and this? Maybe I am missing something but I don't see a rule against non-English text on police cars on the link you provided.

**Comment by tut98** [comment]
Rules can be found on the [forum thread linked above](https://saesrpg.uk/topic/8309/about-donation-wraps)

If you have any evidence (screenshots or similar, and wrap owner) of emergency service wraps that go against the rules please direct them to myself or Steven in Discord or a forum PM!

**Comment by reketitekkep6hjus** [comment]
Alright, would it be good to go if the 'POLITSEI' was replaced with GARRETT?

**Comment by tut98** [comment]
Sure

**Comment by reketitekkep6hjus** [comment]
Updated.

**Comment by tut98** [comment]
Just need to change the contact info on the left side and it'll be good to go

**Comment by reketitekkep6hjus** [comment]
What exactly needs to be changed? the www.POLITSEI.ee has to be removed or the entire thing?

**Comment by tut98** [comment]
Politsei and the Estonian domain needs to go. Foreign content generally cannot go on emergency service wraps.

**Comment by reketitekkep6hjus** [comment]
I don't understand what you mean by US format.

**Comment by tut98** [comment]
It is 911 for the USA. There is a specific phone format for USA, example +1 (234) 567-8901

**Comment by reketitekkep6hjus** [comment]
If I change 110 to 911, will it be fine? Or do I have to make the INFO 612-3000?

**Comment by tut98** [comment]
To be fair we're not too strict on formatting, it just needs to be US, meaning no foreign country codes or phone number variations that you wouldn't see anywhere in the US.

**Comment by tut98** [comment]
US phone numbers are formatted as `+countrycode (area code) phone number.` Your example could be `INFO +1 (424) 612-3000`
You can find a list of area codes at https://www.allareacodes.com/maps/us-area-code-map-thumb.png or make your own.

**Comment by reketitekkep6hjus** [comment]
I have decided to make another wrap instead of this one. Sorry for the trouble.
