### ISSUE TITLE
Police LV

### ISSUE THREAD

**Issue by reketitekkep6hjus** [saesrpg/donation-vehicle-shaders#464]
**Vehicle ID**
598

**Wrap access**
garrett2011

**Thread for reward change**
https://saesrpg.uk/topic/32933/donation-undefined-amount-20-00-gbp

**Translations**
N/A

**Wrap image**
![512](https://user-images.githubusercontent.com/109255441/179363888-3190f193-6e3e-4558-ba02-b6a6a640aa21.png)

**Comment by tut98** [comment]
Currently we only accept images with 512x512 or 256x256 dimensions

**Comment by reketitekkep6hjus** [comment]
Edited, it's 512x512 now.

**Comment by reketitekkep6hjus** [comment]
is it fine then?

**Comment by tut98** [comment]
Yep, on its way as `garrett2011_1`
