### ISSUE TITLE
Curny's custom wrap

### ISSUE THREAD

**Issue by Curny123** [saesrpg/donation-vehicle-shaders#465]
**Vehicle ID**
561

**Wrap access**
freezz

**Thread for reward change**
https://saesrpg.uk/topic/32968/curny-s-reward-change

**Translations**

**Wrap image**

![camesl-Stratum](https://user-images.githubusercontent.com/108004852/179363645-8d7f90f1-f8dd-4c0c-96fe-51657b0eb576.png)

**Comment by tut98** [comment]
When #463 goes live you'll be able to use the wrap `gang_bb`. As a side note we only accept images with dimensions 512x512 or 256x256
