### ISSUE TITLE
FBI rancher

### ISSUE THREAD

**Issue by reketitekkep6hjus** [saesrpg/donation-vehicle-shaders#466]
**Vehicle ID**
490

**Wrap access**
garrett2011

**Thread for reward change**
https://saesrpg.uk/topic/32933/donation-undefined-amount-20-00-gbp?_=1658087935630
**Translations**
N/A

**Wrap image**
![321](https://user-images.githubusercontent.com/109255441/179422861-6bbcb347-f4a2-4ca6-a6ff-c8e752244cc4.png)

**Comment by tut98** [comment]
The version that was most recently edited is on its way as `garrett2011_2`
