### ISSUE TITLE
Black~Bullets Warp

### ISSUE THREAD

**Issue by youssef-bb** [saesrpg/donation-vehicle-shaders#467]
**Vehicle ID**
470

**Wrap access**
setttheboss
**Thread for reward change**
to be updated

**Translations**
n/a

**Wrap image**
![undefined - Imgur (6)](https://user-images.githubusercontent.com/93038475/180047357-fbe0244a-7485-47be-b4e3-1a6375b870f0.png)

**Comment by tut98** [comment]
Black Bullets currently has a gang wrap requested in #463 , would you like this one added as a personal wrap or replace the gang's existing wrap?
If you would like it as a personal wrap, please mention a few gang usernames that you would like to have wrap access.

**Comment by youssef-bb** [comment]
okay ill make it as a personal warp then if a gang mate want the warp ill give him access @tut98 Ty 👍

**Comment by tut98** [comment]
On its way as `setttheboss_5`
