### ISSUE TITLE
FBI Custom Wrap Change

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#468]
**Vehicle ID**
598

**Wrap access**
dhiamlaih & all FBI agents.

**Thread for reward change**
https://saesrpg.uk/topic/32820/donation-undefined-amount-15-00-gbp

**Translations**
Everything is clear.

**Wrap image**
![template](https://user-images.githubusercontent.com/60038193/180512356-d6e414b6-41e9-4ae8-96bb-b2d6eff5abfd.png)

**Comment by tut98** [comment]
Would you like other usernames than your own added as wrap owner?

**Comment by Liyones** [comment]
> Would you like other usernames than your own added as wrap owner?

FBI Agents yes please.

**Comment by tut98** [comment]
We'll need a few usernames, unless you want it added as a squad wrap. FBI currently has no squad wrap.

**Comment by Liyones** [comment]
> We'll need a few usernames, unless you want it added as a squad wrap. FBI currently has no squad wrap.

Then just add my username as wrap owner.

**Comment by tut98** [comment]
On its way as `dhiamlaih_2`

**Comment by Liyones** [comment]
> On its way as `dhiamlaih_2`

I guess it should be dhiamlaih_1 because i will change it with the current dhiamlaih_1 wrap which is live.

**Comment by tut98** [comment]
Ok
