### ISSUE TITLE
corpse's custom rwap

### ISSUE THREAD

**Issue by corpseginder** [saesrpg/donation-vehicle-shaders#469]
**Vehicle ID**
<!vehicle id: 451>

**Wrap access**
corpsegrinder
**Thread for reward change**

**Translations**

![AAPD_Corpse](https://user-images.githubusercontent.com/109925418/180668259-3783517f-e01d-4289-ace6-64c5a989dfb1.png)

**Wrap image**

[AAPD_Corpse](https://user-images.githubusercontent.com/109925418/180668259-3783517f-e01d-4289-ace6-64c5a989dfb1.png)

**Comment by tut98** [comment]
On its way as `corpsegrinder_1`
