### ISSUE TITLE
Raafet's Custom Wrap Request

### ISSUE THREAD

**Issue by raafet12** [saesrpg/donation-vehicle-shaders#47]
Vehicle Name: Sultan
Vehicle ID: 560
Wrap access locked to: raafet
Custom wrap:
https://imgur.com/gallery/kiheMhI

**Comment by tutgreco** [comment]
Imgur link is down, please re-upload @raafet12

**Comment by raafet12** [comment]
done

**Comment by raafet12** [comment]
@tutgreco  Can I see the wrap please?

**Comment by tutgreco** [comment]
> @tutgreco Can I see the wrap please?

I'm sorry for the late response. Wrap added as 'raafet_1', please have an admin add the wrap for you, so that you can reopen this issue later if you'd like changes made

**Comment by tutgreco** [comment]
As per discord message asking for lettering to be fixed, can you please send your design as .psd so that I can resolve it for you.

I require the lettering and anything else out of order to be separate layers from the template, otherwise it'll be too much work to fix.
@raafet12

**Comment by raafet12** [comment]
@tutgreco I'm sorry for the late response. link design http://www.mediafire.com/file/gq3ixl41wnthvcf/PSD.psd/file

**Comment by tutgreco** [comment]
Ok, a fix is being pushed and issue will be marked completed when live.

**Comment by tutgreco** [comment]
I have uploaded my fix.
