### ISSUE TITLE
Sentinel & Shamal Generic Wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#471]
I'd like to request a generic wrap for my sentinel and shamal.
**Name for wrap**
dhiamlaih_1
![template](https://user-images.githubusercontent.com/60038193/181378408-c2598e0d-e48b-4416-a498-cf822b815f92.png)

https://saesrpg.uk/topic/33135/liyones-reward-change

**Comment by tut98** [comment]
The first one is custom as it's following a template

**Comment by Liyones** [comment]
> 

i think it's fine now

**Comment by tut98** [comment]
On its way as `abstract1`
