### ISSUE TITLE
Landstalker Custom Wrap

### ISSUE THREAD

**Issue by Liyones** [saesrpg/donation-vehicle-shaders#472]
**Vehicle ID**
400

**Wrap access**
dhiamlaih

**Thread for reward change**
https://saesrpg.uk/topic/33135/liyones-reward-change

**Translations**
N/A

**Wrap image**
![template](https://user-images.githubusercontent.com/60038193/181396641-33e3b891-c2d6-444b-998c-42584d059131.png)

**Comment by tut98** [comment]
On its way as `dhiamlaih_2`
