### ISSUE TITLE
Corpsegrinder's Infernus wraps

### ISSUE THREAD

**Issue by corpseginder** [saesrpg/donation-vehicle-shaders#475]
**Vehicle ID**
411

**Wrap access**
corpsegrinder

**Thread for reward change**
https://saesrpg.uk/topic/33183/donation-undefined-amount-20-00-gbp

**Translations**
N/A

**Wrap image**
![rnoBwQt](https://user-images.githubusercontent.com/109925418/182043675-c3fb0b6f-fe78-436b-ae4b-dfc5d96ed23e.png)
![DsT86na](https://user-images.githubusercontent.com/109925418/182043683-4313d2a4-cf2f-4dee-8b0b-389fdcd429ea.png)
![QsYAuXf](https://user-images.githubusercontent.com/109925418/182043689-295bf288-edc4-481c-980b-8b6ed2707da1.png)

**Comment by tut98** [comment]
On their way as `corpsegrinder_2` through `corpsegrinder_4`
