### ISSUE TITLE
Versace's Custom Wrap

### ISSUE THREAD

**Issue by Versace0** [saesrpg/donation-vehicle-shaders#477]
**Vehicle ID**
502

**Wrap access**
kinggamer

**Thread for reward change**

**Translations**

**Wrap image**
![502 (1)](https://user-images.githubusercontent.com/96533575/182428959-0aaf08a8-e407-4d33-9295-aa01fce3cd13.png)

**Comment by tut98** [comment]
Please upload with 512x512 image size

**Comment by Versace0** [comment]
fixed

**Comment by tut98** [comment]
On its way as `kinggamer_1`
