### ISSUE TITLE
RenQ's Custom Wrap Request

### ISSUE THREAD

**Issue by renq1** [saesrpg/donation-vehicle-shaders#48]
Vehicle Name: Sultan
Vehicle ID: 560
Custom wrap:
https://imgur.com/a/PRkHWB6

**Comment by tutgreco** [comment]
Adding as public wrap since you did not specify any usernames. On issue closing, it marks that your wrap is live.

**Comment by renq1** [comment]
Wrap access locked to usernames (leave blank if public): skirillex
@tutgreco

**Comment by tutgreco** [comment]
Ok thanks for updating me on this. :+1:

**Comment by tutgreco** [comment]
Wrap added as 'skirillex_1'
