### ISSUE TITLE
Rondaw Custom wraps

### ISSUE THREAD

**Issue by MrRondaw01** [saesrpg/donation-vehicle-shaders#485]
### Wrap 1
**Vehicle ID**
400

**Wrap access**
league1

**Translations**
N/A

**Wrap image**
![template](https://user-images.githubusercontent.com/110779926/183499928-0d28ba0c-3dd4-44d6-b3b5-70e55db33c31.png)

### Wrap 2
**Vehicle ID**
541

**Wrap access**
league1

**Translations**
N/A

**Wrap image**
![remap_body](https://user-images.githubusercontent.com/110779926/183508985-a75c65b9-d750-4a8f-a75b-b6b86a7fc97c.png)

### Wrap 3
**Vehicle ID**
506

**Wrap access**
league1

**Translations**
N/A

**Wrap image**
![template](https://user-images.githubusercontent.com/110779926/183509357-d8f9d16a-a1f7-47f4-8491-906e40a35505.png)

### Wrap 4
**Vehicle ID**
402

**Wrap access**
league1

**Translations**
N/A

**Wrap image**
![template](https://user-images.githubusercontent.com/110779926/183509533-5e664847-f3fb-48b3-af81-4d590b60c78e.png)

### Wrap 5
**Vehicle ID**
561

**Wrap access**
league1

**Translations**
N/A

**Wrap image**
![template_AudiRs7](https://user-images.githubusercontent.com/110779926/183509799-437faf15-cf4d-414f-838e-cd6788ec2224.png)

### Wrap 6
**Vehicle ID**
466

**Wrap access**
league1

**Translations**
N/A

**Wrap image**
![template_glenshit](https://user-images.githubusercontent.com/110779926/183510332-cab88905-cf64-4bb5-92fc-81f08cf36898.png)

**Reward Change**
https://saesrpg.uk/topic/33261/rondaw-x01-reward-change

**Comment by tut98** [comment]
On their way as `league1_5` through `league1_10`
