### ISSUE TITLE
Youssef's costume warp

### ISSUE THREAD

**Issue by youssef-bb** [saesrpg/donation-vehicle-shaders#486]
**Vehicle ID**
598

setttheboss

**Thread for reward change**
https://saesrpg.uk/topic/33257/youssef-s-reward-change

**Translations**
Ohayo=hi

**Wrap image**

![blizz work](https://user-images.githubusercontent.com/93038475/183691975-6f71b053-6dfa-42d7-9c8c-bede079e5ee7.png)

Note: U can remove setttheboss_3 as i won't use it anymore i replace it with this if u can 
https://github.com/saesrpg/donation-vehicle-shaders/issues/356

**Comment by tut98** [comment]
Sorry, emergency vehicles are not yet ready for civilian use
