### ISSUE TITLE
Steve's custom wraps

### ISSUE THREAD

**Issue by steeveeeeee** [saesrpg/donation-vehicle-shaders#487]
**_WRAP 1  (Steve_BAT1 )_**

**Vehicle ID** 528 (FBI truck)

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A
**Wrap image** 
![base (1)](https://user-images.githubusercontent.com/110913436/184038203-383051c2-bb12-4579-8e90-865e11d3fa0e.png)

**_WRAP 2 ( Steve_BAT2 )_**

**Vehicle ID** 490 (FBI Rancher)

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template (4)](https://user-images.githubusercontent.com/110913436/184038268-dcea732e-37bb-4c26-a21e-a86de96299e8.png)

**_WRAP 3 ( Steve_p1 )_**

**Vehicle ID** 490 (FBI Rancher)

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template (3)](https://user-images.githubusercontent.com/110913436/184038285-6063c8de-38f0-4a27-8ccf-7d7649e338b1.png)

**_WRAP 4 ( Steve_bob1 )_**

**Vehicle ID** 490 (FBI Rancher)

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template](https://user-images.githubusercontent.com/110913436/184038298-e525f256-6b15-4a3a-907f-13ac4c319d6e.png)

**_WRAP 5 ( Steve_p2 )_**

**Vehicle ID** 582 ( News van Police )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template_newsvan (2)](https://user-images.githubusercontent.com/110913436/184038305-9b002f3e-b343-4fd5-a2f2-9acbdb2708d2.png)

**_WRAP 6 ( Steve_bob2 )_**

**Vehicle ID** 582 ( News van Police )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template_newsvan (1)](https://user-images.githubusercontent.com/110913436/184038316-7254a43e-fdb9-483c-b383-5a7ecfbae009.png)

**_WRAP 7 ( Steve_m1 )_**

**Vehicle ID** 598 ( Police LV )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![liyones (1)](https://user-images.githubusercontent.com/110913436/184038320-e122d93e-4818-46bf-8e27-cd90a55634ba.png)

**_WRAP 8 ( Steve_bob3 )_**

**Vehicle ID** 598 ( Police LV )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![liyones](https://user-images.githubusercontent.com/110913436/184038336-60246505-749c-4070-a69d-566f610f42e4.png)

**_WRAP 9 ( Steve_p3 )_**

**Vehicle ID** 598 ( Police LV )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![liyones (2)](https://user-images.githubusercontent.com/110913436/184038351-b27d974f-2fbe-4f24-a12f-65f8276cf3bf.png)

**_WRAP 10 ( Steve_p4 )_**

**Vehicle ID** 596 ( Police LS )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template (5)](https://user-images.githubusercontent.com/110913436/184038371-f466d554-f4f4-43ee-8d43-ada13655a9fc.png)

**_WRAP 11 ( Steve_m2 )_**

**Vehicle ID** 596 ( Police LS )

**Wrap access** ( kazmet - cyberghost - judyess )

**Thread for reward change** 

**Translations** N/A

**Wrap image** 
![template (2)](https://user-images.githubusercontent.com/110913436/184038382-610c1a13-a0ec-4d5e-bb78-ee04bf63dded.png)

**Comment by tut98** [comment]
Please upload the files directly to the github issue so that they embed

**Comment by steeveeeeee** [comment]
> Please upload the files directly to the github issue so that they embed

fixed

**Comment by tut98** [comment]
Wrap 2 and possibly other wraps are uploaded with image sizes of 390x390 - we only support 512x512 or 256x256

**Comment by Liyones** [comment]
![template](https://user-images.githubusercontent.com/60038193/184042724-6872fcd9-d899-42a7-a2ad-fe4fa4376f3f.png)
![template](https://user-images.githubusercontent.com/60038193/184042827-3bf879cc-2942-4937-bf43-3853dc0fe740.png)
![template](https://user-images.githubusercontent.com/60038193/184042880-e2cbb74e-1329-4132-b2cc-08bbe520878d.png)
![template_newsvan](https://user-images.githubusercontent.com/60038193/184042957-207c7b46-7f4b-43a9-a1c9-a16b954ccbed.png)
![template_newsvan](https://user-images.githubusercontent.com/60038193/184043169-7d3da056-914f-4487-9499-4b28a296cb04.png)
![liyones](https://user-images.githubusercontent.com/60038193/184043289-a9a1788e-3aaf-4828-86f9-49e4c9ea2df9.png)
![liyones](https://user-images.githubusercontent.com/60038193/184043823-2e588dec-a261-4f14-82d7-240d7a1c7f89.png)
![liyones](https://user-images.githubusercontent.com/60038193/184044074-9b2ac914-ea4d-48a9-a699-4f8b23184b1a.png)
![template](https://user-images.githubusercontent.com/60038193/184044266-6cd70a78-2509-45dc-989a-2ed697025ff7.png)
![template](https://user-images.githubusercontent.com/60038193/184044154-de656a15-6bda-4448-83c6-ebccb0078001.png)

**Comment by tut98** [comment]
On their way as `kazmet_1` through `kazmet_11`
