### ISSUE TITLE
King's Custom warp

### ISSUE THREAD

**Issue by keeper1023** [saesrpg/donation-vehicle-shaders#488]
**Warp 1 (wrap15)**

**Vehicle ID** 506 (Super GT)

**Wrap access** ( theking01 )

**Thread for reward change**

**Translations** N/A

**Wrap image**

![alt text](https://cdn.discordapp.com/attachments/926466646380511242/1006665453525020782/wrap15.png)

**Comment by tut98** [comment]
On its way as `theking01_1`
