### ISSUE TITLE
Sanfara's Custom Wrap Request #2

### ISSUE THREAD

**Issue by Sanfara44** [saesrpg/donation-vehicle-shaders#489]
**Vehicle ID**
482

**Wrap access**

Only Me.

**Thread for reward change**
https://saesrpg.uk/topic/33336/sanfara-s-reward-change

**Translations**
N/A everything is in english.

**Wrap image**
![20220812_163119](https://user-images.githubusercontent.com/68815648/184459963-2299df07-3bc6-4b2d-a684-e6e8e9c226c3.png)

**Comment by tut98** [comment]
On its way as `midoprock_2`

**Comment by Sanfara44** [comment]
Wrap is added.
Issue need to be closed, thanks.
