### ISSUE TITLE
Sollozzo's custom wrap request

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#49]
Vehicle name : Police LV GTA V
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): sollozzo, rabhirr, colonelsemih76
TXN ID: 7CS02182V03617825
Image : https://i.imgur.com/8uyQWWx.png

**Comment by tutgreco** [comment]
Wrap added as 'sollozzo_2'
