### ISSUE TITLE
GM wrap for organization name

### ISSUE THREAD

**Issue by reketitekkep6hjus** [saesrpg/donation-vehicle-shaders#491]
**Vehicle ID**
519
**Wrap name**
gang_thc
**Needs testing**
No

**Wrap image**

![remap45](https://user-images.githubusercontent.com/109255441/185761166-6c96cd6b-7176-457f-979b-68af56280e97.png)

**Comment by reketitekkep6hjus** [comment]
edited the image, added thc logo

**Comment by Liyones** [comment]
Askers?
