### ISSUE TITLE
kemet (Cargobob)

### ISSUE THREAD

**Issue by jordskjelv** [saesrpg/donation-vehicle-shaders#492]
**Vehicle ID**

548
**Wrap access**

**Thread for reward change**

https://saesrpg.uk/topic/33462/donation-undefined-amount-30-00-gbp
**Translations**

80 ОДШБР
80 air assault brigade

Завжди першi
Always the first ones
https://cdn.discordapp.com/attachments/806297191953989642/1011608682167021699/mta-screen_2022-08-23_15-11-16.png
**Wrap image**

![template_cargobob](https://user-images.githubusercontent.com/111872610/186156815-51438031-01b6-42be-ac5c-77f62819c751.png)

**Comment by tut98** [comment]
Please upload with 512x512 image dimensions

**Comment by jordskjelv** [comment]
![186156815-51438031-01b6-42be-ac5c-77f62819c751](https://user-images.githubusercontent.com/111872610/186462888-f4aa8962-8fb8-4517-97d9-2aa012ec4d89.png)

**Comment by tut98** [comment]
On its way as `kemet_1` locked to nobody
