### ISSUE TITLE
theking01 warp

### ISSUE THREAD

**Issue by keeper1023** [saesrpg/donation-vehicle-shaders#493]
**Vehicle ID**
477 and 582

**Wrap access**

**Thread for reward change**
https://saesrpg.uk/topic/33464/king-s-reaward-change?_=1661262392400
**Translations**

**Wrap image**
![alt text](https://cdn.discordapp.com/attachments/926466646380511242/1009864807131906258/wrap2.png)
![alt text](https://cdn.discordapp.com/attachments/926466646380511242/1011936587547947028/test1.png)

**Comment by tut98** [comment]
On their way as `theking01_2` and `theking01_3` locked to nobody
