### ISSUE TITLE
Fandi's Custom wraps

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpg/donation-vehicle-shaders#494]
**Vehicle ID** 402 / 559

**Wrap access** 

Fandi123_9
Fandi123_10

**Thread for reward change**

**Translations**

**Wrap image**

![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3930353237383031373234373533313035382f3932353435363233393138343437383239382f646a616e676f6f6f6f6f6f2e706e67](https://user-images.githubusercontent.com/104403749/189489860-f4dd616a-138e-44ef-93e9-bcaec1982258.jpg)

![68747470733a2f2f692e696d6775722e636f6d2f734d636c4a65452e706e67(1)](https://user-images.githubusercontent.com/104403749/188943664-a651a3cb-de1a-46a5-bcd2-3ac3357837e9.jpg)

**Comment by tut98** [comment]
The images are a bit mixed up, the last one is ID 402, and the first image is neither 402 or 559

**Comment by FandiMohammed** [comment]
hello Sir 
 the first image is 559 
the the other is 402

**Comment by tut98** [comment]
Ah you are right. ID 559 just needs to be rotated 90 degrees anti-clockwise so that it's facing to the left

**Comment by FandiMohammed** [comment]
i can fix it if u want

**Comment by tut98** [comment]
Thanks that'd be great. For future reference we prefer that the first post has the fixed images in case anything pops up in the future

**Comment by FandiMohammed** [comment]
ok  Sir

**Comment by FandiMohammed** [comment]
Hello sir 

 Any news with the warps

**Comment by tut98** [comment]
Once ID 559 image gets flipped to the left (anti-clockwise) it'll be good to go

**Comment by steven517** [comment]
Why do you always have the templates always rotated and flipped @FandiMohammed ? just leave them the way they are and edit them like that

**Comment by FandiMohammed** [comment]
![Uploading template_supra(2).jpg…]()

**Comment by FandiMohammed** [comment]
![Uploading 68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3930353237383031373234373533313035382f3932353435363233393138343437383239382f646a616e676f6f6f6f6f6f2e706e67.jpg…]()

**Comment by FandiMohammed** [comment]
Fixed

@steven517

**Comment by steven517** [comment]
wraps on their way as `fandi123_9` and `fandi123_10`

**Comment by FandiMohammed** [comment]
any news sir

**Comment by tut98** [comment]
done @FandiMohammed
