### ISSUE TITLE
Royal's Custom Wrap

### ISSUE THREAD

**Issue by FirasJerbi20** [saesrpg/donation-vehicle-shaders#495]
**Vehicle ID**
561

**Wrap access**
patronxd

**Thread for reward change**
https://saesrpg.uk/topic/33685/royal-s-reward-change

**Translations**
N/A

**Wrap image**
![xroyal1](https://user-images.githubusercontent.com/111855740/191763708-305e035b-5c17-42f9-beab-dab5422070a5.png)

**Comment by tut98** [comment]
On its way as `patronxd_1`
