### ISSUE TITLE
Liberty hs  custom wrap 

### ISSUE THREAD

**Issue by mag1kSS** [saesrpg/donation-vehicle-shaders#498]
**Vehicle ID** 400

**Wrap access** mag1ks

**Thread for reward change** https://saesrpg.uk/topic/33977/liberty-reward-change

**Translations**

**Wrap image**
![pngegg-5 (2)](https://user-images.githubusercontent.com/84975890/197292082-ea7743b9-86cc-42cc-8175-12519fa74cba.png)

**Comment by tut98** [comment]
Images needs to be submitted as 512x512 size.

**Comment by mag1kSS** [comment]
@tut98 updated

**Comment by tut98** [comment]
On its way as `mag1ks_3`
