### ISSUE TITLE
Chasin's donation wraps

### ISSUE THREAD

**Issue by ChasinTLSN** [saesrpg/donation-vehicle-shaders#499]
**Vehicle ID**
494, 541, 411, 549, 519

**Wrap access**
decrypter1

**Thread for reward change**
https://saesrpg.uk/topic/34028/chasin-s-reward-change

**Translations**

**Wrap image**
![bemm](https://user-images.githubusercontent.com/48862898/198368301-a32c8c60-3c25-4fe3-a3de-234dc4ac280c.png)
![Bullet-3](https://user-images.githubusercontent.com/48862898/198367700-c46e1f2e-e3db-43bb-a6e7-d6a6a0e9f201.png)
![Infernus_2512](https://user-images.githubusercontent.com/48862898/198368060-226c5b07-47f1-44a7-8616-cb02b475c768.png)
![tampa](https://user-images.githubusercontent.com/48862898/198368421-c8a749c6-d837-424e-819f-8dc6c0596b31.png)
![remap](https://user-images.githubusercontent.com/48862898/198368519-39e34ca7-6529-4b55-a585-cb59bbf144ed.png)

**Comment by tut98** [comment]
On their way as `decrypter1_1` through `decrypter1_5`. For future uploads please make sure wraps has no transparencies.
