### ISSUE TITLE
Radio's Custom Wrap for Turisimo

### ISSUE THREAD

**Issue by radiogithub** [saesrpg/donation-vehicle-shaders#5]
Vehicle ID: 451
Wrap access locked to usernames (leave blank if public): Wrap locked to [AA]Radio, accountname = radiodude

My donation car is located at my property in LV near the warehouse 1 Ninja Sword Street

![turismo](https://user-images.githubusercontent.com/50849604/58155760-77d0de00-7c6c-11e9-85f6-532cf139f4aa.png)

**Comment by tutgreco** [comment]
your wrap has been added.
