### ISSUE TITLE
Terry - Custom Wrap Request

### ISSUE THREAD

**Issue by TheMetalizer** [saesrpg/donation-vehicle-shaders#50]
Vehicle Name: Burrito
Vehicle ID: 482
Wrap access locked to usernames (leave blank if public): rizacem

https://imgur.com/a/XFUL0ry

**Comment by tutgreco** [comment]
Preview: https://imgur.com/a/wrDHqE6

**Comment by TheMetalizer** [comment]
@tutgreco 

Fixed 
https://imgur.com/a/fsgv3qz

**Comment by tutgreco** [comment]
Wrap added as 'rizacem_1'
