### ISSUE TITLE
Youssef's costume warp 

### ISSUE THREAD

**Issue by youssef-bb** [saesrpg/donation-vehicle-shaders#500]
**Vehicle ID**
411

**Wrap access**
setttheboss

**Thread for reward change**
https://saesrpg.uk/topic/34160/youssef-s-reward-change

**Translations**
n/a

**Wrap image** (Can u please resize it to 512x512 because i coulden't , i'll be appreciate)
![PEwLd3g - Imgur](https://user-images.githubusercontent.com/93038475/200380582-008c4e04-d19f-413b-a56d-7a73149dde8c.png)

**Comment by tut98** [comment]
It depends on which image app you are using but it should be under 'image > size'.
On its way as `setttheboss_6`
