### ISSUE TITLE
KodigoCustom Wrap

### ISSUE THREAD

**Issue by kodigo21** [saesrpg/donation-vehicle-shaders#501]
**Vehicle ID** 506 - 400 - 604 - 561

**Wrap access** eduuh96

**Thread for reward change**
https://saesrpg.uk/topic/34219/kodigo-reward-change

**Wrap image**

Super GT - 506:
![superGT_outfit](https://user-images.githubusercontent.com/96799401/201521795-96394345-75ad-4372-9d1e-441376c80eec.png)

Landstalker - 400:
![template](https://user-images.githubusercontent.com/96799401/201521815-bcb61e42-2c05-4d5c-8767-4b7588ae003f.png)

Glendale Damaged - 604:
![129613561-a7490fb2-f49a-4f19-b019-140e260f4f54](https://user-images.githubusercontent.com/96799401/201521884-9669d147-08b6-44f5-9c6b-4838c226ea0e.png)

Stratum - 561
![template_AudiRs7](https://user-images.githubusercontent.com/96799401/201521965-bf34bc21-4197-4fc3-b9ca-b40caebab523.png)

**Comment by tut98** [comment]
On their way as `eduuh96_21` through `eduuh96_24`. For future uploads please ensure all images have a solid color as background
