### ISSUE TITLE
BOPE WRAP

### ISSUE THREAD

**Issue by samuel3021** [saesrpg/donation-vehicle-shaders#502]
**Vehicle ID**
1 Stratum 411
2 Cheetah 415
**Wrap access**
Samuel3021
**Thread for reward change**
https://saesrpg.uk/topic/34243/bope-wrap

Wras 
https://imgur.com/a/IyZEody

**Comment by tut98** [comment]
@samuel3021 it seems your request doesn't have any images

**Comment by samuel3021** [comment]
> @samuel3021parece que seu pedido não tem imagens

I just added

**Comment by tut98** [comment]
On their way as `samuel3021_18` and `samuel3021_19`
