### ISSUE TITLE
reket custom wrap

### ISSUE THREAD

**Issue by reketitekkep6hjus** [saesrpg/donation-vehicle-shaders#503]
**Vehicle ID** 400

**Wrap access** mikupro, mag1ks

**Thread for reward change** https://saesrpg.uk/topic/34305/liberty-reward-change

**Translations** None

**Wrap image**
![maybefinal](https://user-images.githubusercontent.com/109255441/202846518-c7fd5193-b53f-4448-a7a7-41be3a4eff08.png)

**Comment by tut98** [comment]
On its way as `mikupro_1`

**Comment by reketitekkep6hjus** [comment]
edited, added mag1ks under wrap access

**Comment by tut98** [comment]
Sorry it's already live, if you add your username to their vehicle ingame it'll be able to get the wrap
