### ISSUE TITLE
Douglass's custom wrap

### ISSUE THREAD

**Issue by manuel4693** [saesrpg/donation-vehicle-shaders#504]
**Vehicle ID:** 411 & 402

**Wrap access:** subkage, felixovalles12

**Thread for reward change:** https://saesrpg.uk/topic/34361/donation-douglas?_=1669599090838

**Translations:** ''No subo gordas'' = i don't ride fat girls. [**SS**](https://i.imgur.com/go2MZ16.png)

**Wrap image**
Buffalo (402) [Link](https://i.imgur.com/sLmD27Z.png)
Infernus(411) [Link](https://i.imgur.com/EPzzdG4.png)

**Comment by tut98** [comment]
That's just twisting it really, have to put something else

**Comment by manuel4693** [comment]
... ''No subo banqueras'' = i don't ride moms

**Comment by tut98** [comment]
It's fine

**Comment by manuel4693** [comment]
https://i.imgur.com/nomM5QR.png

**Comment by tut98** [comment]
Infernus on its way as `subkage_2`, Buffalo as `subkage_3`

**Comment by manuel4693** [comment]
Nothing yet?

**Comment by tut98** [comment]
live @manuel4693
