### ISSUE TITLE
Henry's custom wrap request

### ISSUE THREAD

**Issue by SAESHenry** [saesrpg/donation-vehicle-shaders#52]
**For Custom wrap request :**
Vehicle name: Buffalo (GTR34)
Vehicle ID: 402 
Wrap access locked to usernames (leave blank if public): mierburns

https://i.imgur.com/PJWiiIJ.png

I'd like to see how it looks if possible, thanks!

**Comment by tutgreco** [comment]
https://imgur.com/a/VY6gDyR

**Comment by SAESHenry** [comment]
I have attempted to fix the rear a bit, and it would be ready for upload, thanks!

https://imgur.com/a/GKzn3H3

**Comment by tutgreco** [comment]
wrap is added as mierburns_1
