### ISSUE TITLE
Stark's Custom wrap request

### ISSUE THREAD

**Issue by OG-Stark** [saesrpg/donation-vehicle-shaders#53]
**Vehicle ID**  560

**Wrap access** jt16

**Needs testing** Yes

**Image color profile** RGB

https://i.imgur.com/tiPSCgG.png

**Comment by Ahmed-khayry** [comment]
@tutgreco 
removed the black blot on the car hood
https://i.ibb.co/r3jQjTY/sultan.png

**Comment by tutgreco** [comment]
https://imgur.com/a/22lD6NM

**Comment by OG-Stark** [comment]
Awesome, i love it.

**Comment by OG-Stark** [comment]
Can i request it @tutgreco ?

**Comment by tutgreco** [comment]
We're add the 'completed' label on the issue once the wrap is on server

**Comment by OG-Stark** [comment]
alright, let me know, thanks

**Comment by tutgreco** [comment]
wrap is added as jt16_1
