### ISSUE TITLE
Velona's Custom Wrap Request

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#54]
**Vehicle ID** : 494

**Wrap access** : velona77, rizacem, zizi31

**Needs testing** : Yes, please.

**Image color profile** : RGB

![template](https://user-images.githubusercontent.com/46403782/78503508-a31ec780-776f-11ea-88d7-120a7fbf4a09.png)

**Comment by tutgreco** [comment]
https://imgur.com/a/omHBMht

**Comment by Velona77** [comment]
It looks fine, thanks. I'd like to have it ingame.

**Comment by tutgreco** [comment]
Wrap added as `velona77_1`
