### ISSUE TITLE
Jim's custom wrap

### ISSUE THREAD

**Issue by Jim4222** [saesrpg/donation-vehicle-shaders#55]
**Vehicle ID**
562

**Wrap access**
oximan42

**Needs testing**
Yes

**Image color profile**
RGB

![](https://i.imgur.com/5q98Im7.png)

**Comment by tutgreco** [comment]
Correct ID is 436. Please use https://wiki.multitheftauto.com/wiki/Vehicle_IDs to get the right ID.

**Comment by Jim4222** [comment]
I thought it was for the Elegy: https://imgur.com/a/87FDf4x

But if it is oke for. I only changed the color of the vehicle.

New one: https://imgur.com/a/JmTLjU1

**Comment by tutgreco** [comment]
Thanks it has been corrected on the thread.

**Comment by tutgreco** [comment]
Are you still interested in having this wrap added?

**Comment by tutgreco** [comment]
Seems not, closing. Feel free to reopen should you be interested.
