### ISSUE TITLE
Custom Wrap Test - NYFD 407

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#57]
Just for testing please, do not upload yet.

**Vehicle ID**
407 Firetruck (NYFD)

**Wrap access**
bardo45 (me)

**Needs testing**
Yes

**Image color profile**
https://i.imgur.com/fa4uYJk.png

**Comment by tutgreco** [comment]
https://imgur.com/a/VQBKiat

**Comment by bardo45** [comment]
Looks cool, think it's ready to be uploaded.

**Comment by tutgreco** [comment]
Wrap added as `bardo45_1`. We'll add a patch for fire truck letting you color the rims.
