### ISSUE TITLE
LandShark's Custom Wrap Request

### ISSUE THREAD

**Issue by LandSharkSAFP** [saesrpg/donation-vehicle-shaders#58]
**Vehicle ID**
598

**Wrap access**
landsharkppppp

**Needs testing**
Yes

**Image color profile**
RGB

https://imgur.com/ONmXNh8

**Comment by tutgreco** [comment]
https://imgur.com/a/canjLp0

When done, please submit with image resolutions of either 256x256, 512x512 or 1024x1024 (your image quality must justify 1024x1024, if this can't be done, please downscale to 512x512)

**Comment by LandSharkSAFP** [comment]
Okay, I'll try to fix it tonight

**Comment by LandSharkSAFP** [comment]
https://imgur.com/a/lo9txBV

**Comment by tutgreco** [comment]
https://streamable.com/rmcd3i

**Comment by LandSharkSAFP** [comment]
Looks good, ready to upload

**Comment by tutgreco** [comment]
Wrap added as `landsharkppppp_1`
