### ISSUE TITLE
Velona's Custom Wrap Request

### ISSUE THREAD

**Issue by Velona77** [saesrpg/donation-vehicle-shaders#59]
**Vehicle ID** : 451

**Wrap access**

**Needs testing** : Yes

**Image color profile** : RGB
![Lambo](https://user-images.githubusercontent.com/46403782/79542630-a762b300-8094-11ea-8386-5748923c0d39.png)

**Comment by tutgreco** [comment]
https://imgur.com/a/b2hkLCG
If you send the PSD I'll have it fixed by next week, if you want to clear yourself of the hassle to get it precise

**Comment by Velona77** [comment]
@tutgreco There's the PSD file, would be appreciated. https://www.dropbox.com/s/e4x15nckhf4iyxj/Lambo.psd?dl=0

**Comment by tutgreco** [comment]
fixed wrap is on its way to live

**Comment by tutgreco** [comment]
Wrap added as `velona77_2`
