### ISSUE TITLE
Custom wrap request

### ISSUE THREAD

**Issue by DemienD** [saesrpg/donation-vehicle-shaders#6]
For Custom wrap request :
Vehicle ID: 598
Wrap access locked to usernames (leave blank if public): dyam98, hassoni, firefox201791

![image](https://user-images.githubusercontent.com/15146566/58728697-c1959300-83e7-11e9-98c1-3712ce755387.png)

**Comment by DemienD** [comment]
![FOX-PoliceLV-shader](https://user-images.githubusercontent.com/15146566/58728925-484a7000-83e8-11e9-8311-1b2dea8a2c31.png)

**Comment by DemienD** [comment]
PS: requested it in the comment here as a car wasn't placed https://saesrpg.uk/topic/8609/dyam-s-reward-change

**Comment by tutgreco** [comment]
would you like it tested or added as soon as possible? @DemienD

**Comment by DemienD** [comment]
Whatever you think is best ;)

**Comment by tutgreco** [comment]
please horizontally mirror the bonnet text (FOX operations). also, the background color should be similar to the borders of the wrap, so a grey ish would be fine.

**Comment by DemienD** [comment]
Text on the hood was mirrored on purose. I can't figure out how to match the background color using the template provided. The only way I found was to hide both the template and shadows layer and I'm not certain if that's the way to do it. Perhaps you could [download my PSD](https://stack.demiendrost.nl/s/ZU7tt6e9enY0WDT) and take a look. Thanks again

**Comment by tutgreco** [comment]
double clicking the color fill layer allows you to change it;
https://cdn.discordapp.com/attachments/308955200876707840/585175331435053056/Skrmbillede_5349.png
I chose not to, as your wrap template seem to be using fonts that i don't have on this PC.

**Comment by DemienD** [comment]
![FOX-PoliceLV-shader](https://user-images.githubusercontent.com/15146566/59551896-bb271f80-8f80-11e9-9334-e93471f05938.png)
