### ISSUE TITLE
vektor's Custom Wrap Request

### ISSUE THREAD

**Issue by vekkiee** [saesrpg/donation-vehicle-shaders#61]
**Vehicle ID** : 598

**Wrap access** : vektor

**Needs testing** : Yes

**Image color profile** RGB

![vektor](https://user-images.githubusercontent.com/64019325/79756135-d2facd00-8322-11ea-9117-ebb5b558a636.png)

**Comment by tutgreco** [comment]
As written on discord, wraps need to represent police departments
