### ISSUE TITLE
Jona/Halo custom Wrap

### ISSUE THREAD

**Issue by jonathan959** [saesrpg/donation-vehicle-shaders#63]
**Vehicle ID**
598

**Wrap access**
"buch", "mrslowguy", "jonathan959"

**Needs testing**
yes

**Image color profile**
RGB
https://imgur.com/a/YwGqu59

**Comment by jonathan959** [comment]
Hey, I think it is fixed now, but I got a question regarding the unit number. If we want to have the same shader but different unit numbers, can that be possible or is it a long and tedious process? 
https://imgur.com/a/mZCdjmS

**Comment by tutgreco** [comment]
Having different unit number requires a separate wrap, as the text is included in the template. Would you like them tested?

**Comment by jonathan959** [comment]
Hey tut we just want this one to be approved so we can duplicate it with different unit numbers

**Comment by tutgreco** [comment]
596: https://imgur.com/a/v8WqiVG
598: https://imgur.com/a/u8w44qs

**Comment by jonathan959** [comment]
It looks good but the charger doesnt have the supervisor on the back, apart from that it looks good

**Comment by tutgreco** [comment]
Do you want them added now?

**Comment by jonathan959** [comment]
yes please

**Comment by tutgreco** [comment]
@jonathan959 
596 template was updated, get the latest here:
https://saesrpg.uk/topic/8309/about-donation-wraps

It underwent many changes, making your current wrap unusable. I'll leave the thread open for a month. If you prefer to not submit an updated version, we'll have to remove it.
