### ISSUE TITLE
Dawis67's custom wrap

### ISSUE THREAD

**Issue by Mondea** [saesrpg/donation-vehicle-shaders#64]
**Vehicle ID** 515, Roadtrain
 

**Wrap access** Dawis67
 

**Needs testing** Yes, idk how it looks ingame yet.
 

**Image color profile** IDK, probably sRGB
 

https://imgur.com/a/5sT3v8j

**Comment by tutgreco** [comment]
515: https://imgur.com/a/1WJub8F

**Comment by Mondea** [comment]
Thanks, ill edit the skin a bit more

**Comment by Mondea** [comment]
I think this will be final one. https://imgur.com/a/FhhJXCu

**Comment by tutgreco** [comment]
Do you want it tested?

**Comment by Mondea** [comment]
Yes

**Comment by tutgreco** [comment]
515: https://imgur.com/a/4UoDJEC

**Comment by Mondea** [comment]
That is good. You can publish it.

**Comment by tutgreco** [comment]
It seems that your wrap is on server now. I'm sorry for the delay.
