### ISSUE TITLE
SAFP Stoner's Custom Wrap Request

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/donation-vehicle-shaders#65]
**Vehicle ID**
598 Police LV

**Wrap access**
MrSlowGuy (Please do this for all my previous wraps as well if you have time)

**Needs testing**
To be safe, yes. 

**Image color profile**
N/A / Don't know

![V116S](https://user-images.githubusercontent.com/62346746/80299054-3d0dda80-8746-11ea-8f3a-49e96faeb756.png)
___
![R951S](https://user-images.githubusercontent.com/62346746/80299108-a2fa6200-8746-11ea-91a8-73fca6b4f1d1.png)
___
![B975S](https://user-images.githubusercontent.com/62346746/80299117-b86f8c00-8746-11ea-923b-9b8497842b97.png)
___
![D034S](https://user-images.githubusercontent.com/62346746/80299120-bc031300-8746-11ea-992d-e4ceaf43ea6b.png)
___
![A024S](https://user-images.githubusercontent.com/62346746/80299122-bdccd680-8746-11ea-9084-385c1c1b6395.png)

**Vehicle ID**
596 Police LS

**Wrap access**
MrSlowGuy

**Needs testing**
To be safe, yes. 

**Image color profile**
N/A / Don't know

![V116SV](https://user-images.githubusercontent.com/62346746/80299164-1dc37d00-8747-11ea-9ea1-70a0c102ab9b.png)

**Comment by tutgreco** [comment]
596: https://imgur.com/a/fZyyU6w
598: https://imgur.com/a/HjiRRiG

**Comment by MrSlowGuy** [comment]
Looks good, Tut!

**Comment by tutgreco** [comment]
Added as `mrslowguy_4` up to `mrslowguy_9`

**Comment by tutgreco** [comment]
@MrSlowGuy 
596 template was updated, get the latest here:
https://saesrpg.uk/topic/8309/about-donation-wraps

It underwent many changes, making your current wrap unusable. I'll leave the thread open for a month. If you prefer to not submit an updated version, we'll have to remove it.

**Comment by MrSlowGuy** [comment]
All of these need fixing. Will update soon.

**Comment by tutgreco** [comment]
Hello @MrSlowGuy I'd just like to follow up, have you made any progress with the wraps?

**Comment by tutgreco** [comment]
I'm closing this, please reopen should you regain interest in sorting the wraps @MrSlowGuy
