### ISSUE TITLE
Custom Wrap Fix

### ISSUE THREAD

**Issue by bardo45** [saesrpg/donation-vehicle-shaders#71]
https://github.com/saesrpg/donation-vehicle-shaders/issues/57
This wrap got named as my existing wrap so my Police LV got the shader of the firetruck now (Tut knows) 

Firetruck = bardo45_1
This one, bardo45_2 please.

**Vehicle ID**
598 Police LV (GTA5)

**Wrap access**
bardo45

**Needs testing**
Yes

**Image color profile**
https://i.imgur.com/jMbVoVt.png

**Comment by tutgreco** [comment]
598: https://imgur.com/a/B8NFxq7
note: emergency services wraps has to be readable in English

**Comment by bardo45** [comment]
https://i.imgur.com/QcW6StZ.png

**Comment by tutgreco** [comment]
598: https://imgur.com/a/lFRVwoL

**Comment by bardo45** [comment]
Final fix, got the trust that it's ready to be uploaded like this:
https://i.imgur.com/gESdem4.png

**Comment by tutgreco** [comment]
I'll need the text written in English, we can't have foreign paint on emergency vehicles in SA

**Comment by bardo45** [comment]
English version:
https://i.imgur.com/ETEHH1j.png

**Comment by tutgreco** [comment]
Wrap added as `bardo45_2`
