### ISSUE TITLE
Moley's Custom wrap Request 

### ISSUE THREAD

**Issue by Moley1** [saesrpg/donation-vehicle-shaders#72]
**Vehicle ID**
400 

**Wrap access**
DaToletha 

**Needs testing**
Yes 

**Image color profile**
https://i.imgur.com/Y1hqaxt.png

**Comment by tutgreco** [comment]
400: https://imgur.com/a/gEIZX14

**Comment by Moley1** [comment]
https://imgur.com/a/5IJ2tWR

**Comment by Moley1** [comment]
I would like to have this one in-game

**Comment by tutgreco** [comment]
Wrap added as `datoletha_1`
