### ISSUE TITLE
GJMC Costum Burrito

### ISSUE THREAD

**Issue by Klay683** [saesrpg/donation-vehicle-shaders#73]
**Vehicle ID** 482

**Wrap access** olp.bendhiab

**Needs testing** Yes

**Image color profile** https://imgur.com/a/oNxbbjk

**Comment by tutgreco** [comment]
482: https://imgur.com/a/7kH9Y1I

**Comment by Klay683** [comment]
good ya @tutgreco

**Comment by tutgreco** [comment]
Wrap added as `bendhiab_3`
