### ISSUE TITLE
SeBa´s custom wrap request

### ISSUE THREAD

**Issue by Saes-SeBa** [saesrpg/donation-vehicle-shaders#74]
**Vehicle ID**
451

**Wrap access**
seb123,bardo45

**Needs testing**
Yes

**Image color profile**
https://i.imgur.com/26uZkH8.png

**Comment by tutgreco** [comment]
451: https://imgur.com/a/Zaqc620

**Comment by Saes-SeBa** [comment]
Can you try this color instead? Thanks
https://i.imgur.com/wGCJLFn.png

**Comment by tutgreco** [comment]
451: https://imgur.com/a/SqansiC

**Comment by Saes-SeBa** [comment]
Perfect that is the one i want uploaded 👍

**Comment by tutgreco** [comment]
Ok, please send the version without lines and it'll be added

**Comment by Saes-SeBa** [comment]
Here you go: 

![](https://i.imgur.com/cIbdcCg.png)

**Comment by tutgreco** [comment]
Wrap was added as `seb123_1`
