### ISSUE TITLE
Divine's Custom Wrap

### ISSUE THREAD

**Issue by nobody-Loves-Me** [saesrpg/donation-vehicle-shaders#75]
Vehicle ID
494

Wrap access
divine and cavid

Needs testing
Yes

Image color profile
RGB
https://i.imgur.com/gxzioXH.png

**Comment by tutgreco** [comment]
Are you the owner of the donation?

**Comment by Daviddivine1** [comment]
> Are you the owner of the donation? If not, please forward the owner to request it instead.
> Owner is the one who pays for the wrap.

Greetings mister **tut**.

Here is the new link: https://github.com/saesrpg/donation-vehicle-shaders/issues/77

Sorry about that! 👍
