### ISSUE TITLE
Sanek's custom wrap

### ISSUE THREAD

**Issue by SanekFox** [saesrpg/donation-vehicle-shaders#76]
**Vehicle ID**
598

**Wrap access**
cahek23, dufabo1900, dalboeb

**Needs testing**
yes

**Image color profile**
https://imgur.com/fbZxV8L

**Comment by tutgreco** [comment]
598: https://imgur.com/a/vVlCdZA

**Comment by SanekFox** [comment]
598: (edited) https://imgur.com/a/u31wvrZ

**Comment by tutgreco** [comment]
Whenever you send the final version, please send it as either 512x512 or 1024x1024 (though ensure its quality justifies extra resolution as it greatly adds in size)
598: https://imgur.com/a/BDLIvtz

**Comment by SanekFox** [comment]
https://imgur.com/a/J9QquoM (1024*1024)

**Comment by tutgreco** [comment]
598: https://imgur.com/a/N4656Pe

**Comment by SanekFox** [comment]
last version) https://imgur.com/a/tJqG4Bl

**Comment by tutgreco** [comment]
Wrap added as `cahek23_2`, whereas your first wrap retains its name (from before the naming convention changed) `SheriffSanek`.

**Comment by tutgreco** [comment]
keeping it open til new usernames are sorted

**Comment by SanekFox** [comment]
Access to wrap has been open for login "dalboeb"

**Comment by tutgreco** [comment]
> Access to wrap has been open for login "dalboeb"

Sorted 👍
