### ISSUE TITLE
Divine's custom wrap (2)

### ISSUE THREAD

**Issue by Daviddivine1** [saesrpg/donation-vehicle-shaders#77]
Vehicle ID
494

Wrap access
divine and cavid

Needs testing
Yes

Image color profile
RGB
https://i.imgur.com/gxzioXH.png

**Comment by tutgreco** [comment]
494: https://imgur.com/a/el4doJO

**Comment by Daviddivine1** [comment]
Hej mister turtle,

Try this
https://i.imgur.com/mc1Qjz6.png

Takker, tut level 126.

**Comment by tutgreco** [comment]
494: https://imgur.com/a/3pWfFcU

**Comment by Daviddivine1** [comment]
> 494: https://imgur.com/a/3pWfFcU

It's fine! ;)

ty turtle, much appreciated.

**Comment by tutgreco** [comment]
Wrap added as `divine_1`
