### ISSUE TITLE
Felixizm Custom Wrap Request

### ISSUE THREAD

**Issue by RebelFelix** [saesrpg/donation-vehicle-shaders#79]
Vehicle ID
506
Wrap access
felixizm, byforce, qweasd2

Needs testing
No, there is similar wrap already existing.

Image color profile
https://imgur.com/a/eSa8Egf

**Comment by morde3** [comment]
hello dear @tutgreco , we'd like to add that in game.

**Comment by tutgreco** [comment]
Yes, the accepted label means it's currently in the process  to be uploaded. :+1:

**Comment by tutgreco** [comment]
Wrap is added as `felixizm_1`
