### ISSUE TITLE
Aurora's Custom Wrap Request

### ISSUE THREAD

**Issue by FBIAurora** [saesrpg/donation-vehicle-shaders#80]
**Vehicle ID**
596

**Wrap access**
jamesmpf

**Needs testing**
Yes

**Image color profile**
https://cdn.discordapp.com/attachments/708094903577739304/712439220836237342/crownvic.png

**Vehicle ID**
598

**Wrap access**
jamesmpf

**Needs testing**
Yes

**Image color profile**
https://cdn.discordapp.com/attachments/708094903577739304/712438529178730546/gtav.png

**Comment by tutgreco** [comment]
596: https://imgur.com/a/h9PwtU1
598: https://imgur.com/a/Zzj52M2

**Comment by FBIAurora** [comment]
I appreciate you testing it, I'll get with Velo and try to edit it a bit more. Another test to come soon my friend if you're up for it, not sure when it'll be ready

**Comment by FBIAurora** [comment]
Alright sir after so long Velo has worked so hard on it and I couldn't be more thankful; 

The Dodge Charger is ready to be added, it's fully ready and up. 
Image ID; 598
Color Profile; 714696502341009414

The Crown Vic needs a slight test as we can't figure out where the text will appear at for the trunk...so would it be possible to test it so we know where it's at?
Image ID; 596
Profile; https://cdn.discordapp.com/attachments/708094903577739304/714700585294889030/crownvic2.png

**Comment by tutgreco** [comment]
I'm aware of the issues with Crown Vic, and if need be I'll gladly look into resolving the wrap myself if you provide the .psd file.
596: https://imgur.com/a/l5nAvfJ

**Comment by tutgreco** [comment]
596 template has been updated, get the latest here: 
https://saesrpg.uk/topic/8309/about-donation-wraps

**Comment by tutgreco** [comment]
598 is added as `jamesmpf_1`

**Comment by tutgreco** [comment]
596 is added as `jamesmpf_2`
