### ISSUE TITLE
Richard's Custom Wrap

### ISSUE THREAD

**Issue by richard42050** [saesrpg/donation-vehicle-shaders#81]
Vehicle ID
451 ( The Police Cruiser / Police LV ) ( I'm not quite sure if it's the right ID of the car)

Wrap access
richardthekiller

Needs testing
Yes

Image color profile
https://cdn.discordapp.com/attachments/398519310798290944/712377219082616882/royals_lastyy.png

The donation will be done by AkyZ in the name of Richard.

**Comment by tutgreco** [comment]
Police LV ID is ID 598 according to the ID page provided with the "new issue" template.
Might want to bump up the resolution to at least 512x512 or 1024x1024.

598: https://imgur.com/a/FTSm4FT

**Comment by richard42050** [comment]
Vehicle ID
598 

Wrap access
richardthekiller

Needs testing
Yes

Image color profile
https://cdn.discordapp.com/attachments/398519310798290944/712723151074754610/royalswiw1.png

The donation will be done by AkyZ in the name of Richard.

The resolution has been updated, could I get it re-tested if possible?

**Comment by tutgreco** [comment]
> The resolution has been updated, could I get it re-tested if possible?

You might want to change the following:
- remove fuzzy transitions between white and black paint
- move the text a bit towards the front on the left side (the end of the text is cut off)

**Comment by tutgreco** [comment]
Are you still interested in getting the wrap? @richard42050

**Comment by tutgreco** [comment]
I think it's safe to say that this wrap is not wanted. Please reopen should you see fit.
