### ISSUE TITLE
Custom Wrap | AkyZ

### ISSUE THREAD

**Issue by AkyZ-collab** [saesrpg/donation-vehicle-shaders#82]
**Vehicle ID**
451 | Turismo

**Wrap access**
Everyone can use it, but is **prohibited** to edit it for their own goods.

**Needs testing**
Yes

**Image color profile**
RGB
https://media.discordapp.net/attachments/711403311319875595/712444501829877800/AkyZ.png?width=677&height=677

**Comment by tutgreco** [comment]
The German signs and "I love hentai" needs to be removed if you plan to use it as police cruiser.
451: https://imgur.com/a/DoaIQA1

**Comment by AkyZ-collab** [comment]
It's a turismo, a Lamborghini, not a police vehicle

**Comment by tutgreco** [comment]
It's our intent to have emergency vehicles reflect the true department they're used by. If you don't plan on getting the police edition of the vehicle (which is set by an admin; provides a siren and LED lights) then these criterias don't apply.

You can also read about them here: https://saesrpg.uk/topic/8309/about-donation-wraps

**Comment by AkyZ-collab** [comment]
Ok, I'll do it on turismos and won't add the sirens and lights :)

**Comment by tutgreco** [comment]
Wrap is added as `akyz_1`
