### ISSUE TITLE
SAFP Stone's Custom Vehicle Wrap

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/donation-vehicle-shaders#83]
**Vehicle ID**
598

**Wrap access**
mrslowguy and anyone else who I grant permission to when asked. 

**Needs testing**
Yes
**Image color profile**
N/A

Tut can you please test this for me and send screen shots! 

https://i.imgur.com/qSEzmGA.png

**Comment by tutgreco** [comment]
598: https://imgur.com/a/sV4ywft

**Comment by tutgreco** [comment]
Are you still interested in getting the wrap?

**Comment by MrSlowGuy** [comment]
https://cdn.discordapp.com/attachments/700180497023631390/719686805238317066/safpshader151.png

Sorry! Can you test this one and if it looks good, I'd like it added please! I would also like you to replace mrslowguy_1 with this shader. Thanks.

**Comment by tutgreco** [comment]
598: https://imgur.com/a/0hW5DNJ

**Comment by tutgreco** [comment]
Unfortunately with the new template, the submitted wrap is no longer usable. I'll leave issue open so that you can request a redesigned version.

**Comment by tutgreco** [comment]
I'm closing this, please reopen should you regain interest in sorting the wraps @MrSlowGuy
