### ISSUE TITLE
Jizzy's custom wrap 

### ISSUE THREAD

**Issue by JizzyPro** [saesrpg/donation-vehicle-shaders#84]
**Vehicle ID**
Turismo | 451

**Wrap access**
eliran25802

**Needs testing**
yes

**Image color profile**
https://i.imgur.com/qG5MwxO.jpg

**Comment by tutgreco** [comment]
451: https://imgur.com/a/fu27Asu

**Comment by JizzyPro** [comment]
**Image color profile**
https://i.imgur.com/IrhT1c9.png
can you test this one for me please?

**Comment by tutgreco** [comment]
That'll be your last test. I'm sure you can use the screenshots I've sent as reference.

451: https://imgur.com/a/Zl10qVI

**Comment by JizzyPro** [comment]
im sorry tut i really dont mean or want to bother you that much because im sure you are a busy man so this one doesnt need any testing as this is my very final one im really sorry about all the requests but if i could test it myself trust me i would've done it myself for sure
https://i.imgur.com/UI5d8Fp.png (no testing needed for this one)
ty for all the efforts and help and im really sorry for bothering you

**Comment by tutgreco** [comment]
No problem at all. Until developers creates a system to let people test wraps directly on SAES server, there's nothing more you can do than request us to test them for you.

**Comment by tutgreco** [comment]
Wrap added as `eliran25802_1`
