### ISSUE TITLE
PinkyyyTinkyyys Custom Wrap

### ISSUE THREAD

**Issue by PinkyyyTinkyyy** [saesrpg/donation-vehicle-shaders#85]
**Vehicle ID**
Turismo 451

**Wrap access**

**Needs testing**
Yes please.

**Thread for reward change**
https://saesrpg.uk/topic/18235/donation-pinkyyytinkyyy-amount-40-00-gbp?_=1590584462076
![PINKCAN1](https://user-images.githubusercontent.com/66016253/83022445-71b1d200-a023-11ea-9242-809dcfb0f522.jpg)

**Comment by tutgreco** [comment]
Agreed to adding a grayscale generic wrap as `weed2` instead (on its way)
