### ISSUE TITLE
bas260's custom wrap request

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#86]
**Vehicle ID**
598
**Wrap access**
bas260
**Needs testing**
Yes it needs testing.
**Thread for reward change**
https://saesrpg.uk/topic/19176/bas260-s-reward-change

![San Andreas Interceptors Wrap 003](https://user-images.githubusercontent.com/46720463/83400969-2113ed80-a404-11ea-8f2f-de3bcbede30d.png)

**Vehicle ID**
598
**Wrap access**
bas260
**Needs testing**
Yes it needs testing. This is the same one but without my unit number on top. 
**Thread for reward change**
https://saesrpg.uk/topic/19176/bas260-s-reward-change

![San Andreas Interceptors Wrap Blank](https://user-images.githubusercontent.com/46720463/83401082-53bde600-a404-11ea-9000-56b2895c51f8.png)

**Comment by bas260** [comment]
I'm not sure if the shadows of the door handles and such were supposed to stay added. Velo the designer said you'd probably know. We removed the shadows and such on this version. 
If you read this Tut and if that's the case (that it has to be re-added) please contact me on Discord.

**Comment by tutgreco** [comment]
598: https://imgur.com/a/ZgXve20

**Comment by bas260** [comment]
![San Andreas Interceptors Wrap 003 v2](https://user-images.githubusercontent.com/46720463/83435562-c8ad1200-a43c-11ea-8edc-98755f3e915f.png)

**Comment by bas260** [comment]
![San Andreas Interceptors Wrap 003 v3](https://user-images.githubusercontent.com/46720463/83436355-00688980-a43e-11ea-8f14-685ed8dec0cd.png)
![San Andreas Interceptors Wrap blank v3](https://user-images.githubusercontent.com/46720463/83436356-01012000-a43e-11ea-850b-9cf6c4e56d4c.png)

**Comment by tutgreco** [comment]
598: https://imgur.com/a/uTNNLOz (looks good to me)

**Comment by bas260** [comment]
Looks good to me also

**Comment by tutgreco** [comment]
Added as `bas260_1`, `bas260_2`

**Comment by bas260** [comment]
https://i.imgur.com/o4tQfKr.png
This to replace the one that has the 003 on the roof I don't know which one that is.
The other one is coming.

**Comment by tutgreco** [comment]
@bas260 
598: https://imgur.com/a/ytz5fYq

**Comment by bas260** [comment]
https://cdn.discordapp.com/attachments/716566633849684060/725321423043952670/bascharger1.png

**Comment by tutgreco** [comment]
Both wraps updated
