### ISSUE TITLE
Shader replacement

### ISSUE THREAD

**Issue by Ardron92** [saesrpg/donation-vehicle-shaders#87]
**Vehicle ID**
480

**Wrap access**
king1992

**Needs testing**
yes

**Thread for reward change**
I would like to replace my old ardron92 shader just

Shader:

https://cdn.discordapp.com/attachments/343763594837491713/716992140361596958/gaylords_car.png

**Comment by Ardron92** [comment]
https://i.imgur.com/Aj5dGqv.png
In case first link doesnt work

**Comment by tutgreco** [comment]
480: https://imgur.com/a/RO8r4XW

**Comment by Ardron92** [comment]
Perfect!

**Comment by tutgreco** [comment]
It's being uploaded as `king1992_1` to go in line with the new naming convention

**Comment by tutgreco** [comment]
added as `king1992_1`, old wrap removed
