### ISSUE TITLE
xDarkMan's custom wrap request

### ISSUE THREAD

**Issue by freezer13-jpg** [saesrpg/donation-vehicle-shaders#88]
**Vehicle ID** 482

**Wrap access** freezer13

**Needs testing** yes

**Thread for reward change** https://saesrpg.uk/topic/19202/xdarkman-s-reward-change

![template_Buritto](https://user-images.githubusercontent.com/66308416/83512085-fbecb100-a4cf-11ea-802f-c5e0e39190a5.png)

**Comment by freezer13-jpg** [comment]
@tutgreco preview if possible

**Comment by tutgreco** [comment]
482: https://imgur.com/a/XOrIybJ

**Comment by freezer13-jpg** [comment]
ok I want it it looks sexy.

**Comment by tutgreco** [comment]
added as freezer13_1
