### ISSUE TITLE
MIT Sollozzo's Custom Wraps

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#89]
2 wraps.

---
Wrap name : sollozzo_3

**Vehicle ID**
598 - Police LV

**Wrap access**
sollozzo ; 40salih 

**Needs testing**
No, thanks.

**Thread for reward**
https://saesrpg.uk/topic/19364/donation-sollozzo-amount-40-00-gbp

**Wrap image** : 
https://i.imgur.com/aMusOmp.png

---
Wrap name : sollozzo_4 

**Vehicle ID**
416 - Ambulance

**Wrap access**
sollozzo ; 40salih 

**Needs testing**
Yes, please.

**Thread for reward**
https://saesrpg.uk/topic/19364/donation-sollozzo-amount-40-00-gbp

**Wrap image** : 
(Last update : https://i.imgur.com/Jpd5Jn0.png)

**Comment by tutgreco** [comment]
You currently have 2 other wraps on your server. Do you want to keep those? Having one of each requires a total of at least 80 pounds.

598: https://imgur.com/a/29ebH2j
416: https://imgur.com/a/2LE3JsR

**Comment by SOLLOZZO-SAES** [comment]
The others wrap already ingame (sollozzo_1 and sollozzo_2) was donated in the Brophy's price reducing period (5 pound the custom wrap). 

I sent a new donation today of 40 GPB and my request is splitted like this :

10 GPB for the Police LV + 10 for the custom wrap
; 10 GPB for the Ambulance + 10 for the custom wrap on it

So a total amount of 40 GPB. 

---

The 598 it's okay, I will send you asap a last edit for the 416.
Thanks

**Comment by SOLLOZZO-SAES** [comment]
416 here he is : 
https://i.imgur.com/Jpd5Jn0.png

Both can be pushed without test, thanks.

**Comment by tutgreco** [comment]
598 is added as `sollozzo_3`
416 is added as `sollozzo_4`
