### ISSUE TITLE
Skulion's Custom Vehicle Wrap

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/donation-vehicle-shaders#90]
**Vehicle ID**
482

**Wrap access**
olo1

**Needs testing**
Yes

https://i.imgur.com/3krSqzR.png

**Thread for reward change**
https://saesrpg.uk/topic/19440/skulion-s-reward-change

FYI: I've requested it for Skulion because his github acc is somehow not working. He wanted me to post it so i hope it is not a problem.

**Comment by tutgreco** [comment]
Please use the correct request format that you get when pressing `New issue`.

**Comment by WenDo21** [comment]
Fixed, @tutgreco

**Comment by tutgreco** [comment]
Cool, can you please link the image?

**Comment by WenDo21** [comment]
omg, I forgot to post it sorry, here you go. 

https://i.imgur.com/3krSqzR.png

**Comment by tutgreco** [comment]
482: https://imgur.com/a/tfOtLpc

**Comment by WenDo21** [comment]
We have made a new one wrap, because the previous one is crap. Could you test this one please? @tutgreco 

https://i.imgur.com/Tq2fpsZ.png

**Comment by tutgreco** [comment]
The template is fairly reliable, so what you see in photoshop should be fairly accurate thus i don't deem it in need of testing.

**Comment by WenDo21** [comment]
Okay then, add it to queue to be pushed live when there's update please. Thanks in advance! @tutgreco

**Comment by tutgreco** [comment]
Wrap added as `olo1_1`
