### ISSUE TITLE
bas260's Custom Wrap Request

### ISSUE THREAD

**Issue by bas260** [saesrpg/donation-vehicle-shaders#91]
**Vehicle ID**
596
**Wrap access**
bas260, bardo45
**Needs testing**
No
**Thread for reward change**
Donation in this case 
https://saesrpg.uk/topic/19445/donation-bas260-amount-50-00-gbp
https://i.imgur.com/Rey2tuo.png

**Vehicle ID**
596
**Wrap access**
bas260, bardo45
**Needs testing**
No
**Thread for reward change**
Donation in this case 
https://saesrpg.uk/topic/19445/donation-bas260-amount-50-00-gbp
https://i.imgur.com/RAbcDxO.png

**Comment by tutgreco** [comment]
Black/white 596 added as `bas260_4`
White 596 added as `bas260_5`
