### ISSUE TITLE
MouRiS's Custom Vehicle Wrap

### ISSUE THREAD

**Issue by ryadmahsoudi** [saesrpg/donation-vehicle-shaders#92]
**Vehicle ID**
598

**Wrap access**
only me 

**Needs testing**
yes and send ss pls ! 
https://imgur.com/a/z2MKOUz

**Thread for reward change**
https://saesrpg.uk/topic/19441/donation-mouris-amount-20-gbp/2?_=1591812202592

**Comment by ryadmahsoudi** [comment]
changed the new image link : https://imgur.com/AHwbVaK

**Comment by tutgreco** [comment]
I'm sorry the above still applies. The flag needs to be removed entirely. The SAPA logo will probably have to be removed as well or place it somewhere on the rear end as a sticker if you like, as with its current size and placement it could be interpreted as a SAPA cruiser and not an FBI cruiser.

> Please keep it more neutral and within respect of what a police department's vehicle would look like.

**Comment by tutgreco** [comment]
Hello @ryadmahsoudi I'd just like to follow up, have you made any progress with the wrap?

**Comment by tutgreco** [comment]
I'm closing this, please reopen should you regain interest in sorting the wraps @ryadmahsoudi
