### ISSUE TITLE
Zeno skin request

### ISSUE THREAD

**Issue by midot19** [saesrpg/donation-vehicle-shaders#93]
**Vehicle ID**
 

598
--

**Wrap access**
 midot19

**Needs testing**
 yes

**Thread for reward change**
 https://saesrpg.uk/topic/19506/midot19-reward-change

Tut can you please test this for me and send screen shots!
https://imgur.com/a/J7E4ZZu

**Comment by tutgreco** [comment]
Please correctly export the canvas to image format, what you sent is a screenshot.

**Comment by midot19** [comment]
https://cdn.discordapp.com/attachments/717771149773111456/721012316669214807/template.png

**Comment by tutgreco** [comment]
598: https://imgur.com/a/heX76N6

**Comment by midot19** [comment]
https://cdn.discordapp.com/attachments/717771149773111456/721333253952503828/template.png

pls test it and make car colour mix between white and blue

**Comment by tutgreco** [comment]
598: https://imgur.com/a/T4m53Wj

**Comment by midot19** [comment]
i like this one  request it now

**Comment by tutgreco** [comment]
I'm keeping issue open so that you can submit the new design here (and specify whether it needs testing)

**Comment by tutgreco** [comment]
Uploading one sent by Daryl/Steven instead

**Comment by tutgreco** [comment]
Wrap added as `midot19_1`. Please note that the changes made to the appearence will first go live next week.
