### ISSUE TITLE
Daniel's Custom Vehicle Wrap

### ISSUE THREAD

**Issue by 3Bo0** [saesrpg/donation-vehicle-shaders#94]
**Vehicle ID**
**490** 

**Wrap access**
**3bo010 and xxmrtrollstylexx**

**Needs testing**
**Yes**

**Thread for reward change**
https://saesrpg.uk/topic/19608/donation-daniel-amount-20-00-gbp

https://i.imgur.com/jN3RM5j.png

**Comment by 3Bo0** [comment]
https://i.imgur.com/jN3RM5j.png

**Comment by tutgreco** [comment]
You need to reupload it, the one above is the same link as in OP @3Bo0

**Comment by 3Bo0** [comment]
https://g.top4top.io/p_16305woet1.png

**Comment by 3Bo0** [comment]
I really don't understand why I have to re-upload it again, you can't notice that is my topic has been edited 4 times? :/

**Comment by tutgreco** [comment]
The one in the topic is the same image as the one I quoted you on.

Can you please upload to imgur, as top4top isn't verified on my end.

**Comment by Niklaus-187** [comment]
https://i.imgur.com/C2uit6U.png here you go Tut

**Comment by tutgreco** [comment]
Please make sure that the rear side is in English and most preferably 'call 911' or whatever it's meant to say in your language. The general public should know what it means when it's an emergency vehicle. Like I communicated in the DM.
Other than that it's looking good and I'll send a preview once changes are made.

**Comment by 3Bo0** [comment]
https://i.imgur.com/VeeBc6y.png

**Comment by tutgreco** [comment]
No, I didn't mean you have to add it as an additional marking. I was wondering what Killuminati 187 means on a police vehicle. If you could replace that line with some that belongs in SA it would be cool, so 'call 911' instead would do.

I have already pulled you up on the issue with having foreign language on emergency vehicles. Please see if you can adapt it to be readable and understandable for everyone.

**Comment by 3Bo0** [comment]
**Your requests are endless, this is the last time I'll open the photoshop for you.**
https://i.imgur.com/TLLml0L.png

**Comment by tutgreco** [comment]
I think you're the one that I spoke to in Discord and thoroughly explained why you can't have foreign skins on emergency vehicles. You can also read the wrap rules here: https://saesrpg.uk/topic/8309/about-donation-wraps

Can I please remind you that we're not doing you a service. Donating to the server is your contribution to the server, and any reward that you may be requesting is nothing but a return of appreciation for supporting the upkeep of our platforms. 
Please stick to the guidelines that we enforce, then ask questions if something is unclear.

490: https://imgur.com/a/hzZ3fYn

**Comment by 3Bo0** [comment]
I'm not the one that you talked with, In addition, I did not say anything about " Ay it is my money, oh no my donation! I just said " **Your requests are endless** ".

**Comment by 3Bo0** [comment]
**No need to test, just upload it.**
https://i.imgur.com/4VCUcJs.png

**Comment by tutgreco** [comment]
Wrap added as `3bo010_1`
