### ISSUE TITLE
Jojo's Custom Vehicle Wrap

### ISSUE THREAD

**Issue by jonathdb93** [saesrpg/donation-vehicle-shaders#95]
**Vehicle ID**
598

**Wrap access**
jojofromjory, shadowr, johnnyenglish

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/19612/jojo-s-reward-change

**File**
https://imgur.com/a/ESw30gS

**Comment by SAFPShadro** [comment]
Update
File: https://imgur.com/a/uFdH0sG

**Comment by jonathdb93** [comment]
Original comment changed to use updated image link

**Comment by tutgreco** [comment]
598: https://imgur.com/a/tAAWPl3

**Comment by MTA-Shadro** [comment]
Update: https://imgur.com/a/ESw30gS

**Comment by tutgreco** [comment]
598: https://imgur.com/a/ItT35T5

**Comment by jonathdb93** [comment]
> 598: https://imgur.com/a/ItT35T5

Skin has been verified, green light from our side for https://imgur.com/a/ESw30gS

**Comment by tutgreco** [comment]
Wrap added as `jojofromjory_1`
