### ISSUE TITLE
Niklaus's Custom Vehicle Wrap

### ISSUE THREAD

**Issue by Niklaus-187** [saesrpg/donation-vehicle-shaders#97]
**Vehicle ID**
598

**Wrap access**
xxmrtrollstylexx and FOX Members

**Needs testing**
Yes

**Thread for reward change**
https://saesrpg.uk/topic/19661/donation-niklaus-amount-20-00-gbp?_=1592506482600

**Wrap image**
https://i.imgur.com/sFk4q33.png

**Comment by tutgreco** [comment]
Outdated template. Please get the latest at: https://saesrpg.uk/topic/8309/about-donation-wraps

**Comment by Niklaus-187** [comment]
https://i.imgur.com/xHFT5R6.png what about this?

**Comment by tutgreco** [comment]
No, sorry. We updated the wrap template earlier the week. You need to download it from the linked thread and make changes to the photoshop file.

**Comment by Niklaus-187** [comment]
https://i.imgur.com/BnT1KG8.png now ffs

**Comment by Niklaus-187** [comment]
https://i.imgur.com/xXJ5vg6.png now ffs

**Comment by tutgreco** [comment]
598: https://imgur.com/a/ftlxoNA

**Comment by Niklaus-187** [comment]
Okay I liked it

**Comment by Niklaus-187** [comment]
https://i.imgur.com/P8MkUhj.png upload this just made them small changes no need to test it

**Comment by Niklaus-187** [comment]
Also yeah, make sure that the wrap called "FOX_187"

**Comment by tutgreco** [comment]
> Also yeah, make sure that the wrap called "FOX_187"

Please see #1 for how wraps are named

**Comment by Niklaus-187** [comment]
Oh, okay np

**Comment by tutgreco** [comment]
Wrap added as `xxmrtrollstylexx_1`
