### ISSUE TITLE
Rikki's Custom Wrap Request

### ISSUE THREAD

**Issue by RikKi100** [saesrpg/donation-vehicle-shaders#98]
**Vehicle ID**
519

**Wrap access**
King100

**Needs testing**
yes

**Thread for reward change**
https://saesrpg.uk/topic/19781/donation-exalted-amount-10-00-gbp

**Wrap image
https://i.imgur.com/bgo3IGY.png

@tutgreco pre-view pls

**Comment by tutgreco** [comment]
Have you not previewed it yourself already?

**Comment by RikKi100** [comment]
i did okay nvm then

**Comment by tutgreco** [comment]
Wrap added as `king100_1`, in the future please keep usernames lowercase :+1:
