### ISSUE TITLE
Sanek's custom vehicle wrap

### ISSUE THREAD

**Issue by SanekFox** [saesrpg/donation-vehicle-shaders#99]
**Vehicle ID**
<598>

**Wrap access**
<cahek23>

**Needs testing**
<yes (with open doors pls)>

**Thread for reward change**
<changing my previous wrap, because of update>

**Wrap image
<https://imgur.com/a/ftssrXk>

**Comment by tutgreco** [comment]
I'm currently working on updating the rest of our wraps, so if you want to send over the .psd then I can do the rest if there's any need for it. 

If not, then I'll send a review later as per usual - up to you

**Comment by SanekFox** [comment]
Do your job, I'll wait)

**Comment by tutgreco** [comment]
598: https://imgur.com/a/6FsVIQa

I can look into resolving the edges between white and black paint if you give the .psd after making all the rest adjustments :man_mechanic:

**Comment by SanekFox** [comment]
I forgot to save psd *crying* ;;;;((( i will do another one

**Comment by tutgreco** [comment]
Thanks @SanekFox, but I should be able to correct the edges without any significant issues by just editing the image file. Please let me know if that's fine

**Comment by tutgreco** [comment]
Hey @SanekFox any news on the wrap?

**Comment by tutgreco** [comment]
The fixed wrap of `cahek23_2` is live now.
